(in-package :cl-info)
(let (
(deffn-defvr-pairs '(
; CONTENT: (<INDEX TOPIC> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS> <NODE NAME>))
("boolean_form" . ("logic.info" 11698 539 "Definitions for logic"))
("characteristic_vector" . ("logic.info" 3148 1295 "Definitions for logic"))
("closed_under_f" . ("logic.info" 6521 396 "Definitions for logic"))
("closed_under_t" . ("logic.info" 6919 393 "Definitions for logic"))
("demorgan" . ("logic.info" 12239 378 "Definitions for logic"))
("dual_function" . ("logic.info" 5725 351 "Definitions for logic"))
("functionally_complete" . ("logic.info" 9051 625 "Definitions for logic"))
("linear" . ("logic.info" 8447 602 "Definitions for logic"))
("logic_basis" . ("logic.info" 9678 1436 "Definitions for logic"))
("logic_diff" . ("logic.info" 11116 580 "Definitions for logic"))
("logic_equiv" . ("logic.info" 4994 729 "Definitions for logic"))
("logic_simp" . ("logic.info" 2487 659 "Definitions for logic"))
("monotonic" . ("logic.info" 7314 1131 "Definitions for logic"))
("pcnf" . ("logic.info" 12866 224 "Definitions for logic"))
("pdnf" . ("logic.info" 12619 245 "Definitions for logic"))
("self_dual" . ("logic.info" 6078 441 "Definitions for logic"))
("zhegalkin_form" . ("logic.info" 4445 547 "Definitions for logic"))
))
(section-pairs '(
; CONTENT: (<NODE NAME> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS>))
("Definitions for logic" . ("logic.info" 2434 10656))
("Introduction to logic" . ("logic.info" 386 1922))
)))
(load-info-hashtables (pathname-directory #-gcl *load-pathname* #+gcl sys:*load-pathname*) deffn-defvr-pairs section-pairs))
