(in-package :cl-info)
(let (
(deffn-defvr-pairs '(
; CONTENT: (<INDEX TOPIC> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS> <NODE NAME>))
("boolean_form" . ("logic.info" 11592 541 "Definitions for logic"))
("characteristic_vector" . ("logic.info" 3038 1297 "Definitions for logic"))
("closed_under_f" . ("logic.info" 6415 397 "Definitions for logic"))
("closed_under_t" . ("logic.info" 6813 394 "Definitions for logic"))
("demorgan" . ("logic.info" 12134 380 "Definitions for logic"))
("dual_function" . ("logic.info" 5618 353 "Definitions for logic"))
("functionally_complete" . ("logic.info" 8945 626 "Definitions for logic"))
("linear" . ("logic.info" 8341 603 "Definitions for logic"))
("logic_basis" . ("logic.info" 9572 1437 "Definitions for logic"))
("logic_diff" . ("logic.info" 11010 581 "Definitions for logic"))
("logic_equiv" . ("logic.info" 4886 731 "Definitions for logic"))
("logic_simp" . ("logic.info" 2376 661 "Definitions for logic"))
("monotonic" . ("logic.info" 7208 1132 "Definitions for logic"))
("pcnf" . ("logic.info" 12763 226 "Definitions for logic"))
("pdnf" . ("logic.info" 12515 247 "Definitions for logic"))
("self_dual" . ("logic.info" 5972 442 "Definitions for logic"))
("zhegalkin_form" . ("logic.info" 4336 549 "Definitions for logic"))
))
(section-pairs '(
; CONTENT: (<NODE NAME> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS>))
("Definitions for logic" . ("logic.info" 2324 10665))
("Introduction to logic" . ("logic.info" 385 1813))
)))
(load-info-hashtables (maxima::maxima-load-pathname-directory) deffn-defvr-pairs section-pairs))
