;; Round 3. Logs every INTCV call to *DEBUG-IO*: caller (DINTEXP or LOGX1),
;; b*x^n+a or SOLVE branch, result, time, substitution, limits, integrand.
(in-package :maxima)
(defvar *cv-caller* nil)
(defvar *cv-integrand* nil)
(defun cv-str (e)
  (let ((s (remove #\Newline (format nil "~{~A~}" (mstring e)))))
    (subseq s 0 (min 160 (length s)))))
(let ((orig (fdefinition 'dintexp)))
  (setf (fdefinition 'dintexp)
        (lambda (exp ivar ll ul)
          (let ((*cv-caller* 'dintexp) (*cv-integrand* exp))
            (funcall orig exp ivar ll ul)))))
(let ((orig (fdefinition 'logx1)))
  (setf (fdefinition 'logx1)
        (lambda (exp ll ul ivar)
          (let ((*cv-caller* 'logx1) (*cv-integrand* exp))
            (funcall orig exp ll ul ivar)))))
(let ((orig (fdefinition 'intcv)))
  (setf (fdefinition 'intcv)
        (lambda (nv flag ivar ll ul &rest more)
          (let* ((t0 (get-internal-run-time))
                 (bx (bx**n+a nv ivar))
                 (res (apply orig nv flag ivar ll ul more))
                 (dt (/ (- (get-internal-run-time) t0)
                        internal-time-units-per-second)))
            (format *debug-io* "~&CV|~A|~A|~A|~,3F|~A|~A|~A|~A~%"
                    *cv-caller* (if bx 'bxn 'solve) (if res 'ok 'fail) dt
                    (cv-str nv) (cv-str ll) (cv-str ul) (cv-str *cv-integrand*))
            res))))
