;;; Times every LOADFILE (load() of Lisp files). Nested loads are
;;; counted in their parent too. Report with (loadlog-report "loads.txt").
(in-package :maxima)
(defvar *loadlog-orig* (fdefinition 'loadfile))
(defvar *loadlog* nil)
(setf (fdefinition 'loadfile)
      (lambda (file findp printp)
        (let ((t0 (get-internal-run-time)))
          (multiple-value-prog1 (funcall *loadlog-orig* file findp printp)
            (push (list (namestring file)
                        (/ (- (get-internal-run-time) t0)
                           (float internal-time-units-per-second)))
                  *loadlog*)))))
(defun loadlog-report (out)
  (with-open-file (s out :direction :output :if-exists :supersede)
    (let ((agg (make-hash-table :test 'equal)))
      (dolist (e *loadlog*)
        (let ((x (gethash (first e) agg (list 0 0.0))))
          (setf (gethash (first e) agg) (list (1+ (first x)) (+ (second x) (second e))))))
      (let ((rows (loop for k being the hash-keys of agg using (hash-value v) collect (cons k v))))
        (setq rows (sort rows #'> :key #'third))
        (format s "total ~,3F s in ~D loads~%" (reduce #'+ rows :key #'third) (length *loadlog*))
        (dolist (r rows) (format s "~8,3F ~3D  ~A~%" (third r) (second r) (first r)))))))
