;;; Counts SIGNFACTOR calls by linearity of the sum and by whether
;;; factoring gained a sign, and times each class.
;;;   :lisp (load "profiling/instrumentation/sfstat.lisp")
;;;   run_testsuite(share_tests=true);
;;;   :lisp (sf-report "sfstat.txt")
(in-package :maxima)
(defvar *sf-orig* (fdefinition 'signfactor))
;; key (linear-p . final-sign) -> #(count time)
(defvar *sf* (make-hash-table :test 'equal))
(defun sf-linear-p (x)
  (and (mplusp x)
       (every (lambda (term)
                (flet ((kernelp (f) (or (atom f) (not (or (mexptp f) (mtimesp f) (mplusp f))))))
                  (or (mnump term)
                      (kernelp term)
                      (and (mtimesp term)
                           (<= (count-if-not #'mnump (cdr term)) 1)
                           (every #'kernelp (cdr term))))))
              (cdr x))))
(setf (fdefinition 'signfactor)
      (lambda (x)
        (let ((t0 (get-internal-run-time))
              (lin (sf-linear-p x))
              (before sign))
          (multiple-value-prog1 (funcall *sf-orig* x)
            (let* ((dt (- (get-internal-run-time) t0))
                   ;; SIGN-MPLUS keeps the stronger of BEFORE and SIGN.
                   (gain (and (not (eq sign '$pnz)) (strongp sign before)))
                   (key (list lin (if gain 'gained 'no-gain) sign))
                   (v (or (gethash key *sf*) (setf (gethash key *sf*) (make-array 2 :initial-element 0)))))
              (incf (aref v 0)) (incf (aref v 1) dt))))))
(defun sf-report (out)
  (with-open-file (s out :direction :output :if-exists :supersede)
    (let ((rows (loop for k being the hash-keys of *sf* using (hash-value v) collect (cons k v))))
      (dolist (r (sort rows #'> :key (lambda (r) (aref (cdr r) 1))))
        (format s "~10D ~8,3F s  linear=~A ~A sign=~A~%" (aref (cdr r) 0)
                (/ (aref (cdr r) 1) (float internal-time-units-per-second))
                (first (car r)) (second (car r)) (third (car r)))))))
