;;; Counts plist cells SIMPLIFYA walks for DISTRIBUTE_OVER, OPERS and
;;; OPERATORS, per operator. Report with (ss-report "simpstat.txt").
(in-package :maxima)
(defvar *ss-orig* (fdefinition 'simplifya))
(defvar *ss-ops* (make-hash-table :test 'eq)) ; op -> #(calls steps)
(defvar *ss-calls* 0)
(defvar *ss-steps* 0)
(defun ss-walk (op ind)
  (let ((n 0))
    (do ((pl (symbol-plist op) (cddr pl))) ((atom pl) n)
      (incf n)
      (when (eq (car pl) ind) (return n)))))
(defun ss-record (x)
  (when (and (consp x) (consp (car x)) $simp (not dosimp))
    (let ((op (caar x)))
      (when (and (symbolp op) (not (member 'simp (cdar x))) (not (member op '(rat mrat mqapply))))
        (let ((steps (+ (if $distribute_over (ss-walk op 'distribute_over) 0)
                        (ss-walk op 'opers)
                        (if (get op 'opers) 0 (ss-walk op 'operators)))))
          (incf *ss-calls*) (incf *ss-steps* steps)
          (let ((v (or (gethash op *ss-ops*) (setf (gethash op *ss-ops*) (make-array 2 :initial-element 0)))))
            (incf (aref v 0)) (incf (aref v 1) steps)))))))
(setf (fdefinition 'simplifya)
      (lambda (x y) (ss-record x) (funcall *ss-orig* x y)))
(defun ss-report (out)
  (setf (fdefinition 'simplifya) *ss-orig*)
  (with-open-file (s out :direction :output :if-exists :supersede)
    (format s "dispatching simplifya calls ~:D, plist steps ~:D, mean ~,2F~%" *ss-calls* *ss-steps* (/ *ss-steps* (max 1 *ss-calls*) 1.0))
    (let ((rows (loop for k being the hash-keys of *ss-ops* using (hash-value v) collect (list k (aref v 0) (aref v 1)))))
      (setq rows (sort rows #'> :key #'third))
      (loop for (op c st) in rows repeat 40
            do (format s "~14:D ~14:D ~6,2F  ~S (plist ~D: ~{~S~^ ~})~%" c st (/ st c 1.0) op (/ (length (symbol-plist op)) 2)
                       (loop for (k v) on (symbol-plist op) by #'cddr collect k))))))
