#!/bin/sh
top_srcdir=`dirname $0`
MAXIMA_VERPKGLIBEXECDIR=$top_srcdir/lisp-utils
export MAXIMA_VERPKGLIBEXECDIR
MAXIMA_VERPKGLIBDIR=$top_srcdir/src
export MAXIMA_VERPKGLIBDIR
MAXIMA_INFODIR=$top_srcdir/doc/info
export MAXIMA_INFODIR
MAXIMA_PLOTDIR=$top_srcdir/plotting
export MAXIMA_PLOTDIR

POSIX_SHELL=`head -n 1 $top_srcdir/src/maxima | sed 's/#!//'`
exec $POSIX_SHELL $top_srcdir/src/maxima "$@"
