

gf_set(7,61,x^61+x^4+1);
true;

string(gf_prim);
"x+3";


gf_set(197,24,x^24-x^8+2);
true;

string(gf_prim);
"x+19";


gf_set(5,84,x^84+x^41+x^2+1);
true;

string(gf_prim);
"x^2+1";


gf_set(2,102,x^102+x^29+1);
true;

string(gf_prim);
"x+1";


gf_set(5,61,x^61+x^15+1);
true;

string(gf_prim);
"x-1";


gf_set(8796519617,8,x^8+3*x^6+x+1);
true;

string(gf_prim);
"x+9";


gf_set(3,120,x^120+x^4-1);
true;

string(gf_prim);
"x^3+x^2-1";


gf_set(18659817111137);
true;

gf_log(7);
15962290024269;

