/* Released under terms of the GNU General Public License, version 2,
 * by permission of the authors (Fabrizio Caruso, Jacopo Daurizio, and
 * Alasdair McAndrew) to Robert Dodier circa 2007-12-02.
 */

/* kill(all); */
/* done; */

/* ifactors */
ifactors(226800);
[[2,4],[3,4],[5,2],[7,1]];

/* fasttimes - order does matter */
string(fasttimes(rat(x),rat(1)));
"x";

/* polymod for integers*/
polymod(33,17);
-1;

/* polymod for polynomials*/
polymod(x^2+33*x-12,17);
x^2-x+5;

/* mod - for integers only */
mod(33,17);
16;

/* ?logbitp */
?logbitp(2,181);
true;

?logbitp(0,16);
false;

/* ?ash */
?ash(17,2);
68;

?ash(27,-3);
3;

/* ?integer-length */
?integer\-length(1789);
11;

/* msqrt */
msqrt(289,1789);
[1772, 17];

/* ssqrt */
ssqrt(289,1234567891);
[1234567874, 17];

/* mcbrt */
mcbrt(1331,1789);
[1672, 106, 11];

/* scbrt */
scbrt(1331,1234567891);
[330264042, 11, 904303838];

/* qsplit */
qsplit(1789);
[5, 42];

/* csplit */
csplit(1789);
[12, 35];


