docdraw2d(name,[x]):=if wxplot_size # 'wxplot_size then
	apply('wxdraw2d,x)
else
	(
		apply('draw2d,x),
		print("Press <enter> to continue."),
		readline(stdin)
	)$

docdraw3d(name,[x]):=if wxplot_size # 'wxplot_size then
	apply('wxdraw3d,x)
else
	(
		apply('draw3d,x),
		print("Press <enter> to continue."),
		readline(stdin)
	)$

docdraw(name,[x]):=if wxplot_size # 'wxplot_size then
	apply('wxdraw,x)
else
	(
		apply('draw,x),
		print("Press <enter> to continue."),
		readline(stdin)
	)$
