wxitornot(fun) ::= buildq([fun:fun, wxfun:concat('wx,fun), docfun:concat(doc,fun), doc_fun:concat(doc_,fun), name:gensym("name_"), x:gensym("args_")],
  block(
    docfun(name,[x]) := if wxplot_size # 'wxplot_size then apply('wxfun,x) else
    ( print("Test:",name), apply('fun,x), if demo=true then (print("Press <enter> to continue."), readline(stdin) )),
    alias(doc_fun,docfun))) ;

map(wxitornot,[draw2d,draw3d,draw,julia,mandelbrot,plot2d,plot,plot3d]);
