
/* not found
(kill(all),example("//"));
done; */

(kill(all),example(ADDITIVE));
done;

(kill(all),example(ALGSYS));
done;

(kill(all),example(ALLROOTS));
done;

(kill(all),example(ANTISYMMETRIC));
done;

(kill(all),example(APPEND));
done;

(kill(all),example(ARRAYINFO));
done;

(kill(all),example(ARRAYS));
done;

(kill(all),example(AT));
done;

(kill(all),example(ATVALUE));
done;

(kill(all),example(AUGCOEFMATRIX));
done;

(kill(all),example(BEZOUT));
done;

/* not found
(kill(all),example(BLOCK));
done; */

/* not found
(kill(all),example(BOTHCOEFF));
done; */

(kill(all),example(CATCH));
done;

(kill(all),example(CF));
done;

(kill(all),example(CFDISREP));
done;

(kill(all),example(CFEXPAND));
done;

/* user input required - asks if a > 0
(kill(all),example(CHANGEVAR));
done; */

(kill(all),example(CHARPOLY));
done;

(kill(all),example(COEFF));
done;

(kill(all),example(COMBINE));
done;

(kill(all),example(COMMUTATIVE));
done;

(kill(all),example(COMPLEX));
done;

(kill(all),example(CONTENT));
done;

(kill(all),example(DEFMATCH));
done;

(kill(all),example(DEFTAYLOR));
done;

(kill(all),example(DELETE));
done;

(kill(all),example(DEPENDS));
done;

(kill(all),example(DERIVDEGREE));
done;

(kill(all),example(DESOLVE));
done;

(kill(all),example(DIFF));
done;

(kill(all),example(DISPLAY));
done;

(kill(all),example(DIVIDE));
done;

/* something bad happens
(kill(all),example(DO));
done; */

(kill(all),example(DOTSCRULES));
done;

(kill(all),example(DPART));
done;

(kill(all),example(ECHELON));
done;

(kill(all),example(ELIMINATE));
done;

/* user input required
(kill(all),example(ENTERMATRIX));
done; */

(kill(all),example(EQUATIONS));
done;

(kill(all),example(EV));
done;

(kill(all),example(EVALUATION));
done;

(kill(all),example(EVENFUN));
done;

(kill(all),example(EXP));
done;

(kill(all),example(EXPAND));
done;

(kill(all),example(FACTCOMB));
done;

(kill(all),example(FACTOR));
done;

(kill(all),example(FACTORSUM));
done;

(kill(all),example(FEATUREP));
done;

(kill(all),example(FREEOF));
done;

(kill(all),example(FULLMAP));
done;

(kill(all),example(FULLMAPL));
done;

(kill(all),example(FUNCSOLVE));
done;

(kill(all),example(FUNCTIONS));
done;

(kill(all),example(GENMATRIX));
done;

(kill(all),example(GET));
done;

(kill(all),example(GFACTOR));
done;

(kill(all),example(GRADEF));
done;

(kill(all),example(HORNER));
done;

/* something bad happens
(kill(all),example(IF));
done; */

/* user input required
(kill(all),example(ILT));
done; */

(kill(all),example(INPART));
done;

(kill(all),example(INTEGRATE));
done;

(kill(all),example(IS));
done;

(kill(all),example(ISOLATE));
done;

/* not found
(kill(all),example(LAMBDA));
done; */

(kill(all),example(LAPLACE));
done;

(kill(all),example(LASSOCIATIVE));
done;

(kill(all),example(LET));
done;

(kill(all),example(LETRULES));
done;

(kill(all),example(LIMIT));
done;

(kill(all),example(LINEAR));
done;

(kill(all),example(LINSOLVE));
done;

(kill(all),example(LISTOFVARS));
done;

(kill(all),example(LISTS));
done;

(kill(all),example(LOGCONTRACT));
done;

(kill(all),example(MAP));
done;

(kill(all),example(MATCHDECLARE));
done;

(kill(all),example(MATRICES));
done;

(kill(all),example(MINFACTORIAL));
done;

(kill(all),example(MULTIPLICATIVE));
done;

(kill(all),example(MULTTHRU));
done;

(kill(all),example(NARY));
done;

(kill(all),example(NOUNIFY));
done;

(kill(all),example(NROOTS));
done;

(kill(all),example(NUMFACTOR));
done;

(kill(all),example(NUSUM));
done;

(kill(all),example(ODDFUN));
done;

(kill(all),example(ODE2));
done;

(kill(all),example(OPTIMIZE));
done;

(kill(all),example(ORDERGREAT));
done;

(kill(all),example(ORDERLESS));
done;

(kill(all),example(OUTATIVE));
done;

(kill(all),example(PART));
done;

(kill(all),example(PARTFRAC));
done;

(kill(all),example(PARTITION));
done;

(kill(all),example(PICKAPART));
done;

(kill(all),example(POISSIMP));
done;

(kill(all),example(POLARFORM));
done;

(kill(all),example(POLY_DISCRIMINANT));
done;

(kill(all),example(POSFUN));
done;

(kill(all),example(POWERSERIES));
done;

(kill(all),example(PRINTPROPS));
done;

(kill(all),example(PRODUCT));
done;

(kill(all),example(PROPERTIES));
done;

(kill(all),example(PROPVARS));
done;

(kill(all),example(QUNIT));
done;

(kill(all),example(RADCAN));
done;

(kill(all),example(RANK));
done;

(kill(all),example(RASSOCIATIVE));
done;

/* not found
(kill(all),example(RATCOEFF));
done; */

(kill(all),example(RATDIFF));
done;

(kill(all),example(RATEXPAND));
done;

(kill(all),example(RATSIMP));
done;

(kill(all),example(RATSUBST));
done;

(kill(all),example(RATWEIGHT));
done;

(kill(all),example(REALPART));
done;

(kill(all),example(REALROOTS));
done;

(kill(all),example(RESIDUE));
done;

(kill(all),example(RESULTANT));
done;

(kill(all),example(REVEAL));
done;

(kill(all),example(REVERSE));
done;

(kill(all),example(RISCH));
done;

(kill(all),example(ROOTSCONTRACT));
done;

(kill(all),example(SCANMAP));
done;

(kill(all),example(SCSIMP));
done;

(kill(all),example(SOLVE));
done;

(kill(all),example(SPECINT));
done;

(kill(all),example(SQFR));
done;

/* requires input
(kill(all),example(SUBST));
done; */

(kill(all),example(SUBSTINPART));
done;

(kill(all),example(SUBSTPART));
done;

(kill(all),example(SUM));
done;

(kill(all),example(SYMMETRIC));
done;

(kill(all),example(SYNTAX));
done;

(kill(all),example(TAYLOR));
done;

(kill(all),example(TAYTORAT));
done;

(kill(all),example(TELLRAT));
done;

(kill(all),example(TELLSIMP));
done;

(kill(all),example(TRIANGULARIZE));
done;

(kill(all),example(TRIG));
done;

(kill(all),example(TRIGEXPAND));
done;

(kill(all),example(TRIGREDUCE));
done;

(kill(all),example(UNORDER));
done;

(kill(all),example(XTHRU));
done;

(kill(all),example(ZEROEQUIV));
done;



