jn(3,4);
0.1320341839226408 ;
j0(1);
0.7651976865579665 ;
bessel_j(0,1.0);
0.7651976865579665 ;
bessel(2,3);
bessel(2,3)$
bessel(2,3.0);
0.1289432494744021;
bessel_j(3,2.0);
0.1289432494744021;

bessel_j(-5,x);
-bessel_j(5,x);
bessel_j(-n,x);
bessel_j(-n,x);

diff(bessel_j(0,x),x);
-bessel_j(1,x);
diff(bessel_j(1,x),x);
bessel_j(0,x)-bessel_j(1,x)/x;
diff(bessel_y(0,x),x);
-bessel_y(1,x);
diff(bessel_y(1,x),x);
bessel_y(0,x)-bessel_y(1,x)/x;
diff(bessel_i(0,x),x);
bessel_i(1,x);
diff(bessel_i(1,x),x);
bessel_i(0,x)-bessel_i(1,x)/x;
diff(bessel_k(0,x),x);
-bessel_k(1,x);
diff(bessel_k(1,x),x);
-bessel_k(1,x)/x-bessel_k(0,x);

besselexpand:true;
true$

bessel_j(1/2,x);
sqrt(2/(%pi*x))*sin(x);
bessel_j(-1/2,x);
sqrt(2/(%pi*x))*cos(x);
bessel_j(3/2,x);
2*(1/2)/x*bessel_j(1/2,x)-bessel_j(-1/2,x);
bessel_j(5/2,x);
2*(3/2)/x*bessel_j(3/2,x)-bessel_j(1/2,x);
bessel_j(-3/2,x);
2*(-1/2)/x*bessel_j(-1/2,x)-bessel_j(1/2,x);
bessel_j(-5/2,x);
2*(-3/2)/x*bessel_j(-3/2,x)-bessel_j(-1/2,x);

bessel_y(1/2,x);
-sqrt(2/(%pi*x))*cos(x);
bessel_y(-1/2,x);
sqrt(2/(%pi*x))*sin(x);
bessel_y(3/2,x);
2*(1/2)/x*bessel_y(1/2,x)-bessel_y(-1/2,x);
bessel_y(5/2,x);
2*(3/2)/x*bessel_y(3/2,x)-bessel_y(1/2,x);
bessel_y(-3/2,x);
2*(-1/2)/x*bessel_y(-1/2,x)-bessel_y(1/2,x);
bessel_y(-5/2,x);
2*(-3/2)/x*bessel_y(-3/2,x)-bessel_y(-1/2,x);

bessel_i(1/2,x);
sqrt(2*x/%pi)*sinh(x)/x;
bessel_i(-1/2,x);
sqrt(2*x/%pi)*cosh(x)/x;
bessel_i(3/2,x);
-2*(1/2)/x*bessel_i(1/2,x)+bessel_i(-1/2,x);
bessel_i(5/2,x);
-2*(3/2)/x*bessel_i(3/2,x)+bessel_i(1/2,x);
bessel_i(-3/2,x);
2*(-1/2)/x*bessel_i(-1/2,x)+bessel_i(1/2,x);
bessel_i(-5/2,x);
2*(-3/2)/x*bessel_i(-3/2,x)+bessel_i(-1/2,x);

bessel_k(1/2,x);
sqrt(%pi/(2*x))*%e^(-x);
bessel_k(-1/2,x);
sqrt(%pi/(2*x))*%e^(-x);
bessel_k(3/2,x);
2*(1/2)/x*bessel_k(1/2,x)+bessel_k(-1/2,x);
bessel_k(5/2,x);
2*(3/2)/x*bessel_k(3/2,x)+bessel_k(1/2,x);
bessel_k(-3/2,x);
-2*(-1/2)/x*bessel_k(-1/2,x)+bessel_k(1/2,x);
bessel_k(-5/2,x);
-2*(-3/2)/x*bessel_k(-3/2,x)+bessel_k(-1/2,x);


(assume(p>0),true);
true$
(assume(4*p+a>0),true);
true$
besselexpand:false;
false$

specint(t^(1/2)*%e^(-a*t/4)*%e^(-p*t),t);
sqrt(%pi)/(2*(p+a/4)^(3/2));

specint(t^(3/4)*%e^(-t^2/2/b)*%e^(-p*t),t);
3*gamma(3/4)*b^(7/8)*%e^(b*p^2/4)*(8*sqrt(%pi)*%m[-5/8,-1/4](b*p^2/2)/(3*2^ 
 (5/8)*gamma(3/8)*b^(1/4)*sqrt(p))-2^(3/8)*sqrt(%pi)*%m[-5/8,1/4](b*p^2/2)/ 
 (gamma(7/8)*b^(1/4)*sqrt(p)))/4 $

specint(t^(-1/2)*%e^(-2*a^(1/2)*t^(1/2))*%e^(-p*t),t);
sqrt(2)*%e^(a/(2*p))*(sqrt(%pi)*%e^(a/(2*p))/sqrt(2)-sqrt(2)*sqrt(%pi)*erf 
 (sqrt(a)/sqrt(p))*%e^(a/(2*p))/2)/sqrt(p) $

radcan(specint(sin(a*t)*cosh(b*t^2)*%e^(-p*t),t));
-%e^-((p^2+2*%i*a*p+a^2)/(4*b))*(sqrt(%pi)*%e^((2*%i*a*p+a^2)/(2*b))*erf((%i 
 *p+a)/(2*sqrt(b)))-sqrt(%pi)*%e^(a^2/(2*b))*erf((%i*p-a)/(2*sqrt(b)))+sqrt 
 (%pi)*%i*%e^((p^2+2*%i*a*p)/(2*b))*erf((p+%i*a)/(2*sqrt(b)))-sqrt(%pi)*%i*%e 
 ^(p^2/(2*b))*erf((p-%i*a)/(2*sqrt(b)))+(sqrt(%pi)*%i-sqrt(%pi)*%i*%e^(%i*a 
 *p/b))*%e^(p^2/(2*b))-sqrt(%pi)*%e^((2*%i*a*p+a^2)/(2*b))+sqrt(%pi)*%e^(a^2/ 
 (2*b)))/(8*sqrt(b)) $


specint(t^(1/2)*bessel_j(1,2*a^(1/2)*t^(1/2))*%e^(-p*t),t);
sqrt(a)*%e^-(a/p)/p^2$

specint(t^2*bessel_j(1,a*t)*%e^(-p*t),t);
3*a/((a^2/p^2+1)^(5/2)*p^4) ;
specint(t*hstruve[1](t)*%e^(-p*t),t);
16*(2*p*sqrt(p^2+1)+2*p^2)/(9*%pi^(3/2)*p^4*(2*p*sqrt(p^2+1)+2*p^2+1)) $
radcan(specint(t^(3/2)*hstruve[1](t^(1/2))*%e^(-p*t),t));
%e^-(1/(4*p))*((140*p^(3/2)+10*sqrt(p))*%e^(1/(4*p))+140*sqrt(%pi)*%i*erf(%i/ 
 (2*sqrt(p)))*p^2+20*sqrt(%pi)*%i*erf(%i/(2*sqrt(p)))*p+5*sqrt(%pi)*%i*erf 
 (%i/(2*sqrt(p))))/(8*%pi*p^4) $
 
specint(t*%ibes[0](a*t/2)*%ibes[1](a*t/2)*%e^(-p*t),t);
%ibes[0](a*t/2)*%ibes[1](a*t/2)/p^2 $

specint(t^(3/4)*bessel_j(1/2,t)*bessel_j(1/4,t)*%e^(-p*t),t);
2*%i*(1/(2*%i/p+1)^(3/4)-1/(1-2*%i/p)^(3/4))/(2^(3/4)*gamma(1/4)*p^(3/2)) $

specint(t^(5/2)*bessel_y(1/2,t^(1/2))^2*%e^(-p*t),t);
-12*((-3*sqrt(%pi)*%i*erf(%i/sqrt(p))*p^(5/2)*%e^-(1/p)/8-sqrt(%pi)*%i*erf 
 (%i/sqrt(p))*p^(3/2)*%e^-(1/p)/2-sqrt(%pi)*%i*erf(%i/sqrt(p))*sqrt(p)*%e^- 
 (1/p)/2-3*p^2/4-p/2)/p^2+2*(sqrt(%pi)*%i*erf(%i/sqrt(p))*p^(3/2)*%e^-(1/p)/4 
 +sqrt(%pi)*%i*erf(%i/sqrt(p))*sqrt(p)*%e^-(1/p)/2+p/2)/p-sqrt(%pi)*%i*erf 
 (%i/sqrt(p))*sqrt(p)*%e^-(1/p)/2)/(%pi*p^4) $

specint(t^(1/2)*bessel_j(1/2,t^(1/2))^2*%e^(-p*t),t);
-%i*erf(%i/sqrt(p))*%e^-(1/p)/(sqrt(%pi)*p^(3/2)) $
specint(t^(1/2)*%ibes[1](t)*%e^(-p*t),t);
sqrt(%pi)*%ibes[1](t)/(2*p^(3/2)) $

specint( t*%h[2/3,1](t^(1/2))*%e^(-p*t),t);
-4*%i*gamma(1/3)*%m[-3/2,1/3](-1/(4*p))*%e^-(1/(8*p))/(3*(-1)^(5/6)*sqrt(3) 
 *gamma(2/3)*p^(3/2))+4*gamma(1/3)*%m[-3/2,1/3](-1/(4*p))*%e^-(1/(8*p))/(3*( 
 -1)^(5/6)*gamma(2/3)*p^(3/2))-8*%i*gamma(2/3)*%m[-3/2,-1/3](-1/(4*p))*%e^- 
 (1/(8*p))/(3*(-1)^(1/6)*sqrt(3)*gamma(1/3)*p^(3/2)) $

specint( t^(1/2)*%h[3/4,2](t)*%e^(-p*t),t);
5*%i*assoc_legendre_p(-3/2,-3/4,1/sqrt(1/p^2+1))*gamma(1/4)
       *(1/p^4-1)^(3/8)*p^(9/4)
       /(18*(-1)^(1/4)*sqrt(2)*gamma(3/4)^2)
       +5*assoc_legendre_p(-3/2,-3/4,1/sqrt(1/p^2+1))*gamma(1/4)
	 *(1/p^4-1)^(3/8)*p^(9/4)
	/(18*(-1)^(1/4)*sqrt(2)*gamma(3/4)^2)
       +4*%i*assoc_legendre_p(-3/2,3/4,1/sqrt(1/p^2+1))*gamma(3/4)*p^(3/4)
	/((-1)^(3/4)*gamma(1/4)^2*(1/p^4-1)^(3/8))$

specint( t^(3/2)*%h[1/2,1](t)*%e^(-p*t),t);
4/(sqrt(2)*sqrt(%pi)*(1/p^2+1)^2*p^3)-sqrt(2)*%i*(1/(1/p^2+1)-1/((1/p^2+1)^2 
 *p^2))/(sqrt(%pi)*p^2) $

specint( t^(3/2)*bessel_y(1,a*t)*%e^(-t),t);
15*%i*(1/(a^2+1)-1)^(3/4)*(1/(sqrt(a^2+1)+1)^(3/2)+1/(1-sqrt(a^2+1))^(3/2))/ 
 (16*sqrt(a^2+1)) $

specint( t^2*bessel_j(1,a*t)*%e^(-p*t),t);
3*a/((a^2/p^2+1)^(5/2)*p^4) $

specint(t^(1/2)*bessel_j(1,2*a^(1/2)*t^(1/2))*%e^(-p*t),t);
sqrt(a)*%e^-(a/p)/p^2 $

specint( t^(3/2)*%m[1/2,1](t)*%e^(-p*t),t);
6*(1/(1-1/(p+1/2))+1/((p+1/2)*(1-1/(p+1/2))^2))/(p+1/2)^4 ;
(assume(p>a),true);
true;

specint(%e^(a*t)*t^2*erf(t^(1/2))*%e^(-p*t),t);
15*(1/sqrt(1/(p-a)+1)-1/((p-a)*(1/(p-a)+1)^(3/2))+3/(4*(p-a)^2*(1/(p-a)+1)^ 
 (5/2)))/(4*(p-a)^(7/2)) ;




