/*************** -*- Mode: MACSYMA; Package: MAXIMA -*-  ******************/
/***************************************************************************
***                                                                    *****
***     Copyright (c) 1984 by William Schelter,University of Texas     *****
***     All rights reserved                                            *****
***************************************************************************/


KILL(FUNCTIONS,ARRAYS,VALUES);
DONE$
EV(SIN(X),EXPONENTIALIZE);
-%I*(%E^(%I*X)-%E^-(%I*X))/2$
TAYLOR(SIN(X)/X,X,0,4);
1-X^2/6+X^4/120$
EV(COS(X)^2-SIN(X)^2,SIN(X)^2 = 1-COS(X)^2);
2*COS(X)^2-1$
(SQRT(-4)+SQRT(2.25))^2;
(2*%I+1.5)^2$
EXPAND(%);
6.0*%I-1.75$
EXPAND(SQRT(2*%I));
(-1)^(1/4)*SQRT(2)$
KILL(ALLBUT(PROPS));
DONE$
SIN(X)+COS(Y)+(W+1)^2+'DIFF(SIN(W),W);
COS(Y)+SIN(X)+'DIFF(SIN(W),W,1)+(W+1)^2$
EV(%,SIN,EXPAND,DIFF,X = 2,Y = 1);
COS(W)+W^2+2*W+COS(1)+1.909297426825682;
EV(X+Y,X:A+Y,Y:2);
Y+A+2$
'DIFF(Y^2+X*Y+X^2,X,2,Y,1);
'DIFF(Y^2+X*Y+X^2,X,2,Y,1)$
EV(%,DIFF);
0$
EXP:2*X-3*Y = 3;
2*X-3*Y = 3$
-3*X+2*Y = -4;
2*Y-3*X = -4$
SOLVE([EXP,%]);
[[Y = -1/5,X = 6/5]]$
EV(EXP,%);
3 = 3$
X+1/X > GAMMA(1/2);
X+1/X > SQRT(%PI)$
EV(%,NUMER,X = 1/2);
2.5 > 1.772453850905516;
/* tops 20 :2.5 > 1.77245384$ */
EV(%,PRED);
TRUE$
ZEROEQUIV(SIN(2*X)-2*SIN(X)*COS(X),X);
TRUE$
ZEROEQUIV(%E^X+X,X);
FALSE$
ZEROEQUIV(LOG(A*B)-LOG(A)-LOG(B),A);
DONTKNOW$
(1/(X+Y)^4-3/(Y+Z)^3)^2;
(1/(Y+X)^4-3/(Z+Y)^3)^2$
EXPAND(%,2,0);
-6/((Y+X)^4*(Z+Y)^3)+9/(Z+Y)^6+1/(Y+X)^8$
EXPAND(A . (B+C . (D+E)+F));
A . F+A . C . E+A . C . D+A . B$
EXPAND((X+1)^3);
X^3+3*X^2+3*X+1$
EXP:(X+1)^7;
(X+1)^7$
EXPAND(%);
X^7+7*X^6+21*X^5+35*X^4+35*X^3+21*X^2+7*X+1$
EXPAND(EXP,7,7);
X^7+7*X^6+21*X^5+35*X^4+35*X^3+21*X^2+7*X+1$
EV(A*(B+C)+A*(B+C)^2,EXPOP:1);
A*(C+B)^2+A*C+A*B$
RATEXPAND((2*X-3*Y)^3);
-27*Y^3+54*X*Y^2-36*X^2*Y+8*X^3$
EXP:(X-1)/(X+1)^2+1/(X-1);
(X-1)/(X+1)^2+1/(X-1)$
EXPAND(%);
X/(X^2+2*X+1)-1/(X^2+2*X+1)+1/(X-1)$
RATEXPAND(EXP);
2*X^2/(X^3+X^2-X-1)+2/(X^3+X^2-X-1)$
SIN(X/(X^2+X)) = %E^((LOG(X)+1)^2-LOG(X)^2);
SIN(X/(X^2+X)) = %E^((LOG(X)+1)^2-LOG(X)^2)$
RATSIMP(%);
SIN(1/(X+1)) = %E*X^2$
B*(A/B-X)+B*X+A;
B*X+B*(A/B-X)+A$
RATSIMP(%);
2*A$
((X-1)^(3/2)-(X+1)*SQRT(X-1))/SQRT(X-1)/SQRT(X+1);
((X-1)^(3/2)-SQRT(X-1)*(X+1))/(SQRT(X-1)*SQRT(X+1))$
RATSIMP(%);
-2/SQRT(X+1)$
EV(X^(A+1/A),RATSIMPEXPONS);
X^((A^2+1)/A)$
(LOG(X^2+X)-LOG(X))^A/LOG(X+1)^(A/2);
(LOG(X^2+X)-LOG(X))^A/LOG(X+1)^(A/2)$
RADCAN(%);
LOG(X+1)^(A/2)$
LOG(A^(2*X)+2*A^X+1)/LOG(A^X+1);
LOG(A^(2*X)+2*A^X+1)/LOG(A^X+1)$
RADCAN(%);
2$
(%E^X-1)/(%E^(X/2)+1);
(%E^X-1)/(%E^(X/2)+1)$
RADCAN(%);
%E^(X/2)-1$
KILL(ALLBUT(PROPS));
DONE$
COMBINE(A/X+B/X+A/Y+B/Y);
(B+A)/Y+(B+A)/X$
X/(X-Y)^2-1/(X-Y)-F(X)/(X-Y)^3;
-1/(X-Y)+X/(X-Y)^2-F(X)/(X-Y)^3$
MULTTHRU((X-Y)^3,%);
-(X-Y)^2+X*(X-Y)-F(X)$
RATEXPAND(%);
-Y^2+X*Y-F(X)$
((A+B)^10*S^2+2*A*B*S+(A*B)^2)/(A*B*S^2);
((B+A)^10*S^2+2*A*B*S+A^2*B^2)/(A*B*S^2)$
MULTTHRU(%);
2/S+A*B/S^2+(B+A)^10/(A*B)$
MULTTHRU(A . (B+C . (D+E)+F));
A . F+A . C . (E+D)+A . B$
((X+2)^20-2*Y)/(X+Y)^20+(X+Y)^-19-X/(X+Y)^20;
1/(Y+X)^19+((X+2)^20-2*Y)/(Y+X)^20-X/(Y+X)^20$
XTHRU(%);
((X+2)^20-Y)/(Y+X)^20$
2/(X+2)-2/(X+1)+1/(X+1)^2;
2/(X+2)-2/(X+1)+1/(X+1)^2$
RATSIMP(%);
-X/(X^3+4*X^2+5*X+2)$
PARTFRAC(%,X);
2/(X+2)-2/(X+1)+1/(X+1)^2$
FACTOR(2^63-1);
7^2*73*127*337*92737*649657$
FACTOR(Z^2*(X+2*Y)-4*X-8*Y);
(2*Y+X)*(Z-2)*(Z+2)$
X^2*Y^2+2*X*Y^2+Y^2-X^2-2*X-1;
X^2*Y^2+2*X*Y^2+Y^2-X^2-2*X-1$
BLOCK([DONTFACTOR:[X]],FACTOR(%/36/(Y^2+2*Y+1)));
(X^2+2*X+1)*(Y-1)/(36*(Y+1))$
FACTOR(%E^(3*X)+1);
(%E^X+1)*(%E^(2*X)-%E^X+1)$
FACTOR(X^4+1,A^2-2);
(X^2-A*X+1)*(X^2+A*X+1)$
FACTOR(X^3+X^2*Y^2-X*Z^2-Y^2*Z^2);
-((Y^2+X)*(Z-X)*(Z+X))$
(X+2)/(X+3)/(X+B)/(X+C)^2;
(X+2)/((X+3)*(X+B)*(X+C)^2)$
RATSIMP(%);
(X+2)/(X^4+(2*C+B+3)*X^3+(C^2+(2*B+6)*C+3*B)*X^2+((B+3)*C^2+6*B*C)*X+3*B*C^2)$
PARTFRAC(%,X);
-(C^2-4*C-B+6)/((C^4+(-2*B-6)*C^3+(B^2+12*B+9)*C^2+(-6*B^2-18*B)*C+9*B^2)
	       *(X+C))
 -(C-2)/((C^2+(-B-3)*C+3*B)*(X+C)^2)
 +(B-2)/(((B-3)*C^2+(6*B-2*B^2)*C+B^3-3*B^2)*(X+B))
 -1/(((B-3)*C^2+(18-6*B)*C+9*B-27)*(X+3))$
MAP('FACTOR,%);
-((C^2-4*C-B+6)/((C-3)^2*(C-B)^2*(X+C)))-((C-2)/((C-3)*(C-B)*(X+C)^2))
				      +(B-2)/((B-3)*(C-B)^2*(X+B))
				      -(1/((B-3)*(C-3)^2*(X+3)))$
EXP:RATSIMP((X^5-1)/(X-1));
X^4+X^3+X^2+X+1$
SUBST(A,X,%);
A^4+A^3+A^2+A+1$
FACTOR(EXP,%);
(X-A)*(X-A^2)*(X-A^3)*(X+A^3+A^2+A+1)$
FACTOR(X^12+1);
(X^4+1)*(X^8-X^4+1)$
FACTOR(X^99+1);
(X+1)*(X^2-X+1)*(X^6-X^3+1)*(X^10-X^9+X^8-X^7+X^6-X^5+X^4-X^3+X^2-X+1)
     *(X^20+X^19-X^17-X^16+X^14+X^13-X^11-X^10-X^9+X^7+X^6-X^4-X^3+X+1)
     *(X^60+X^57-X^51-X^48+X^42+X^39-X^33-X^30-X^27+X^21+X^18-X^12-X^9+X^3+1)$
EV((X+1)*((U+V)^2+A*(W+Z)^2),EXPAND);
A*X*Z^2+A*Z^2+2*A*W*X*Z+2*A*W*Z+A*W^2*X+V^2*X+2*U*V*X+U^2*X+A*W^2+V^2+2*U*V
       +U^2$
FACTORSUM(%);
(X+1)*(A*(Z+W)^2+(V+U)^2)$
SQFR(4*X^4+4*X^3-3*X^2-4*X-1);
(2*X+1)^2*(X^2-1)$
GFACTOR(X^4-1);
(X-1)*(X+1)*(X-%I)*(X+%I)$
factor(Y^20-7*Y^19+11*Y^18-8*Y^17+59*Y^16-461*Y^15+1694*Y^14+198*Y^13-3541*
 Y^12+2818*Y^11-33327*Y^10-11272*Y^9-56656*Y^8-12672*Y^7+433664*Y^6+472064*Y^5
 +241664*Y^4+131072*Y^3+720896*Y^2+1835008*Y+1048576);
(Y^8-Y^7-11*Y^6-19*Y^5+101*Y^4+76*Y^3-176*Y^2+64*Y+256)
      *(Y^12-6*Y^11+16*Y^10-39*Y^9-19*Y^8-75*Y^7-315*Y^6+300*Y^5-304*Y^4
	    +2496*Y^3+4096*Y^2+6144*Y+4096)$
	      
