(kill (all), 0);
0;

[a, b, c]: [x, y, z];
[x, y, z];

[x, y, z]: [11, 22, 33];
[11, 22, 33];

[''a, ''b, ''c];
[11, 22, 33];

[x, y, z]: x*y*z;
[7986, 7986, 7986];

[x, y, z];
[7986, 7986, 7986];

(kill (a, b), [a, b]: [b, 2*a]);
'[b, 2*a];

[a, b]: [b, 2*a];
'[2*a, 2*b];

[a, b]: [b, 2*a];
'[2*b, 4*a];

[a, b]: [b, 2*a];
'[4*a, 4*b];

[a, b]: [b, 2*a];
'[4*b, 8*a];

(kgcd(a, b) := (while b#0 do [a, b]: [b, remainder(a, b)], abs(a)), kgcd(11*7*5*3, 17*13*11*7));
gcd (11*7*5*3, 17*13*11*7);

(i:10, j:20, [i, j] : [j, i]);
[20, 10];

[i, j];
[20, 10];

/* QUESTIONABLE. MAYBE THIS ONE SHOULD CAUSE AN ERROR */
[i, i] : [1, 2];
[1, 2];

/* QUESTIONABLE. MAYBE PRECEDING ASSIGNMENT SHOULD HAVE FAILED */
i;
2;

a : [1, 2, 3, 4];
[1, 2, 3, 4];

(i : 2, [i, a[i]] : [4, 11]);
[4, 11];

a;
[1, 11, 3, 4];

[ a[1], a[2] ] : [ a[3], a[4] ];
[3, 4];

a;
[3, 4, 3, 4];

(a : [1, 2, 3, 4], i:0, [ a[i : i + 1], a[i : i + 1] ] : [ a[i : i + 1], a[i : i + 1] ]);
[1, 2];

a;
[1, 2, 1, 2];

