/*************** -*- Mode: MACSYMA; Package: MAXIMA -*-  ******************/
/***************************************************************************
***                                                                    *****
***     Copyright (c) 1984 by William Schelter,University of Texas     *****
***     All rights reserved                                            *****
***************************************************************************/


matchfix("{","}");
"{"$
infix("|");
"|"$
exp1:{x | x > 0};
{x | x > 0}$
exp2:{x | x < 2};
{x | x < 2}$
infix("ou");
"ou"$
infix("oi");
"oi"$
exp1 ou exp2;
{x | x > 0} ou {x | x < 2}$
exp1 ou exp2;
{x | x > 0} ou {x | x < 2}$
exp1:{1,2,3};
{1,2,3}$
{3,4,5};
{3,4,5}$
exp1 ou exp1 ou %;
{1,2,3} ou {1,2,3} ou {3,4,5}$
infix("ou",100,100);
"ou"$
exp2:infix("oi",120,120);
"oi"$
exp1 ou exp1 ou {7};
{1,2,3} ou {1,2,3} ou {7}$
/* Make sure we didn't make the uppercase versions also operators */
x + OU;
x + OU$
x + OI;
x + OI$
/*kill("ou");*/
remove("ou",operator);
done$
foo(ou);
foo(ou);


