/*************** -*- Mode: MACSYMA; Package: MAXIMA -*-  ******************/
/***************************************************************************
***                                                                    *****
***     Copyright (c) 1984 by William Schelter,University of Texas     *****
***     All rights reserved                                            *****
***************************************************************************/

kill(allbut(props));
done;
X^2*'DIFF(Y,X,1)+3*X*Y = SIN(X)/X;
X^2*'DIFF(Y,X,1)+3*X*Y = SIN(X)/X$
SOLN1:ODE2(%,Y,X);
Y = (%C-COS(X))/X^3$
IC1(SOLN1,X = %PI,Y = 0);
Y = -(COS(X)+1)/X^3$
'DIFF(Y,X,2)+Y*('DIFF(Y,X,1))^3 = 0;
'DIFF(Y,X,2)+Y*('DIFF(Y,X,1))^3 = 0$
SOLN2:ODE2(%,Y,X);
(Y^3+6*%K1*Y)/6 = X+%K2$
RATSIMP(IC2(SOLN2,X = 0,Y = 0,'DIFF(Y,X,1) = 2));
-(2*Y^3-3*Y)/6 = X$
BC2(SOLN2,X = 0,Y = 1,X = 1,Y = 3);
(Y^3-10*Y)/6 = X-3/2$
EXP:K^2*N^2+K^2*M^2*N^2-K^2*L^2*N^2-K^2*L^2*M^2*N^2;
-K^2*L^2*M^2*N^2+K^2*M^2*N^2-K^2*L^2*N^2+K^2*N^2$
EQ1:K^2+L^2 = 1;
L^2+K^2 = 1$
EQ2:N^2-M^2 = 1;
N^2-M^2 = 1$
SCSIMP(EXP,EQ1,EQ2);
K^4*N^4$
EXQ:(K1*K4-K1*K2-K2*K3)/K3^2;
(K1*K4-K2*K3-K1*K2)/K3^2$
EQ3:K1*K4-K2*K3 = 0;
K1*K4-K2*K3 = 0$
EQ4:K1*K2+K3*K4 = 0;
K3*K4+K1*K2 = 0$
SCSIMP(EXQ,EQ3,EQ4);
K4/K3$
EXP1:2*X^2+Y*X+Z;
Z+X*Y+2*X^2$
EXP2:3*X+5*Y-Z-1;
-Z+5*Y+3*X-1$
EXP3:Z^2+X-Y^2+5;
Z^2-Y^2+X+5$
ELIMINATE([EXP3,EXP2,EXP1],[Y,Z]);
[7425*X^8-1170*X^7+1299*X^6+12076*X^5+22887*X^4-5154*X^3-1291*X^2+7688*X+15376]$
EQN1:'DIFF(F(X),X) = 'DIFF(G(X),X)+SIN(X);
'DIFF(F(X),X,1) = 'DIFF(G(X),X,1)+SIN(X)$
EQN2:'DIFF(G(X),X,2) = 'DIFF(F(X),X)-COS(X);
'DIFF(G(X),X,2) = 'DIFF(F(X),X,1)-COS(X)$
ATVALUE('DIFF(G(X),X),X = 0,A);
A$
ATVALUE(F(X),X = 0,1);
1$
/* The matchfix stuff seems to work but is difficult for batch to parse and check
 MATCHFIX("{","}");
"{"$
INFIX("|");
"|"$
EXP1:{X | X > 0};
{X | X > 0}$
EXP2:{X | X < 2};
{X | X < 2}$
INFIX("OU");
OU$
INFIX("OI");
OI$
EXP1 OU EXP2;
{X | X > 0} OU {X | X < 2}$
EXP1 OU EXP2;
{X | X > 0} OU {X | X < 2}$
EXP1:{1,2,3};
{1,2,3}$
{3,4,5};
{3,4,5}$
EXP1 OU EXP1 OU %;
{1,2,3} OU {1,2,3} OU {3,4,5}$
INFIX("ou",100,100);
OU$
EXP2:INFIX("OI",120,120);
OI$
EXP1 OU EXP1 OU %;
{1,2,3} OU {1,2,3} OU OI$
REMOVE("ou",OPERATOR);
DONE$
ERRCATCH(EXP1 OU EXP2);
[{1,2,3} OU OI]$  */
