(kill (all), reset (linel), 0);
0;

/* tests adapted from tests/rtest3.mac */

declare_index_properties
 (E, [postsubscript, postsuperscript, presuperscript, presubscript],
  G, [postsubscript, postsuperscript, presuperscript, presubscript,
      postsuperscript, presubscript]);
done;

block ([display2d_unicode: true], with_default_2d_display ([S: make_string_output_stream ()],
  with_stdout (S, ?terpri (), print ((1 - G[a, b, c, d, w, x])/E[1, 1/2, 2/3, 17/29])),
  get_output_stream_string (S)));
"
       c b, w
1 -     G
    d, x a
───────────── 
    2/3 1/2
       E
  17/29 1
";

(print_string_2d (e) := with_default_2d_display (printf (false, "~m", e)), 0);
0;

block ([display2d_unicode: true], print_string_2d (lsum(1/f(g(x)/h(x)), x, LOOOOOOOOONG_EXPR)));
"____
╲                         1
 ⟩                     ───────
╱                        g(x)
‾‾‾‾                   f(────)
x in LOOOOOOOOONG_EXPR   h(x)
"$

/* other examples which call DSUMPROD in test suite */

block ([display2d_unicode: true], print_string_2d ('sum(x^k / k,k,1,inf)));
"inf
____   k
╲     x
 ⟩    ──
╱     k
‾‾‾‾
k = 1
"$

block ([display2d_unicode: true], print_string_2d (subst (k = \*index, 'sum(x^k / k,k,1,inf))));
"inf
____        *index
╲          x
 ⟩         ───────
╱          *index
‾‾‾‾
*index = 1
"$

block ([display2d_unicode: true], print_string_2d ('sum(i!,i,1,4)));
" 4
____
╲
 ⟩    i!
╱
‾‾‾‾
i = 1
"$

block ([display2d_unicode: true], print_string_2d ('sum(g(i),i,0,n)));
" n
____
╲
 ⟩    g(i)
╱
‾‾‾‾
i = 0
"$

block ([display2d_unicode: true], print_string_2d ('sum(g(i),i,0,n) + 1));
" n
____
╲
 ⟩    g(i) + 1
╱
‾‾‾‾
i = 0
"$

block ([display2d_unicode: true], print_string_2d (foo: unsum(product(i^2,i,1,n),n)));
"  n - 1
 ─┬───┬─
  │   │  2
( │   │ i ) (n - 1) (n + 1)
  │   │
  i = 1
"$

block ([display2d_unicode: true], print_string_2d (nusum(foo,n,1,n)));
"   n
─┬───┬─
 │   │  2
 │   │ i  - 1
 │   │
 i = 1
"$

block ([display2d_unicode: true], print_string_2d (niceindices (powerseries(log(sin(x)/x),x,0))));
"inf
____       i  2 i - 1            2 i
╲     (- 1)  2        bern(2 i) x
 ⟩    ──────────────────────────────
╱                i (2 i)!
‾‾‾‾
i = 1
"$

block ([display2d_unicode: true], print_string_2d (product((x^i+1)^2.5,i,1,inf)/(x^2+1)));
"  inf
─┬───┬─
 │   │   i     2.5
 │   │ (x  + 1)
 │   │
 i = 1
 ─────────────────
       2
      x  + 1
"$

/* additional DSUMPROD examples */

block ([display2d_unicode: true], print_string_2d ('lsum(1/(1+f(x)/2), kskdsksdkkdksdksd, w999393293923939losl)));
"____
╲                                            1
 ⟩                                        ────────
╱                                         f(x)
‾‾‾‾                                      ──── + 1
kskdsksdkkdksdksd in w999393293923939losl  2
"$

block ([display2d_unicode: true], print_string_2d ('lsum(1/(1+f(x)/2), kskdsksdkkdksdksd, w999393293923939losl^2)));
"____
╲                                             1
 ⟩                                         ────────
╱                                          f(x)
‾‾‾‾                                       ──── + 1
                                         2  2
kskdsksdkkdksdksd in w999393293923939losl
"$

block ([display2d_unicode: true], print_string_2d ('lsum(1/(1+f(x)/2), kskdsksdkkdksdksd, w999393293923939losl^skdkskdsk)));
"____
╲                                                     1
 ⟩                                                 ────────
╱                                                  f(x)
‾‾‾‾                                               ──── + 1
                                         skdkskdsk  2
kskdsksdkkdksdksd in w999393293923939losl
"$

block ([display2d_unicode: true], print_string_2d (' ?rat(a, b)));
"a
─
b
";

block ([display2d_unicode: true], print_string_2d (' "/"(a, b)));
"a
─
b
";

block ([display2d_unicode: true], print_string_2d ('matrix([a, b, c])));
"┌         ┐
│ a  b  c │
└         ┘
";

block ([display2d_unicode: true], print_string_2d ('?mbox(a)));
"╔═╗
║a║
╚═╝
";

block ([display2d_unicode: true], print_string_2d ('?mlabox (a, b)));
"b═╗
║a║
╚═╝
";

/* tests adapted from tests/rtest9a.mac */

(verify_display_2d (expr, expected_output) :=
  block ([S, output],
    with_default_2d_display
     (S : make_string_output_stream (),
      with_stdout (S, print (expr)),
      output : get_output_stream_string (S),
      close (S),
      if is (output = expected_output) then true else [expected_output, output])),
 verify_display_1d (expr, expected_output) :=
   block ([output : string (expr)], if is (output = expected_output) then true else [expected_output, output]),
 0);
0;

/* increase linel so next few test cases avoid Lisp error when run_testsuite(display_all = true)
 * workaround for SF bug https://sourceforge.net/p/maxima/bugs/4234/
 */

linel: 140;
140;

block ([powerdisp : false, display2d_unicode: true],
  verify_display_2d ((x+1)/(x+2),
"x + 1
───── 
x + 2
"));
true;

block ([powerdisp : true, display2d_unicode: true],
  verify_display_2d ((x+1)/(x+2),
"1 + x
───── 
2 + x
"));
true;

(reset (linel), 0);
0;

(H : ( n2 * s^2 + n1 * s + n0 ) / ( d2 * s^2 + d1 * s + d0 ), 0);
0;

block ([powerdisp : false, display2d_unicode: true], verify_display_2d (H,
"    2
n2 s  + n1 s + n0
───────────────── 
    2
d2 s  + d1 s + d0
"));
true;

block ([powerdisp : true, display2d_unicode: true], verify_display_2d (H,
"                2
n0 + n1 s + n2 s
───────────────── 
                2
d0 + d1 s + d2 s
"));
true;

/* copied print_string_2d from rtest3.mac */
(print_string_2d (e) := with_default_2d_display (printf (false, "~m", e)), 0);
0;

block ([display2d_unicode: true], print_string_2d (-a/b));
"  a
- ─
  b
";

string (-a/b);
"-(a/b)";

block ([display2d_unicode: true], print_string_2d (-(a/b)));
"  a
- ─
  b
";

string (-(a/b));
"-(a/b)";

block ([display2d_unicode: true], print_string_2d ((-a)/b));
"  a
- ─
  b
";

block ([display2d_unicode: true], print_string_2d (-(a + b)/c));
"- b - a
───────
   c
";

string (-(a + b)/c);
"(-b-a)/c";

block ([display2d_unicode: true], print_string_2d ((-(a + b))/c));
"- b - a
───────
   c
";

string ((-(a + b))/c);
"(-b-a)/c";

block ([display2d_unicode: true], print_string_2d (-((a + b)/c)));
"  b + a
- ─────
    c
";

/* tests adapted from share/stringproc/rtestprintf.mac */

block ([display2d_unicode: true],
       with_default_2d_display(printf (false, "~m~%", 1/2)));
"1
─
2
";

block ([display2d_unicode: true],
       with_default_2d_display(block ([s: make_string_output_stream ()],
                                      printf (s, "~m~%", 1/2),
                                      get_output_stream_string (s))));
"1
─
2
";

block ([display2d_unicode: true],
       with_default_2d_display(printf (false, "~m, ~a, ~:m, ~@m, ~d~%", (1 + x)/(1 - x), (1 + x)/(1 - x), (1 + x)/(1 - x), (1 + x)/(1 - x), 1234)));
"x + 1                            x + 1
─────, (x+1)/(1-x), (x+1)/(1-x), ─────, 1234
1 - x                            1 - x
";

block ([display2d_unicode: true],
       with_default_2d_display(block ([s: make_string_output_stream ()],
                                      printf (s, "~m, ~a, ~:m, ~@m, ~d~%", (1 + x)/(1 - x), (1 + x)/(1 - x), (1 + x)/(1 - x), (1 + x)/(1 - x), 1234),
                                      get_output_stream_string (s))));
"x + 1                            x + 1
─────, (x+1)/(1-x), (x+1)/(1-x), ─────, 1234
1 - x                            1 - x
";

block ([display2d_unicode: true],
       with_default_2d_display(printf (false, "~~m ~~:m ~~~~@m ~m, ~a, ~:m, ~@m, ~d ~~z ~~~~z ~~~~~~y~%", (1 + x)/(1 - x), (1 + x)/(1 - x), (1 + x)/(1 - x), (1 + x)/(1 - x), 1234)));
"            x + 1                            x + 1
~m ~:m ~~@m ─────, (x+1)/(1-x), (x+1)/(1-x), ─────, 1234 ~z ~~z ~~~y
            1 - x                            1 - x
";

block ([display2d_unicode: true],
       with_default_2d_display(block ([s: make_string_output_stream ()],
                                      printf (s, "~~m ~~:m ~~~~@m ~m, ~a, ~:m, ~@m, ~d ~~z ~~~~z ~~~~~~y~%", (1 + x)/(1 - x), (1 + x)/(1 - x), (1 + x)/(1 - x), (1 + x)/(1 - x), 1234),
                                      get_output_stream_string (s))));
"            x + 1                            x + 1
~m ~:m ~~@m ─────, (x+1)/(1-x), (x+1)/(1-x), ─────, 1234 ~z ~~z ~~~y
            1 - x                            1 - x
";

/* additional tests covering integrate, sum, lsum, product, diff, at, abs, matrix, box, labeled box, dpart, and ratio. */

(kill (all),
 print_string_2d_unicode (e) := block ([display2d_unicode: true], with_default_2d_display (printf (false, "~m", e))),
 0);
0;

block ([simp: false], print_string_2d_unicode ([abs(1/2), abs(x[n]), abs(x^2)]));
" │1│        │ 2│
[│─│, │x │, │x │]
 │2│  │ n│
";

(M: [matrix ([a]), matrix ([a, b], [c, d]), matrix ([a, b, c], [d, e, f], [g, h, i])],
 print_string_2d_unicode (M));
"                  ┌         ┐
        ┌      ┐  │ a  b  c │
 ┌   ┐  │ a  b │  │         │
[│ a │, │      │, │ d  e  f │]
 └   ┘  │ c  d │  │         │
        └      ┘  │ g  h  i │
                  └         ┘
";

print_string_2d_unicode (matrix (M));
"┌                              ┐
│                  ┌         ┐ │
│        ┌      ┐  │ a  b  c │ │
│ ┌   ┐  │ a  b │  │         │ │
│ │ a │  │      │  │ d  e  f │ │
│ └   ┘  │ c  d │  │         │ │
│        └      ┘  │ g  h  i │ │
│                  └         ┘ │
└                              ┘
";

print_string_2d_unicode (transpose (matrix (M)));
"┌             ┐
│    ┌   ┐    │
│    │ a │    │
│    └   ┘    │
│             │
│  ┌      ┐   │
│  │ a  b │   │
│  │      │   │
│  │ c  d │   │
│  └      ┘   │
│             │
│ ┌         ┐ │
│ │ a  b  c │ │
│ │         │ │
│ │ d  e  f │ │
│ │         │ │
│ │ g  h  i │ │
│ └         ┘ │
└             ┘
";

print_string_2d_unicode ('at(u, u='sum(x[k],k,1,n)));
" │    ____
u│    ╲
 │u =  ⟩    x
      ╱      k
      ‾‾‾‾
      k = 1
";

(e1a: 'integrate (f (u), u),
 e1b: 'integrate (f (u), u, 0, 1),
 e2: 'sum (g[k], k, 1, m),
 e3: 'lsum (v[k]^2, k, L),
 e4: 'product (N[i], i, 1, inf),
 e5: 'diff (h (u[i], v[j], w[k]), u[i], 3, v[j], 2, w[k], 1),
 e6a: 'at (u, u = 0),
 e6b: 'at (1/(1 + 1/f(u, v)), [u = 0, v = 1]),
 e7: abs (1/p[q[r[s[0]]]]^n),
 e8a: matrix (makelist (y[i], i, 1, 10)),
 e8b: transpose (e8a),
 e8c: e8b . e8a,
 e9a: box (u),
 e9b: box (u[1]),
 e9c: box (u^n),
 e9d: box (1 - 1/u[1]^n),
 e10a: box (u, foo),
 e10b: box (u[1], bar),
 e10c: box (u^n, baz),
 e10d: box (1 - 1/u[1]^n, quux),
 e11: dpart (x+y/z^2, 1, 2, 1),
 e12: expand ((x[k] - y[l])^3 - 1) / (1234 - 456/(a[i] - b[j])^3),
 0);
0;

print_string_2d_unicode(e1a);
"⌠
⎮
⎮ f(u) du
⎮
⌡
"$

print_string_2d_unicode(e1b);
" 1
⌠
⎮
⎮  f(u) du
⎮
⌡
 0
"$

print_string_2d_unicode(e2);
" m
____
╲
 ⟩    g
╱      k
‾‾‾‾
k = 1
"$

print_string_2d_unicode(e3);
"____
╲       2
 ⟩     v
╱       k
‾‾‾‾
k in L
"$

print_string_2d_unicode(e4);
"  inf
─┬───┬─
 │   │
 │   │ N
 │   │  i
 i = 1
"$

print_string_2d_unicode(e5);
"     6
    d
─────────── (h(u , v , w ))
  3   2         i   j   k
du  dv  dw
  i   j   k
"$

print_string_2d_unicode(e6b);
"           │
     1     │
───────────│
   1       │
─────── + 1│
f(u, v)    │
           │(u = 0), (v = 1)
"$

print_string_2d_unicode(e7);
"│  1  │
│─────│
│ n   │
│p    │
│ q   │
│  r  │
│   s │
│    0│
"$

block ([linel: 80], print_string_2d_unicode(e8a));
"┌                                         ┐
│ y   y   y   y   y   y   y   y   y   y   │
│  1   2   3   4   5   6   7   8   9   10 │
└                                         ┘
"$

block ([linel: 40], print_string_2d_unicode(e8a));
"         ┌    ┐         ┌    ┐
 Col 1 = │ y  │ Col 2 = │ y  │
         │  1 │         │  2 │
         └    ┘         └    ┘
         ┌    ┐         ┌    ┐
 Col 3 = │ y  │ Col 4 = │ y  │
         │  3 │         │  4 │
         └    ┘         └    ┘
         ┌    ┐         ┌    ┐
 Col 5 = │ y  │ Col 6 = │ y  │
         │  5 │         │  6 │
         └    ┘         └    ┘
         ┌    ┐         ┌    ┐
 Col 7 = │ y  │ Col 8 = │ y  │
         │  7 │         │  8 │
         └    ┘         └    ┘
         ┌    ┐          ┌     ┐
 Col 9 = │ y  │ Col 10 = │ y   │
         │  9 │          │  10 │
         └    ┘          └     ┘
"$

print_string_2d_unicode(e8b);
"┌     ┐
│ y   │
│  1  │
│     │
│ y   │
│  2  │
│     │
│ y   │
│  3  │
│     │
│ y   │
│  4  │
│     │
│ y   │
│  5  │
│     │
│ y   │
│  6  │
│     │
│ y   │
│  7  │
│     │
│ y   │
│  8  │
│     │
│ y   │
│  9  │
│     │
│ y   │
│  10 │
└     ┘
"$

block ([linel: 120], print_string_2d_unicode(e8c));
"┌                                                                                ┐
│    2                                                                           │
│   y     y  y    y  y    y  y    y  y    y  y    y  y    y  y    y  y    y  y   │
│    1     1  2    1  3    1  4    1  5    1  6    1  7    1  8    1  9    1  10 │
│                                                                                │
│            2                                                                   │
│ y  y      y     y  y    y  y    y  y    y  y    y  y    y  y    y  y    y  y   │
│  1  2      2     2  3    2  4    2  5    2  6    2  7    2  8    2  9    2  10 │
│                                                                                │
│                    2                                                           │
│ y  y    y  y      y     y  y    y  y    y  y    y  y    y  y    y  y    y  y   │
│  1  3    2  3      3     3  4    3  5    3  6    3  7    3  8    3  9    3  10 │
│                                                                                │
│                            2                                                   │
│ y  y    y  y    y  y      y     y  y    y  y    y  y    y  y    y  y    y  y   │
│  1  4    2  4    3  4      4     4  5    4  6    4  7    4  8    4  9    4  10 │
│                                                                                │
│                                    2                                           │
│ y  y    y  y    y  y    y  y      y     y  y    y  y    y  y    y  y    y  y   │
│  1  5    2  5    3  5    4  5      5     5  6    5  7    5  8    5  9    5  10 │
│                                                                                │
│                                            2                                   │
│ y  y    y  y    y  y    y  y    y  y      y     y  y    y  y    y  y    y  y   │
│  1  6    2  6    3  6    4  6    5  6      6     6  7    6  8    6  9    6  10 │
│                                                                                │
│                                                    2                           │
│ y  y    y  y    y  y    y  y    y  y    y  y      y     y  y    y  y    y  y   │
│  1  7    2  7    3  7    4  7    5  7    6  7      7     7  8    7  9    7  10 │
│                                                                                │
│                                                            2                   │
│ y  y    y  y    y  y    y  y    y  y    y  y    y  y      y     y  y    y  y   │
│  1  8    2  8    3  8    4  8    5  8    6  8    7  8      8     8  9    8  10 │
│                                                                                │
│                                                                    2           │
│ y  y    y  y    y  y    y  y    y  y    y  y    y  y    y  y      y     y  y   │
│  1  9    2  9    3  9    4  9    5  9    6  9    7  9    8  9      9     9  10 │
│                                                                                │
│                                                                           2    │
│ y  y    y  y    y  y    y  y    y  y    y  y    y  y    y  y    y  y     y     │
│  1  10   2  10   3  10   4  10   5  10   6  10   7  10   8  10   9  10    10   │
└                                                                                ┘
"$

block ([linel: 60], print_string_2d_unicode(e8c));
"         ┌        ┐         ┌        ┐         ┌        ┐
         │    2   │         │ y  y   │         │ y  y   │
         │   y    │         │  1  2  │         │  1  3  │
         │    1   │         │        │         │        │
         │        │         │    2   │         │ y  y   │
         │ y  y   │         │   y    │         │  2  3  │
         │  1  2  │         │    2   │         │        │
         │        │         │        │         │    2   │
         │ y  y   │         │ y  y   │         │   y    │
         │  1  3  │         │  2  3  │         │    3   │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  1  4  │         │  2  4  │         │  3  4  │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
 Col 1 = │  1  5  │ Col 2 = │  2  5  │ Col 3 = │  3  5  │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  1  6  │         │  2  6  │         │  3  6  │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  1  7  │         │  2  7  │         │  3  7  │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  1  8  │         │  2  8  │         │  3  8  │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  1  9  │         │  2  9  │         │  3  9  │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  1  10 │         │  2  10 │         │  3  10 │
         └        ┘         └        ┘         └        ┘
         ┌        ┐         ┌        ┐         ┌        ┐
         │ y  y   │         │ y  y   │         │ y  y   │
         │  1  4  │         │  1  5  │         │  1  6  │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  2  4  │         │  2  5  │         │  2  6  │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  3  4  │         │  3  5  │         │  3  6  │
         │        │         │        │         │        │
         │    2   │         │ y  y   │         │ y  y   │
         │   y    │         │  4  5  │         │  4  6  │
         │    4   │         │        │         │        │
         │        │         │    2   │         │ y  y   │
         │ y  y   │         │   y    │         │  5  6  │
 Col 4 = │  4  5  │ Col 5 = │    5   │ Col 6 = │        │
         │        │         │        │         │    2   │
         │ y  y   │         │ y  y   │         │   y    │
         │  4  6  │         │  5  6  │         │    6   │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  4  7  │         │  5  7  │         │  6  7  │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  4  8  │         │  5  8  │         │  6  8  │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  4  9  │         │  5  9  │         │  6  9  │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  4  10 │         │  5  10 │         │  6  10 │
         └        ┘         └        ┘         └        ┘
         ┌        ┐         ┌        ┐         ┌        ┐
         │ y  y   │         │ y  y   │         │ y  y   │
         │  1  7  │         │  1  8  │         │  1  9  │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  2  7  │         │  2  8  │         │  2  9  │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  3  7  │         │  3  8  │         │  3  9  │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  4  7  │         │  4  8  │         │  4  9  │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  5  7  │         │  5  8  │         │  5  9  │
 Col 7 = │        │ Col 8 = │        │ Col 9 = │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  6  7  │         │  6  8  │         │  6  9  │
         │        │         │        │         │        │
         │    2   │         │ y  y   │         │ y  y   │
         │   y    │         │  7  8  │         │  7  9  │
         │    7   │         │        │         │        │
         │        │         │    2   │         │ y  y   │
         │ y  y   │         │   y    │         │  8  9  │
         │  7  8  │         │    8   │         │        │
         │        │         │        │         │    2   │
         │ y  y   │         │ y  y   │         │   y    │
         │  7  9  │         │  8  9  │         │    9   │
         │        │         │        │         │        │
         │ y  y   │         │ y  y   │         │ y  y   │
         │  7  10 │         │  8  10 │         │  9  10 │
         └        ┘         └        ┘         └        ┘
          ┌        ┐
          │ y  y   │
          │  1  10 │
          │        │
          │ y  y   │
          │  2  10 │
          │        │
          │ y  y   │
          │  3  10 │
          │        │
          │ y  y   │
          │  4  10 │
          │        │
          │ y  y   │
          │  5  10 │
 Col 10 = │        │
          │ y  y   │
          │  6  10 │
          │        │
          │ y  y   │
          │  7  10 │
          │        │
          │ y  y   │
          │  8  10 │
          │        │
          │ y  y   │
          │  9  10 │
          │        │
          │   2    │
          │  y     │
          │   10   │
          └        ┘
"$

print_string_2d_unicode(e9a);
"╔═╗
║u║
╚═╝
"$

print_string_2d_unicode(e9b);
"╔══╗
║u ║
║ 1║
╚══╝
"$

print_string_2d_unicode(e9c);
"╔══╗
║ n║
║u ║
╚══╝
"$

print_string_2d_unicode(e9d);
"╔══════╗
║    1 ║
║1 - ──║
║     n║
║    u ║
║     1║
╚══════╝
"$

print_string_2d_unicode(e10a);
"foo
║u║
╚═╝
"$

print_string_2d_unicode(e10b);
"bar╗
║u ║
║ 1║
╚══╝
"$

print_string_2d_unicode(e10c);
"baz╗
║ n║
║u ║
╚══╝
"$

print_string_2d_unicode(e10d);
"quux═══╗
║    1 ║
║1 - ──║
║     n║
║    u ║
║     1║
╚══════╝
"$

print_string_2d_unicode(e11);
" y
──── + x
   2
╔═╗
║z║
╚═╝
"$

print_string_2d_unicode(e12);
"   3         2      2       3
- y  + 3 x  y  - 3 x  y  + x  - 1
   l      k  l      k  l    k
─────────────────────────────────
                  456
        1234 - ──────────
                        3
               (a  - b )
                 i    j
"$

(ee1:[e1a,e1b,e2,e3,e4],print_string_2d_unicode(ee1));
"             1           m                     inf
 ⌠          ⌠           ____      ____       ─┬───┬─
 ⎮          ⎮           ╲         ╲       2   │   │
[⎮ f(u) du, ⎮  f(u) du,  ⟩    g ,  ⟩     v ,  │   │ N ]
 ⎮          ⎮           ╱      k  ╱       k   │   │  i
 ⌡          ⌡           ‾‾‾‾      ‾‾‾‾        i = 1
             0          k = 1     k in L
";

print_string_2d_unicode(matrix(ee1));
"┌                                                       ┐
│             1           m                     inf     │
│ ⌠          ⌠           ____      ____       ─┬───┬─   │
│ ⎮          ⎮           ╲         ╲       2   │   │    │
│ ⎮ f(u) du  ⎮  f(u) du   ⟩    g    ⟩     v    │   │ N  │
│ ⎮          ⎮           ╱      k  ╱       k   │   │  i │
│ ⌡          ⌡           ‾‾‾‾      ‾‾‾‾        i = 1    │
│             0          k = 1     k in L               │
└                                                       ┘
";

print_string_2d_unicode(transpose(matrix(ee1)));
"┌             ┐
│  ⌠          │
│  ⎮          │
│  ⎮ f(u) du  │
│  ⎮          │
│  ⌡          │
│             │
│   1         │
│  ⌠          │
│  ⎮          │
│  ⎮  f(u) du │
│  ⎮          │
│  ⌡          │
│   0         │
│             │
│    m        │
│   ____      │
│   ╲         │
│    ⟩    g   │
│   ╱      k  │
│   ‾‾‾‾      │
│   k = 1     │
│             │
│             │
│  ____       │
│  ╲       2  │
│   ⟩     v   │
│  ╱       k  │
│  ‾‾‾‾       │
│  k in L     │
│             │
│    inf      │
│  ─┬───┬─    │
│   │   │     │
│   │   │ N   │
│   │   │  i  │
│   i = 1     │
└             ┘
";

(ee2:[e5,e6b,e7,e8a,e8b],print_string_2d_unicode(ee2));
"      6                                  │
     d                             1     │                  │  1  │
[─────────── (h(u , v , w )), ───────────│                , │─────│, 
   3   2         i   j   k       1       │                  │ n   │
 du  dv  dw                   ─────── + 1│                  │p    │
   i   j   k                  f(u, v)    │                  │ q   │
                                         │(u = 0), (v = 1)  │  r  │
                                                            │   s │
                                                            │    0│
                                                                       ┌     ┐
                                                                       │ y   │
                                                                       │  1  │
                                                                       │     │
                                                                       │ y   │
                                                                       │  2  │
                                                                       │     │
                                                                       │ y   │
                                                                       │  3  │
                                                                       │     │
                                                                       │ y   │
                                                                       │  4  │
                                                                       │     │
                                                                       │ y   │
                          ┌                                         ┐  │  5  │
                          │ y   y   y   y   y   y   y   y   y   y   │, │     │]
                          │  1   2   3   4   5   6   7   8   9   10 │  │ y   │
                          └                                         ┘  │  6  │
                                                                       │     │
                                                                       │ y   │
                                                                       │  7  │
                                                                       │     │
                                                                       │ y   │
                                                                       │  8  │
                                                                       │     │
                                                                       │ y   │
                                                                       │  9  │
                                                                       │     │
                                                                       │ y   │
                                                                       │  10 │
                                                                       └     ┘
";

print_string_2d_unicode(matrix(ee2));
"         ┌                             ┐
         │      6                      │
         │     d                       │
         │ ─────────── (h(u , v , w )) │
 Col 1 = │   3   2         i   j   k   │
         │ du  dv  dw                  │
         │   i   j   k                 │
         │                             │
         │                             │
         └                             ┘
         ┌                              ┐         ┌         ┐
         │            │                 │         │ │  1  │ │
         │      1     │                 │         │ │─────│ │
         │ ───────────│                 │         │ │ n   │ │
 Col 2 = │    1       │                 │ Col 3 = │ │p    │ │
         │ ─────── + 1│                 │         │ │ q   │ │
         │ f(u, v)    │                 │         │ │  r  │ │
         │            │(u = 0), (v = 1) │         │ │   s │ │
         └                              ┘         │ │    0│ │
                                                  └         ┘
                                                                 ┌         ┐
                                                                 │ ┌     ┐ │
                                                                 │ │ y   │ │
                                                                 │ │  1  │ │
                                                                 │ │     │ │
                                                                 │ │ y   │ │
                                                                 │ │  2  │ │
                                                                 │ │     │ │
                                                                 │ │ y   │ │
                                                                 │ │  3  │ │
                                                                 │ │     │ │
                                                                 │ │ y   │ │
                                                                 │ │  4  │ │
                                                                 │ │     │ │
         ┌                                             ┐         │ │ y   │ │
         │ ┌                                         ┐ │         │ │  5  │ │
 Col 4 = │ │ y   y   y   y   y   y   y   y   y   y   │ │ Col 5 = │ │     │ │
         │ │  1   2   3   4   5   6   7   8   9   10 │ │         │ │ y   │ │
         │ └                                         ┘ │         │ │  6  │ │
         └                                             ┘         │ │     │ │
                                                                 │ │ y   │ │
                                                                 │ │  7  │ │
                                                                 │ │     │ │
                                                                 │ │ y   │ │
                                                                 │ │  8  │ │
                                                                 │ │     │ │
                                                                 │ │ y   │ │
                                                                 │ │  9  │ │
                                                                 │ │     │ │
                                                                 │ │ y   │ │
                                                                 │ │  10 │ │
                                                                 │ └     ┘ │
                                                                 └         ┘
";

print_string_2d_unicode(transpose(matrix(ee2)));
"┌                                             ┐
│              6                              │
│             d                               │
│         ─────────── (h(u , v , w ))         │
│           3   2         i   j   k           │
│         du  dv  dw                          │
│           i   j   k                         │
│                                             │
│                                             │
│                                             │
│                   │                         │
│             1     │                         │
│        ───────────│                         │
│           1       │                         │
│        ─────── + 1│                         │
│        f(u, v)    │                         │
│                   │(u = 0), (v = 1)         │
│                                             │
│                   │  1  │                   │
│                   │─────│                   │
│                   │ n   │                   │
│                   │p    │                   │
│                   │ q   │                   │
│                   │  r  │                   │
│                   │   s │                   │
│                   │    0│                   │
│                                             │
│ ┌                                         ┐ │
│ │ y   y   y   y   y   y   y   y   y   y   │ │
│ │  1   2   3   4   5   6   7   8   9   10 │ │
│ └                                         ┘ │
│                                             │
│                   ┌     ┐                   │
│                   │ y   │                   │
│                   │  1  │                   │
│                   │     │                   │
│                   │ y   │                   │
│                   │  2  │                   │
│                   │     │                   │
│                   │ y   │                   │
│                   │  3  │                   │
│                   │     │                   │
│                   │ y   │                   │
│                   │  4  │                   │
│                   │     │                   │
│                   │ y   │                   │
│                   │  5  │                   │
│                   │     │                   │
│                   │ y   │                   │
│                   │  6  │                   │
│                   │     │                   │
│                   │ y   │                   │
│                   │  7  │                   │
│                   │     │                   │
│                   │ y   │                   │
│                   │  8  │                   │
│                   │     │                   │
│                   │ y   │                   │
│                   │  9  │                   │
│                   │     │                   │
│                   │ y   │                   │
│                   │  10 │                   │
│                   └     ┘                   │
└                                             ┘
";

(ee3:[e8c,e9a,e9b,e9c,e9d],print_string_2d_unicode(ee3));
"          2
[matrix([y , y  y , y  y , y  y , y  y , y  y , y  y , y  y , y  y , y  y  ], 
          1   1  2   1  3   1  4   1  5   1  6   1  7   1  8   1  9   1  10
         2
[y  y , y , y  y , y  y , y  y , y  y , y  y , y  y , y  y , y  y  ], 
  1  2   2   2  3   2  4   2  5   2  6   2  7   2  8   2  9   2  10
                2
[y  y , y  y , y , y  y , y  y , y  y , y  y , y  y , y  y , y  y  ], 
  1  3   2  3   3   3  4   3  5   3  6   3  7   3  8   3  9   3  10
                       2
[y  y , y  y , y  y , y , y  y , y  y , y  y , y  y , y  y , y  y  ], 
  1  4   2  4   3  4   4   4  5   4  6   4  7   4  8   4  9   4  10
                              2
[y  y , y  y , y  y , y  y , y , y  y , y  y , y  y , y  y , y  y  ], 
  1  5   2  5   3  5   4  5   5   5  6   5  7   5  8   5  9   5  10
                                     2
[y  y , y  y , y  y , y  y , y  y , y , y  y , y  y , y  y , y  y  ], 
  1  6   2  6   3  6   4  6   5  6   6   6  7   6  8   6  9   6  10
                                            2
[y  y , y  y , y  y , y  y , y  y , y  y , y , y  y , y  y , y  y  ], 
  1  7   2  7   3  7   4  7   5  7   6  7   7   7  8   7  9   7  10
                                                   2
[y  y , y  y , y  y , y  y , y  y , y  y , y  y , y , y  y , y  y  ], 
  1  8   2  8   3  8   4  8   5  8   6  8   7  8   8   8  9   8  10
                                                          2
[y  y , y  y , y  y , y  y , y  y , y  y , y  y , y  y , y , y  y  ], 
  1  9   2  9   3  9   4  9   5  9   6  9   7  9   8  9   9   9  10
[y  y  , y  y  , y  y  , y  y  , y  y  , y  y  , y  y  , y  y  , y  y  , 
  1  10   2  10   3  10   4  10   5  10   6  10   7  10   8  10   9  10
                  ╔══╗  ╔══════╗
 2     ╔═╗  ╔══╗  ║ n║  ║    1 ║
y  ]), ║u║, ║u ║, ║u ║, ║1 - ──║]
 10    ╚═╝  ║ 1║  ╚══╝  ║     n║
            ╚══╝        ║    u ║
                        ║     1║
                        ╚══════╝
";

print_string_2d_unicode(matrix(ee3));
"                 2
matrix([matrix([y , y  y , y  y , y  y , y  y , y  y , y  y , y  y , y  y , 
                 1   1  2   1  3   1  4   1  5   1  6   1  7   1  8   1  9
                  2
y  y  ], [y  y , y , y  y , y  y , y  y , y  y , y  y , y  y , y  y , y  y  ], 
 1  10     1  2   2   2  3   2  4   2  5   2  6   2  7   2  8   2  9   2  10
                2
[y  y , y  y , y , y  y , y  y , y  y , y  y , y  y , y  y , y  y  ], 
  1  3   2  3   3   3  4   3  5   3  6   3  7   3  8   3  9   3  10
                       2
[y  y , y  y , y  y , y , y  y , y  y , y  y , y  y , y  y , y  y  ], 
  1  4   2  4   3  4   4   4  5   4  6   4  7   4  8   4  9   4  10
                              2
[y  y , y  y , y  y , y  y , y , y  y , y  y , y  y , y  y , y  y  ], 
  1  5   2  5   3  5   4  5   5   5  6   5  7   5  8   5  9   5  10
                                     2
[y  y , y  y , y  y , y  y , y  y , y , y  y , y  y , y  y , y  y  ], 
  1  6   2  6   3  6   4  6   5  6   6   6  7   6  8   6  9   6  10
                                            2
[y  y , y  y , y  y , y  y , y  y , y  y , y , y  y , y  y , y  y  ], 
  1  7   2  7   3  7   4  7   5  7   6  7   7   7  8   7  9   7  10
                                                   2
[y  y , y  y , y  y , y  y , y  y , y  y , y  y , y , y  y , y  y  ], 
  1  8   2  8   3  8   4  8   5  8   6  8   7  8   8   8  9   8  10
                                                          2
[y  y , y  y , y  y , y  y , y  y , y  y , y  y , y  y , y , y  y  ], 
  1  9   2  9   3  9   4  9   5  9   6  9   7  9   8  9   9   9  10
[y  y  , y  y  , y  y  , y  y  , y  y  , y  y  , y  y  , y  y  , y  y  , 
  1  10   2  10   3  10   4  10   5  10   6  10   7  10   8  10   9  10
                  ╔══╗  ╔══════╗
 2     ╔═╗  ╔══╗  ║ n║  ║    1 ║
y  ]), ║u║, ║u ║, ║u ║, ║1 - ──║])
 10    ╚═╝  ║ 1║  ╚══╝  ║     n║
            ╚══╝        ║    u ║
                        ║     1║
                        ╚══════╝
";

print_string_2d_unicode(transpose(matrix(ee3)));
"                 2
matrix([matrix([y , y  y , y  y , y  y , y  y , y  y , y  y , y  y , y  y , 
                 1   1  2   1  3   1  4   1  5   1  6   1  7   1  8   1  9
                  2
y  y  ], [y  y , y , y  y , y  y , y  y , y  y , y  y , y  y , y  y , y  y  ], 
 1  10     1  2   2   2  3   2  4   2  5   2  6   2  7   2  8   2  9   2  10
                2
[y  y , y  y , y , y  y , y  y , y  y , y  y , y  y , y  y , y  y  ], 
  1  3   2  3   3   3  4   3  5   3  6   3  7   3  8   3  9   3  10
                       2
[y  y , y  y , y  y , y , y  y , y  y , y  y , y  y , y  y , y  y  ], 
  1  4   2  4   3  4   4   4  5   4  6   4  7   4  8   4  9   4  10
                              2
[y  y , y  y , y  y , y  y , y , y  y , y  y , y  y , y  y , y  y  ], 
  1  5   2  5   3  5   4  5   5   5  6   5  7   5  8   5  9   5  10
                                     2
[y  y , y  y , y  y , y  y , y  y , y , y  y , y  y , y  y , y  y  ], 
  1  6   2  6   3  6   4  6   5  6   6   6  7   6  8   6  9   6  10
                                            2
[y  y , y  y , y  y , y  y , y  y , y  y , y , y  y , y  y , y  y  ], 
  1  7   2  7   3  7   4  7   5  7   6  7   7   7  8   7  9   7  10
                                                   2
[y  y , y  y , y  y , y  y , y  y , y  y , y  y , y , y  y , y  y  ], 
  1  8   2  8   3  8   4  8   5  8   6  8   7  8   8   8  9   8  10
                                                          2
[y  y , y  y , y  y , y  y , y  y , y  y , y  y , y  y , y , y  y  ], 
  1  9   2  9   3  9   4  9   5  9   6  9   7  9   8  9   9   9  10
[y  y  , y  y  , y  y  , y  y  , y  y  , y  y  , y  y  , y  y  , y  y  , 
  1  10   2  10   3  10   4  10   5  10   6  10   7  10   8  10   9  10
                        ╔══╗    ╔══════╗
 2       ╔═╗    ╔══╗    ║ n║    ║    1 ║
y  ])], [║u║], [║u ║], [║u ║], [║1 - ──║])
 10      ╚═╝    ║ 1║    ╚══╝    ║     n║
                ╚══╝            ║    u ║
                                ║     1║
                                ╚══════╝
";

(ee4:[e10a,e10b,e10c,e10d,e11],print_string_2d_unicode(ee4));
"            baz╗  quux═══╗
 foo  bar╗  ║ n║  ║    1 ║   y
[║u║, ║u ║, ║u ║, ║1 - ──║, ──── + x]
 ╚═╝  ║ 1║  ╚══╝  ║     n║     2
      ╚══╝        ║    u ║  ╔═╗
                  ║     1║  ║z║
                  ╚══════╝  ╚═╝
";

print_string_2d_unicode(matrix(ee4));
"┌                                     ┐
│            baz╗  quux═══╗           │
│ foo  bar╗  ║ n║  ║    1 ║   y       │
│ ║u║  ║u ║  ║u ║  ║1 - ──║  ──── + x │
│ ╚═╝  ║ 1║  ╚══╝  ║     n║     2     │
│      ╚══╝        ║    u ║  ╔═╗      │
│                  ║     1║  ║z║      │
│                  ╚══════╝  ╚═╝      │
└                                     ┘
";

print_string_2d_unicode(transpose(matrix(ee4)));
"┌          ┐
│   foo    │
│   ║u║    │
│   ╚═╝    │
│          │
│   bar╗   │
│   ║u ║   │
│   ║ 1║   │
│   ╚══╝   │
│          │
│   baz╗   │
│   ║ n║   │
│   ║u ║   │
│   ╚══╝   │
│          │
│ quux═══╗ │
│ ║    1 ║ │
│ ║1 - ──║ │
│ ║     n║ │
│ ║    u ║ │
│ ║     1║ │
│ ╚══════╝ │
│          │
│  y       │
│ ──── + x │
│    2     │
│ ╔═╗      │
│ ║z║      │
│ ╚═╝      │
└          ┘
";

(ee5:[e12,FOO,BAR,BAZ,e6a],print_string_2d_unicode(ee5));
"    3         2      2       3
 - y  + 3 x  y  - 3 x  y  + x  - 1
    l      k  l      k  l    k                      │
[─────────────────────────────────, FOO, BAR, BAZ, u│     ]
                   456                              │u = 0
         1234 - ──────────
                         3
                (a  - b )
                  i    j
";

print_string_2d_unicode(matrix(ee5));
"┌                                                           ┐
│    3         2      2       3                             │
│ - y  + 3 x  y  - 3 x  y  + x  - 1                         │
│    l      k  l      k  l    k                      │      │
│ ─────────────────────────────────  FOO  BAR  BAZ  u│      │
│                   456                              │u = 0 │
│         1234 - ──────────                                 │
│                         3                                 │
│                (a  - b )                                  │
│                  i    j                                   │
└                                                           ┘
";

print_string_2d_unicode(transpose(matrix(ee5)));
"┌                                   ┐
│    3         2      2       3     │
│ - y  + 3 x  y  - 3 x  y  + x  - 1 │
│    l      k  l      k  l    k     │
│ ───────────────────────────────── │
│                   456             │
│         1234 - ──────────         │
│                         3         │
│                (a  - b )          │
│                  i    j           │
│                                   │
│                FOO                │
│                                   │
│                BAR                │
│                                   │
│                BAZ                │
│                                   │
│               │                   │
│              u│                   │
│               │u = 0              │
└                                   ┘
";

block ([linel: 140], print_string_2d_unicode (matrix (ee1, ee2, ee4, ee5)));
"┌                                                                                                                                   ┐
│                                              1                    m                                                       inf     │
│             ⌠                               ⌠                    ____                       ____                        ─┬───┬─   │
│             ⎮                               ⎮                    ╲                          ╲       2                    │   │    │
│             ⎮ f(u) du                       ⎮  f(u) du            ⟩    g                     ⟩     v                     │   │ N  │
│             ⎮                               ⎮                    ╱      k                   ╱       k                    │   │  i │
│             ⌡                               ⌡                    ‾‾‾‾                       ‾‾‾‾                         i = 1    │
│                                              0                   k = 1                      k in L                                │
│                                                                                                                                   │
│                                                                                                                         ┌     ┐   │
│                                                                                                                         │ y   │   │
│                                                                                                                         │  1  │   │
│                                                                                                                         │     │   │
│                                                                                                                         │ y   │   │
│                                                                                                                         │  2  │   │
│                                                                                                                         │     │   │
│                                                                                                                         │ y   │   │
│                                                                                                                         │  3  │   │
│                                                                                                                         │     │   │
│                                                                                                                         │ y   │   │
│                                                                                                                         │  4  │   │
│                                                                                                                         │     │   │
│         6                                     │                                                                         │ y   │   │
│        d                                1     │                  │  1  │   ┌                                         ┐  │  5  │   │
│    ─────────── (h(u , v , w ))     ───────────│                  │─────│   │ y   y   y   y   y   y   y   y   y   y   │  │     │   │
│      3   2         i   j   k          1       │                  │ n   │   │  1   2   3   4   5   6   7   8   9   10 │  │ y   │   │
│    du  dv  dw                      ─────── + 1│                  │p    │   └                                         ┘  │  6  │   │
│      i   j   k                     f(u, v)    │                  │ q   │                                                │     │   │
│                                               │(u = 0), (v = 1)  │  r  │                                                │ y   │   │
│                                                                  │   s │                                                │  7  │   │
│                                                                  │    0│                                                │     │   │
│                                                                                                                         │ y   │   │
│                                                                                                                         │  8  │   │
│                                                                                                                         │     │   │
│                                                                                                                         │ y   │   │
│                                                                                                                         │  9  │   │
│                                                                                                                         │     │   │
│                                                                                                                         │ y   │   │
│                                                                                                                         │  10 │   │
│                                                                                                                         └     ┘   │
│                                                                                                                                   │
│                                                                    baz╗                     quux═══╗                              │
│                foo                             bar╗                ║ n║                     ║    1 ║                     y        │
│                ║u║                             ║u ║                ║u ║                     ║1 - ──║                    ──── + x  │
│                ╚═╝                             ║ 1║                ╚══╝                     ║     n║                       2      │
│                                                ╚══╝                                         ║    u ║                    ╔═╗       │
│                                                                                             ║     1║                    ║z║       │
│                                                                                             ╚══════╝                    ╚═╝       │
│                                                                                                                                   │
│    3         2      2       3                                                                                                     │
│ - y  + 3 x  y  - 3 x  y  + x  - 1                                                                                                 │
│    l      k  l      k  l    k                                                                                            │        │
│ ─────────────────────────────────              FOO                 BAR                         BAZ                      u│        │
│                   456                                                                                                    │u = 0   │
│         1234 - ──────────                                                                                                         │
│                         3                                                                                                         │
│                (a  - b )                                                                                                          │
│                  i    j                                                                                                           │
└                                                                                                                                   ┘
";
