(kill(all), 0);
0;

/* (Z/pZ)* p prime */
p : 2^127-1;
170141183460469231731687303715884105727;

fs : ifactors(p - 1);
[[2, 1], [3, 3], [7, 2], [19, 1], [43, 1], [73, 1], [127, 1], [337, 1], [5419, 1], [92737, 1], [649657, 1], [77158673929, 1]];

g : zn_primroot(p, fs);
43;

zn_primroot_p(power_mod(g, 7, p), p, fs);
false;

zn_primroot_p(power_mod(g, 11, p), p, fs);
true;

is(zn_order(g, p, fs) = totient(p));
true;

is(zn_order(power_mod(g, 7, p), p, fs) = zn_order(g, p, fs));
false;

is(zn_order(power_mod(g, 11, p), p, fs) = zn_order(g, p, fs));
true;

a : power_mod(g, 1234567890, p);
151915201611216996495932583752378710518;

zn_log(a, g, p, fs);
1234567890;

/* (Z/nZ)* n composite */
n : 22;
22;

g : zn_primroot(n);
7;

zn_primroot_p(power_mod(g, 2, n), n);
false;

zn_primroot_p(power_mod(g, 3, n), n);
true;

zn_order(power_mod(g, 2, n), n);
5;

zn_order(g, n);
10;

a : power_mod(g, 8, n);
9;

zn_log(a, g, n);
8;

/* CRT */
mods : [1009, 1013, 1019];
[1009, 1013, 1019];

x : 374599943;
374599943;

rems : map(lambda([z], mod(x, z)), mods);
[621, 647, 258];

chinese(rems, mods);
374599943;

(remvalue(p,fs,g,a,n,mods,x,rems), 0);
0;
