/*************** -*- Mode: MACSYMA; Package: MAXIMA -*-  ******************/
/***************************************************************************
***                                                                    *****
***     Copyright (c) 1984 by William Schelter,University of Texas     *****
***     All rights reserved                                            *****
***************************************************************************/


/* -*- Mode: MACSYMA -*- */
/* BATCH("me:test6a.mac");
It asked is a pos answred yes
   and is i+1 zero or nonzero and I answered nonzero 
  so should add ASSUME (A>0,NOT(EQUAL(I+1,0)))  */
kill(all);
done;
RISCH(X^2*ERF(X),X);
(%PI*X^3*ERF(X)+(SQRT(%PI)*X^2+SQRT(%PI))*%E^-X^2)/(3*%PI);
EV(DIFF(%,X),RATSIMP);
X^2*ERF(X);
ASSUME(A>0);
[a>0];
'INTEGRATE(%E^(SQRT(A)*SQRT(Y)),Y,0,4);
'INTEGRATE(%E^(SQRT(A)*SQRT(Y)),Y,0,4);
CHANGEVAR(%,Y-Z^2/A,Z,Y);
/* on lispm -2*('INTEGRATE(Z*%E^ABS(Z),Z,-2*SQRT(A),0))/A; */
- 'INTEGRATE(2*Z*%E^ABS(Z)/A,Z,-2*SQRT(A),0);
ASSUME(P > 0);
[P > 0]$
T^(1/2)*%E^-(A*T/4)*%E^-(P*T);
SQRT(T)*%E^(-P*T-A*T/4);
/* SPECINT(%,T); not available in distribution
SQRT(%PI)/(2*(P+A/4)^(3/2)); */
assume(T > 0);
[T > 0]$
T^(1/2)*%J[1](2*A^(1/2)*T^(1/2))*%E^-(P*T);
%J[1](2*SQRT(A)*SQRT(T))*SQRT(T)*%E^-(P*T);
/* SPECINT(%,T); not available
SQRT(A)*%E^-(A/P)/P^2;*/
FORGET(P > 0,A > 0)$
[P > 0,A > 0]$
X+Y/Z^2;
Y/Z^2+X;
PART(%,1,2,2);
2;
REMVALUE(X);
[FALSE];
'INTEGRATE(F(X),X,A,B)+X;
'INTEGRATE(F(X),X,A,B)+X;
PART(%,1,1);
F(X);
X^2+2*X = Y^2;
X^2+2*X = Y^2;
EXP:%+1;
X^2+2*X+1 = Y^2+1;
LHS(%);
X^2+2*X+1;
PART(EXP,2);
Y^2+1;
PART(%,1);
Y^2;
27*Y^3+54*X*Y^2+36*X^2*Y+Y+8*X^3+X+1;
27*Y^3+54*X*Y^2+36*X^2*Y+Y+8*X^3+X+1;
PART(%,2,[1,3]);
54*Y^2;
SQRT(PIECE/54);
ABS(Y);
X+Y+W*Z;
W*Z+Y+X;
INPART(%,3,2);
Z;
'LIMIT(F(X)^G(X+1),X,0,MINUS);
'LIMIT(F(X)^G(X+1),X,0,MINUS);
INPART(%,1,2);
G(X+1);
'LIMIT(F(X)^G(X+1),X,0,MINUS);
'LIMIT(F(X)^G(X+1),X,0,MINUS);
IS(INPART(%,0) = NOUNIFY(LIMIT));
TRUE;
DPART(X+Y/Z^2,1,2,1);
Y/?MBOX(Z)^2+X;
EXP:EXPAND((B+A)^4);
B^4+4*A*B^3+6*A^2*B^2+4*A^3*B+A^4;
(B+A)^2*(Y+X)^2;
(B+A)^2*(Y+X)^2;
EXPAND(%);
B^2*Y^2+2*A*B*Y^2+A^2*Y^2+2*B^2*X*Y+4*A*B*X*Y+2*A^2*X*Y+B^2*X^2+2*A*B*X^2+A^2*X^2;
EXP:EXP/%;
(B^4+4*A*B^3+6*A^2*B^2+4*A^3*B+A^4)/(B^2*Y^2+2*A*B*Y^2+A^2*Y^2+2*B^2*X*Y+4*A*B*X*Y+2*A^2*X*Y+B^2*X^2+2*A*B*X^2+A^2*X^2);
FACTOR(%);
(B+A)^2/(Y+X)^2;
DPART(EXP,2,4);
(B^4+4*A*B^3+6*A^2*B^2+4*A^3*B+A^4)/(B^2*Y^2+2*A*B*Y^2+A^2*Y^2+?MBOX(2*B^2*X*Y)+4*A*B*X*Y+2*A^2*X*Y+B^2*X^2+2*A*B*X^2+A^2*X^2);
PART(EXP,2,4);
2*B^2*X*Y;
SUBST(A,X+Y,X+(X+Y)^2+Y);
Y+X+A^2;
SUBST(-%I,%I,A+B*%I);
A-%I*B;
SUBST(X,Y,X+Y);
2*X;
SUBST(X = 0,DIFF(SIN(X),X));
1;
ERRCATCH(EV(DIFF(SIN(X),X),X = 0));
[];
ASSUME(NOT(EQUAL(I,-1)));
[NOT EQUAL(I,-1)]$
EV(INTEGRATE(X^I,X),I = -1);
LOG(X);
ERRCATCH(SUBST(-1,I,INTEGRATE(X^I,X)));
[];
MATRIX([A,B],[C,D]);
MATRIX([A,B],[C,D]);
SUBST("[",MATRIX,%);
[[A,B],[C,D]];
RATSUBST(A,X*Y^2,X^4*Y^8+X^4*Y^3);
A*X^3*Y+A^4;
1+COS(X)+COS(X)^2+COS(X)^3+COS(X)^4;
COS(X)^4+COS(X)^3+COS(X)^2+COS(X)+1;
RATSUBST(1-SIN(X)^2,COS(X)^2,%);
SIN(X)^4-3*SIN(X)^2+COS(X)*(2-SIN(X)^2)+3;
RATSUBST(1-COS(X)^2,SIN(X)^2,SIN(X)^4);
COS(X)^4-2*COS(X)^2+1;
