/* This file contains tests added since April 2002 */

kill(all);
done$

/* apropos function added 7 April 2002 */
apropos('TR_OPTIMIZE_MAX_LOOP);
[TR_OPTIMIZE_MAX_LOOP]$

/* Test introduced 7 April 2002. Bug fix incorporated 9 June 2002 */
integrate(3^log(x),x);
3^((1/LOG(3)+1)*LOG(x))/((1/LOG(3)+1)*LOG(3))$

/* Wester[1995] Problem 84 - Known failure - 7 April 2002 */
integrate(sqrt(x+1/x-2),x,0,1);
4/3$

/* second thru tenth code added 9 June 2002 */
l : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]$
FIRST(l);
1$ 
SECOND(l);
2$
THIRD(l);
3$
FOURTH(l);
4$
FIFTH(l);
5$
SIXTH(l);
6$
SEVENTH(l);
7$
EIGHTH(l);
8$
NINTH(l);
9$
TENTH(l);
10$
