kill(allbut(props));
done;
/* Tests of confluent hypergeometric function */

/* See A&S 13.6 */
/* Bessel functions */

assume(not(equal(z,0)));
[not equal(z,0)]$

/* A&S 13.6.1 */
hgfred([v+1/2],[2*v+1],2*%i*z);
4^(v/2)*bessel_j(v,z)*gamma(v+1)*exp(%i*z)/z^v$

/* A&S 13.6.3 */
hgfred([v+1/2],[2*v+1],2*z);
4^(v/2)*bessel_i(v,z)*gamma(v+1)*exp(z)/z^v$

/* A&S 13.6.4 */
expand(hgfred([n+1],[2*n+2],2*%i*z));
4^(n/2+1/4)*bessel_j(n+1/2,z)*gamma(n+3/2)*z^(-n-1/2)*%e^(%i*z)$

/* A&S 13.6.5 */
expand(hgfred([-n],[-2*n],2*%i*z));
bessel_j(-n-1/2,z)*gamma(1/2-n)*4^(-n/2-1/4)*z^(n+1/2)*%e^(%i*z)$

/* A&S 13.6.6 */
hgfred([n+1],[2*n+2],2*z);
bessel_i(n+1/2,z)*gamma(n+3/2)*z^(-n-1/2)*%e^z/4^((-n-1/2)/2)$

/* A&S 13.6.10 */
hgfred([a],[a+1],-z);
a*z^(-a)*%gammagreek(a,z)$

/* A&S 13.6.12 */
hgfred([a],[a],z);
exp(z)$

/* A&S 13.6.13 */
besselexpand:true;
true$

expand(hgfred([1],[2],-2*%i*z));
exp(-%i*z)*sin(z)/z$

/* A&S 13.6.14 */
expand(hgfred([1],[2],2*z));
exp(z)*sinh(z)/z$

/* A&S 13.6.17 
 * Note that this formula is in terms of He but we want just H.  
 * A&S 22.5.18 gives the relationship between He and H:
 *
 * He(n,x) = 2^(-n/2)*H(n,x/sqrt(2))
 */
hgfred([-4],[1/2],z^2/2);
hermite(8,z/sqrt(2))/1680$

/* A&S 13.6.18 */
hgfred([-4],[3/2],z^2/2);
sqrt(2)*hermite(9,z/sqrt(2))/30240/z$

/* A&S 13.6.19 */
ratsimp(hgfred([1/2],[3/2],-z^2));
sqrt(%pi)/2/abs(z)*erf(abs(z))$

/* A&S 7.1.21 */
ratsimp(hgfred([1],[3/2],z^2));
sqrt(%pi)*exp(z^2)*erf(abs(z))/2/abs(z)$

/* Hypergeometric function 2F1 tests 
*
* See A&S 15.1
*
*/
/* A&S 15.1.3 */
hgfred([1,1],[2],z);
-log(1-z)/z;

/* A&S 15.1.4 */
hgfred([1/2,1], [3/2], z^2);
log((1+z)/(1-z))/(2*z)$

/* A&S 15.1.5 */
hgfred([1/2,1], [3/2], -z^2);
atan(z)/z$

/* A&S 15.1.6 */
hgfred([1/2,1/2], [3/2], z^2);
asin(z)/z$

hgfred([1,1], [3/2], z^2);
asin(z)/z/sqrt(1-z^2)$

/* A&S 15.1.7 */
hgfred([1/2,1/2], [3/2], -z^2);
log(z+sqrt(1+z^2))/z$

hgfred([1,1], [3/2], -z^2);
log(z+sqrt(1+z^2))/z/sqrt(1+z^2)$

/* A&S 15.1.8 */
hgfred([a,b],[b],z);
(1-z)^(-a)$

/* A&S 15.1.9 */
hgfred([a,a+1/2],[1/2],z^2);
1/2*((z+1)^(-2*a)+(1-z)^(-2*a))$

/* A&S 15.1.10 */
hgfred([a,a+1/2],[3/2],z^2);
((z+1)^(1-2*a)-(1-z)^(1-2*a))/2/(1-2*a)/z$

/* A&S 15.1.11 */
hgfred([-a,a],[1/2],-z^2);
((z+sqrt(1+z^2))^(2*a) + (sqrt(1+z^2)-z)^(2*a))/2$

/* A&S 15.1.12 */
hgfred([a,1-a],[1/2],-z^2);
((sqrt(1+z^2)+z)^(2*a-1)+(sqrt(1+z^2)-z)^(2*a-1))/2/sqrt(1+z^2)$

/* A&S 15.1.13 */
hgfred([a,a+1/2],[1+2*a],z);
2^(2*a)/(1+sqrt(1-z))^(2*a)$

hgfred([a+1,a+1/2],[1+2*a],z);
2^(2*a)/(1+sqrt(1-z))^(2*a)/sqrt(1-z)$

/* A&S 15.1.14 */
hgfred([a,a+1/2],[2*a],z);
2^(2*a-1)/sqrt(1-z)*(1+sqrt(1-z))^(1-2*a)$

/* A&S 15.1.15 */
hgfred([a,1-a],[3/2],sin(z)^2);
sin((1-2*a)*z)/sin(z)/(1-2*a)$

/* A&S 15.1.16 */
hgfred([a,2-a],[3/2],sin(z)^2);
sin((2-2*a)*z)/(2-2*a)/(sin(z)*cos(z))$

/* A&S 15.1.17 */
assume(not(equal(sin(z),0)));
[not equal(sin(z),0)]$

hgfred([-a,a],[1/2],sin(z)^2);
cos(2*a*z)$

/* A&S 15.1.18 */
hgfred([a,1-a],[1/2],sin(z)^2);
cos((2*a-1)*z)/cos(z)$

/* A&S 15.1.19 */
assume(not(equal(tan(z),0)));
[not equal(tan(z), 0)]$

hgfred([a,a+1/2],[1/2],-tan(z)^2);
cos(z)^(2*a)*cos(2*a*z)$

/* A&S 15.4.3 */
assume(x > 0);
[x > 0]$

hgfred([-n,n],[1/2],x);
cos(2*n*asin(sqrt(x)))$

hgfred([-10,10],[1/2],x);
chebyshev_t(10,1-2*x)$

/* A&S 15.4.4 
 * (And A&S 8.2.1)
 */
hgfred([-n,n+1],[1],x);
legendre_p(-n-1,1-2*x);

/* A&S 8.1.2
 * Is there a bug in that formula?
 * http://functions.wolfram.com/HypergeometricFunctions/LegendreP2General/26/01/02/ 
 * shows the formula with (1+z) and (1-z).
 *
 * But this differs from formula 14 in Higher Transcendental
 * Functions, which agrees with A&S.
 *
 * Formula 14 says:
 *
 * P(v,u,z) = (z+1)^(u/2)*(z-1)^(-u/2)/gamma(1-u)*F(-v, 1+v; 1-u,(1-z)/2)
 *
 * Now what?
 *
 * This tests the legf14 function.
 */
radcan(((z+1)/(z-1))^(u/2)/gamma(1-u)*hgfred([-v,v+1],[1-u],(1-z)/2));
assoc_legendre_p(v,u,z)$

/* A&S 15.4.16 
 *
 * F(a,1-a;c;x) = gamma(c)*(-x)^(1/2-c/2)*(1-x)^(c/2-1/2)*P(-a,1-c,1-2*x)
 *
 * This tests the legf14 function.
 */
radcan(hgfred([a,1-a],[c],x)*(-x)^(c/2-1/2)*(1-x)^(1/2-c/2)/gamma(c));
assoc_legendre_p(-a, 1-c, 1-2*x)$

/* A&S 15.4.10 
 *
 * F(a,a+1/2;c;z) = 2^(c-1)*gamma(c)*z^(1/2-c/2)*(1-z)^(c/2-a-1/2)*P(2*a-c,1-c,1/sqrt(1-z))
 *
 * Test for legf24 function.
 */
radcan(hgfred([a,a+1/2],[c],z)*2^(1-c)*z^(c/2-1/2)*(1-z)^(1/2+a-c/2)/gamma(c));
/* Use A&S 8.2.1 to get this */
assoc_legendre_p(c-2*a-1,1-c,1/sqrt(1-z))$

2^u*(z^2-1)^(-u/2)*z^(v+u)/gamma(1-u)*hgfred([-v/2-u/2,1/2-v/2-u/2],[1-u],1-1/z^2);
assoc_legendre_p(v,u,z)$

/* A&S 15.4.12
 *
 * F(a,b;a+b+1/2;z) = 2^(a+b-1/2)*gamma(a+b+1/2)*(-z)^(1/2-a-b)*P(a-b-1/2,1/2-a-b,sqrt(1-z))
 * Test for legf20 function.
 */
expand(ratsimp(2^(1/2-a-b)*(-x)^(1/2*(a+b-1/2))/gamma(a+b+1/2)*hgfred([a,b],[a+b+1/2],x)));
assoc_legendre_p(-b+a-1/2,1/2-a-b,sqrt(1-x))$

2^m*(z^2-1)^(-m/2)/gamma(1-m)*hgfred([1/2+n/2-m/2, -n/2-m/2], [1-m], 1-z^2);
assoc_legendre_p(n,m,z)$

/*
 * Formula 36:
 * exp(-%i*m*%pi)*Q(n,m,z) = 
 *     2^n*gamma(1+n)*gamma(1+n+m)*(z+1)^(m/2-n-1)*(z-1)^(-m/2)/gamma(2+2*n)
 *     *hgfred([1+n-m,1+n],[2+2*n],2/(1+z))
 * 
 * Test for legf36 function.
 */
expand(radcan(hgfred([a,b],[2*b],z)*2^(-2*b)*sqrt(%pi)/gamma(b+1/2)*gamma(2*b-a)*z^b*(1-z)^((a-b)/2)*exp(%i*%pi*(b-a))));
/*
 * Maxima doesn't expand gamma(2*b) which would cancel the other
 * terms, so we leave it in.  
 */
2*sqrt(%pi)*assoc_legendre_q(b-1,b-a,2/z-1)*gamma(2*b)/(2^(2*b)*gamma(b)*gamma(b+1/2))$

hgfred([a,b],[2*b],z) - hgfred([b,a],[2*b],z);
0$

exp(%i*%pi*u)*2^v*gamma(1+v)*gamma(1+v+u)*(z+1)^(u/2-v-1)*(z-1)^(-u/2)/gamma(2+2*v)*hgfred([1+v-u,1+v],[2+2*v],2/(1+z));
assoc_legendre_q(v, u, z)$

/*
 * A&S 15.4.14
 *
 * F(a,b;a-b+1;z) = gamma(a-b+1)*z^(b/2-a/2)*(1-z)^(-b)*P(-b,b-a,(1+z)/(1-z))
 *
 * Test for legf16 function
 */
radcan(hgfred([a,b],[a-b+1],z));
gamma(-b+a+1)*z^((b-a)/2)*(1-z)^(-b)*assoc_legendre_p(b-1,b-a,(1+z)/(1-z))$

/*
 * Test for legf16 function
 */
2^(-v)*(z+1)^(u/2+v)*(z-1)^(-u/2)/gamma(1-u)*ratsimp(hgfred([-v,-v-u],[1-u],(z-1)/(z+1)));
assoc_legendre_p(v, u, z)$

/* Regression tests */

/* simpg tests */

/* F([...,0,...],[non-zero], z) is 1 */
hgfred([a,0],[c], z);
1$

/* F([non-zero],[...,zero or neg integer,...],z) is undefined */
hgfred([a,b],[0],z);
%f[2,1]([a,b],[0],z)$

hgfred([a,b],[c,4,-3],z);
%f[2,3]([a,b],[c,4,-3],z)$

/* F([...,neg integer,...],[...],z) is a polynomial */

/* Test 1F1 polynomials */
hgfred([-7],[c],z);
5040*gen_laguerre(7,c-1,z)*gamma(c)/gamma(c+7)$

hgfred([-2],[1],z);
laguerre(2,z)$

hgfred([-7],[1],z);
laguerre(7,z)$

hgfred([-2],[1/2],z);
hermite(4,sqrt(z))/12$

hgfred([-2],[3/2],z);
hermite(5,sqrt(z))/(120*sqrt(z))$

hgfred([a],[a+1],-z);
a*%gammagreek(a,z)/z^a$

hgfred([a],[a+2],-z);
a*(a+1)*%gammagreek(a,z)/z^a-a*(a+1)*%gammagreek(a+1,z)*z^(-a-1)$

/* Test 2F0 polynomials */
hgfred([-3,-3+1/2],[],z);
-hermite(6,%i/sqrt(z))*z^3/64$

hgfred([-3-1/2,-3],[],z);
%i*hermite(7,%i/sqrt(z))*z^(7/2)/128$

hgfred([-2,-4],[],z);
2*gen_laguerre(2,2,-1/z)*z^2$

/* Test that 2F0([a,b],...) = 2F0([b,a],...) */
hgfred([-4,-2],[],z);
2*gen_laguerre(2,2,-1/z)*z^2$

/* Test 2F1 polynomials */

hgfred([-2,1],[1/2],z);
8*jacobi_p(2,-1/2,-3/2,1-2*z)/3$

/* F(a,b;c;z) = F(b,a;c;z) */
hgfred([1,2],[3],z);
-2*(log(1-z)/z+1/z+log(1-z)*(1-z)/z^2)$

hgfred([1,2],[3],z)-hgfred([2,1],[3],z);
0$

/*
 * Test F(a,b;c;z) for some integral values of a,b,c.
 * These can all be written in terms of F(1,1;2;z).
 */

/*
 * A&S 15.2.6:
 * diff((1-z)^(a+b-c)*F(a,b;c;z),z,n) = poch(c-a,n)*poch(c-b,n)/poch(c,n)*
 *    (1-z)^(a+b-c-n)*F(a,b;c+n;z)
 *
 * With a=b=1 and c = 2, we have
 *
 * diff(F(1,1;2;z),z,n) = poch(1,n)*poch(1,n)/poch(2,n)*(1-z)^(-n)*F(1,1;2+n,z)
 *
 * And A&S 15.1.3 says F(1,1;2;z) = -log(1-z)/z.
 *
 * So F(1,1;2+n;z) = diff(F(1,1;2;z),z,n)*(1-z)^n*poch(2,n)/poch(1,n)/poch(1,n)
 *
 * F(1,1;3;z) = diff(F(1,1;2;z),z,1)*(1-z)*2/1!/1!
 *            = 2*(1-z)*diff(F(1,1;2;z),z,1)
 * F(1,1;4;z) = diff(F(1,1;2;z),z,2)*(1-z)^2*(2*3)/2!/2!
 *            = 3/2*(1-z)^2*diff(F(1,1;2;z),z,2);
 */

hgfred([1,1],[3],z);
2*(1/((1-z)*z)+log(1-z)/z^2)*(1-z)$

hgfred([1,1],[4],z);
3*(1/((1-z)^2*z)-2/((1-z)*z^2)-2*log(1-z)/z^3)*(1-z)^2/2$

/*
 * A&S 15.2.7:
 * diff((1-z)^(a+n-1)*F(a,b;c;z),z,n) 
 *    = (-1)^n*poch(a,n)*poch(c-b,n)/poch(c,n)*(1-z)^(a-1)*F(a+n,b;c+n;z)
 *
 * So
 * F(a+n,b;c+n;z) = (-1)^n*poch(c,n)/poch(a,n)/poch(c-b,n)*(1-z)^(1-a)
 *                  *diff((1-z)^(a+n-1)*F(a,b;c;z),z,n)
 *
 * Thus,
 * F(1+n,1;2+n;z) = (-1)^n*poch(2,n)/n!/n!*diff((1-z)^n*F(1,1;2;z),z,n)
 *
 * F(2,1;3;z) = -1*2*diff((1-z)*F(1,1;2;z),z,1)
 * F(3,1;4;z) = (2*3)/2!/2!*diff((1-z)^2*F(1,1;2;z),z,2)
 */
hgfred([2,1],[3],z);
-2*(log(1-z)/z+1/z+log(1-z)*(1-z)/z^2)$

hgfred([3,1],[4],z);
3*(-2*log(1-z)/z-3/z-4*log(1-z)*(1-z)/z^2-2*(1-z)/z^2
		       -2*log(1-z)*(1-z)^2/z^3)
	/2$

/*
 * A&S 15.2.2:
 * diff(F(a,b;c;z),z,n) = poch(a,n)*poch(b,n)/poch(c,n)*F(a+n,b+n;c+n;z)
 *
 * So 
 *
 * F(a+n,b+n;c+n;z) = poch(c,n)/poch(a,n)/poch(b,n)*diff(F(a,b;c;z),z,n)
 *
 * F(1+n,1+n;2+n;z) = poch(2,n)/n!/n!*diff(F(1,1;2;z),z,n)
 *
 * F(2,2;3;z) = 2*diff(F(1,1;2;z),z,1);
 * F(3,3;4;z) = 2*3/2!/2!*diff(f(1,1;2;z),z,2)
 */

hgfred([2,2],[3],z);
2*(1/((1-z)*z)+log(1-z)/z^2)$

hgfred([3,3],[4],z);
3*(1/((1-z)^2*z)-2/((1-z)*z^2)-2*log(1-z)/z^3)/2$

/*
 * A&S 15.3.9:
 * F(a,b;c;z) = A*z^(-a)*F(a,a-c+1;a+b-c+1;1-1/z)
 *              + B*(1-z)^(c-a-b)*z^(a-c)*F(c-a,1-a;c-a-b+1,1-1/z)
 *
 * where A = gamma(c)*gamma(c-a-b)/gamma(c-a)/gamma(c-b)
 *       B = gamma(c)*gamma(a+b-c)/gamma(a)/gamma(b)
 *
 * F(2,b;3;z) = A*z^(-2)*F(2,0;b;1-1/z) + B*(1-z)^(1-b)*z^(-1)*F(1,-1;2-b;1-1/z)
 * where A = gamma(3)*gamma(1-b)/gamma(1)/gamma(3-b) = 2*gamma(1-b)/gamma(3-b)
 *       B = gamma(3)*gamma(b-1)/gamma(2)/gamma(b) = 2*gamma(b-1)/gamma(b)
 *
 * And we know that F(2,0;b;1-1/z) = 1 and 
 * F(1,-1;2-b;1-1/z) = jacobi_p(1,1-b,b-2,1-2*(1-1/z))/(2-b).
 *
 * This tests geredf in hyp.lisp.
 *
 */
declare(ia,integer,ib,integer,ic,integer);
done$

hgfred([2,ib],[3],z);
2*jacobi_p(1,1-ib,ib-2,1-2*(1-1/z))*gamma(ib-1)*(1-z)^(1-ib)/((2-ib)*gamma(ib)*z)
	+2*gamma(1-ib)/(gamma(3-ib)*z^2)$

/*
 * Test of step4, which handles F(a,b;c;z) when a+b is an integer and
 * c + 1/2 is an integer.
 *
 */
assume(zn < 0);
[zn < 0]$

/*
 * Tests f81
 * First test.  F(a,-a;3/2;z)
 * A&S 15.2.6 tells us how to compute this:
 *
 * diff((1-z)^(a+b-c)*F(a,b;c;z),z,n) 
 *     = poch(c-a,n)*poch(c-b,n)/poch(c,n)*(1-z)^(a+b-c-n)*F(a,b;c+n;z)
 * 
 * So
 *
 * diff((1-z)^(-1/2)*F(a,-a;1/2;z),z,1)
 *     = poch(1/2-a,1)*poch(1/2+a,n)/poch(1/2,n)*(1-z)^(-3/2)*F(a,-a;3/2;z)
 *     = (1/2-a)*(1/2+a)/(1/2)*(1-z)^(-3/2)*F(a,-a;3/2;z)
 *
 * So
 * F(a,-a;3/2;z) = (1-z)^(3/2)*2/(1/2-a)/(1/2+a)*diff((1-z)^(-1/2)*F(a,-a;1/2;z),z,1)
 * 
 * A&S 15.1.11 and 15.1.17 tells us what F(a,-a;1/2;z) is.
 *
 */
hgfred([-a,a],[3/2],zn)-(1-zn)^(3/2)*(1/2)/(1/2-a)/(1/2+a)*diff((1-zn)^(-1/2)*hgfred([-a,a],[1/2],zn),zn,1);
0$

/*
 * Test f85
 * F(a+2,-a;1/2;zn)
 *
 * A&S 15.2.3:
 * diff(z^(a+n-1)*F(a,b;c;z),z,n) = poch(a,n)*z^(a-1)*F(a+n,b;c;z)
 *
 * or
 *
 * F(a+n,b;c;z) = z^(1-a)/poch(a,n)*diff(z^(a+n-1)*F(a,b;c;z),z,n)
 *
 * In this case, we have
 *
 * F(a+2,-a;1/2;z) = z^(1-a)/poch(a,2)*diff(z^(a+1)*F(a,-a;c;z),z,2)
 */
hgfred([a+2,-a],[1/2],zn)-zn^(1-a)/(a*(a+1))*diff(zn^(a+1)*hgfred([a,-a],[1/2],zn),zn,2);
0$

/*
 * Tests f83 
 * F(a-1,-a;1/2;z)
 *
 * F(a-1,-a;1/2;z)
 *
 * A&S 15.2.5:
 * diff(z^(c-a+m-1)*(1-z)^(a+b-c)*F(a,b;c;z),z,m)
 *   = poch(c-a,m)*z^(c-a-1)*(1-z)^(a+b-c-m)*F(a-m,b;c;z)
 *
 * So
 *
 * diff(z^(1/2-a)*(1-z)^(-1/2)*F(a,-a;1/2;z),z,1) 
 *    = poch(1/2-a,1)*z^(-a-1/2)*(1-z)^(-3/2)*F(a-1,-a;1/2;z)
 *
 * F(a-1,-a;1/2;z) 
 *    = (1-z)^(3/2)*z^(a+1/2)/(1/2-a)*diff(z^(1/2-a)*(1-z)^(-1/2)*F(a,-a;1/2;z),z,1)
 * 
 */
hgfred([a-1,-a],[1/2],zn)-(1-zn)^(3/2)*zn^(a+1/2)/(1/2-a)*diff(zn^(1/2-a)*(1-zn)^(-1/2)*hgfred([a,-a],[1/2],zn),zn,1);
0$

/*
 * Tests f84
 * F(a,-a;-1/2;z)
 *
 * A&S 15.2.4:
 * diff(z^(c-1)*F(a,b;c;z),z,n) = poch(c-n,n)*z^(c-n-1)*F(a,b;c-n;z)
 *
 * A&S 15.2.3:
 * diff(z^(a+m-1)*F(a,b;c;z),z,m) = poch(a,n)*z^(a-1)*F(a+n,b;c;z)
 *
 * So:
 * diff(z^(-1/2)*F(a,-a;1/2;z),z,1) = poch(1/2-1,1)*z^(1/2-1-1)*F(a,-a;-1/2;z)
 *
 * F(a,-a;-1/2;z) = z^(3/2)/poch(-1/2,1)*diff(z^(-1/2)*F(a,-a;1/2;z),z,1)
 * 
 */
hgfred([a,-a],[-1/2],zn) - zn^(3/2)/(-1/2)*diff(zn^(-1/2)*hgfred([a,-a],[1/2],zn),zn,1);
0$

/*
 * Tests f82
 * F(a-1,-a;-1/2;z)
 *
 * A&S 15.2.4
 * diff(z^(c-1)*F(a,b;c;z),z,n)
 *     = poch(c-n,n)*z^(c-n-1)*F(a;b;c-n;z)
 *
 * A&S 15.2.8:
 * diff(z^(c-1)*(1-z)^(b-c+n)*F(a,b;c;z),z,n)
 *     - poch(c-n,n)*z^(c-n-1)*(1-z)^(b-c)*F(a-n,b;c-n;z)
 *
 * So:
 * diff(z^(-1/2)*(1-z)^(-a+1/2)*F(a,-a;1/2;z),z,1)
 *      = poch(-1/2,1)*z^(-3/2)*(1-z)^(-a-1/2)*F(a-1,-a;-1/2;z)
 *
 * F(a-1,-a;-1/2;z) = z^(3/2)*(1-z)^(a+1/2)/poch(-1/2,1)*diff(z^(-1/2)*(1-z)^(-a+1/2)*F(a,-a;1/2;z),z,1)
 * 
 */
hgfred([a-1,-a],[-1/2],zn) - zn^(3/2)*(1-zn)^(a+1/2)/(-1/2)*diff(zn^(-1/2)*(1-zn)^(-a+1/2)*hgfred([a,-a],[1/2],zn),zn,1);
0$

/*
 * Tests f86
 * F(a-2,-a;-1/2;z)
 *
 * A&S 15.2.5
 * diff(z^(c-a+n-1)*(1-z)^(a+b-c)*F(a,b;c;z),z,n)
 *     = poch(c-a,n)*z^(c-a-1)*(1-z)^(a+b-c-n)*F(a-n,b;c;z)
 *
 * A&S 15.2.8:
 * diff(z^(c-1)*(1-z)^(b-c+n)*F(a,b;c;z),z,n)
 *     = poch(c-n,n)*z^(c-n-1)*(1-z)^(b-c)*F(a-n,b;c-n;z)
 *
 * For our problem:
 *
 * diff(z^(-a+1-1/2)*(1-z)^(-1/2)*F(a,-a;1/2;z),z,1)
 *     = poch(1/2-a,1)*z^(-a-1/2)*(1-z)^(-1/2-1)*F(a-1,-a;1/2;z)
 *     = (1/2-a)*z^(-a-1/2)*(1-z)^(-3/2)*F(a-1,-a;-1/2;z)
 *
 * diff(z^(-1/2)*(1-z)^(-a-1/2+1)*F(a-1,-a;1/2;z),z,1)
 *     = poch(1/2-1,1)*z^(-1-1/2)*(1-z)^(-a-1/2)*F(a-2,-a;-1/2;z)
 *     = -1/2*z^(-3/2)*(1-z)^(-a-1/2)*F(a-2,-a;-1/2;z)
 *
 * Let
 * G(z) = z^(-a-1/2)*(1-z)^(-3/2)*F(a-1,-a;1/2;z)
 *      = (1/2-a)^(-1)*diff(z^(-a+1/2)*(1-z)^(-1/2)*F(a,-a;1/2;z),z,1)
 *
 * F(a-2,-a;-1/2;z)
 *      = z^(3/2)*(1-z)^(a+1/2)/(-1/2)
 *         *diff(z^(-1/2)*(1-z)^(-a+1/2)*F(a-1,-a;1/2;z),z,1)
 *      = z^(3/2)*(1-z)^(a+1/2)/(-1/2)
 *         *diff(z^a*(1-z)^(2-a)*G(z),z,n)
 * 
 */
hgfred([a-2,-a],[-1/2],zn) - 
   zn^(3/2)*(1-zn)^(a+1/2)/(-1/2)*(1/2-a)^(-1)*
   diff(zn^a*(1-zn)^(2-a)
        *diff(zn^(-a+1/2)*(1-zn)^(-1/2)*hgfred([a,-a],[1/2],zn),zn,1)
        ,zn,1);
0$

/*
 * F(1,2;3/2;z)
 *
 * This is easily derived from F(1,1;3/2;z) via A&S 15.2.3:
 *
 * diff(z^(a+n-1)*F(a,b;c;z),z,n) = poch(a,n)*z^(a-1)*F(a+n,b;c;z)
 *
 * And from A&S 15.1.6, F(1,1;3/2;z^2) = asin(z)/z/sqrt(1-z^2).
 *
 * So 
 * diff(z*F(1,1;3/2;z),z,1) = poch(1,1)*F(2,1;3/2;z)
 *                          = F(1,2;3/2;z)
 *
 */

/* Tests step4-int */
hgfred([1,2],[3/2],zn) - diff(zn*hgfred([1,1],[3/2],zn),zn,1);
0$

/*
 * Some tests of splitpfq
 */

/*
 * From A&S 15.2.2
 *
 * diff(z^(a+n-1)*F(a,b;c;z),z,n) = poch(a,n)*z^(a-1)*F(a+n,b;c;z)
 *
 * So
 *
 * F(a+n,b;c;z) = z^(1-a)/poch(a,n)*diff(z^(a+n-1)*F(a,b;c;z),z,n)
 */

/*
 * F(a+3,b;a+2;z) = z^(1-a-2)/poch(a+2,1)*diff(z^(a+2+1-1)*F(a+2;b;a+2;z),z,1)
 *                = z^(-1-a)/(a+2)*diff(z^(a+2)*F(b;;z),z,1)
 * F(b;;z) = (1-z)^(-b)
 *
 * F(a+3,b;a+2,z) = z^(-1-a)/(a+2)*diff(z^(a+2)*(1-z)^(-b),z,1)
 */
hgfred([a+3,b],[a+2],z);
b*(1-z)^(-b-1)*z/(a+2)+1/(1-z)^b$

/*
 * F(a+4,b;a+2;z) = z^(1-a-2)/poch(a+2,2)*diff(z^(a+2+2-1)*F(a+2;b;a+2;z),z,2)
 *                = z^(-1-a)/(a+2)/(a+3)*diff(z^(a+3)*F(b;;z),z,2)
 *
 */
hgfred([b,a+4],[a+2],z);
b*(b+1)*(1-z)^(-b-2)*z^2/((a+2)*(a+3))
	+2*b*(1-z)^(-b-1)*z/(a+2)+1/(1-z)^b$
