@c version 1.10
@menu
* Definiciones para Constantes::   
@end menu

@node Definiciones para Constantes,  , Constantes, Constantes
@section Definiciones para Constantes

@defvr {Constante} %e
La base de los logaritmos naturales, e, se representa en Maxima como @code{%e}.

@end defvr

@defvr {Constante} false
Constante l@'ogica para "falso". (NIL en Lisp)

@end defvr

@defvr {Constante} inf
M@'as infinito.

@end defvr

@defvr {Constante}  infinity
Infinito complejo.

@end defvr

@defvr {Constante} minf
Menos infinito.

@end defvr

@defvr {Constante} %pi
El valor "pi" se representa en Maxima como @code{%pi}.

@end defvr

@defvr {Constante} true
Constante l@'ogica para "verdadero". (T en Lisp)

@end defvr
