foo_string: "
   !\" # $ % & ' ( ) * + , - . /
 0 1 2 3 4 5 6 7 8 9 : ; < = > ?
 @ A B C D E F G H I J K L M N O
 P Q R S T U V W X Y Z [ \ ] ^ _
 ` a b c d e f g h i j k l m n o
 p q r s t u v w x y z { | } ~
   Ħ ˘ £ ¤   Ĥ § ¨ İ Ş Ğ Ĵ ­   Ż
 ° ħ ² ³ ´ µ ĥ · ¸ ı ş ğ ĵ ½   ż
 À Á Â   Ä Ċ Ĉ Ç È É Ê Ë Ì Í Î Ï
   Ñ Ò Ó Ô Ġ Ö × Ĝ Ù Ú Û Ü Ŭ Ŝ ß
 à á â   ä ċ ĉ ç è é ê ë ì í î ï
   ñ ò ó ô ġ ö ÷ ĝ ù ú û ü ŭ ŝ ˙
";
