(kill(all), 'done);
'done$

(load(gentran), 'done);
'done$

gentranlang('fortran);
?fortran$

gentranlang('ratfor);
?ratfor$

gentranlang('c);
?c$

(gentranlang('c), ?\*gentranlang);
?c$

/* helper function to get gentran output as a string */
(sgentran(['L]):= block([s: make_string_output_stream(),
    ?genstmtno\*: 25000 ],
  gentranpush(s),
  apply(gentran, L),
  gentranpop(s),
  get_output_stream_string(s)),
'done);
'done;

(gentranlang('fortran), sgentran(a : 42));
"      a=42.0
"$

(gentranlang('ratfor), sgentran(a : 42));
"a=42.0
"$

(gentranlang('c),      sgentran(a : 42));
"a=42.0;
"$

/* the output is different from the one in the manual
   share/contrib/gentran/man/MANUAL.ps (page. 6)

(c2) gentran( for i:1 thru n do v[i]:0.0 );
      do 25001 i=1,n
          v(i)=0.0
25001 continue */
(gentranlang('fortran), sgentran(type(integer, n, i),
    for i:1 thru n do v[i]:0.0 ));
"      integer n,i
      i=1
25001 if (i .GT. n) goto 25002
          v(i)=0.0
          i=i+1
          goto 25001
25002 continue
"$


/*

Gentran is confused by batch

batch("rtest_gentran.mac", 'test);
(gentranlang('fortran), gentran(a : 42));

returns
true

One should reload
load("gentran")$
(gentranlang('fortran), gentran(a : 42))$

prints
a=42.0

*/




