@c Language=Russian
@c Encoding=CP1251
@c File=stirling.texi
@c OriginalRevision=1.3
@c TranslatedBy: (c) 2007-09-04 Alexey V. Beshenov <al@beshenov.ru>

@menu
* Формула Стирлинга::
@end menu

@node Формула Стирлинга,  , Пакет stirling, Пакет stirling
@section Формула Стирлинга

@deffn {Функция} stirling (@var{z},@var{n})

Заменяет @code{gamma(x)} по формуле Стирлинга @math{O(1/x^(2n-1))}. Сообщает об ошибке,
если @var{n} не является неотрицательным целым числом.

См. Abramowitz & Stegun, "Handbook of mathematical functions", 6.1.40.

Примеры:
@example
(%i1) load (stirling)$

(%i2) stirling(gamma(%alpha+x)/gamma(x),1);
       1/2 - x             x + %alpha - 1/2
(%o2) x        (x + %alpha)
                                   1           1
                            --------------- - ---- - %alpha
                            12 (x + %alpha)   12 x
                          %e
(%i3) taylor(%,x,inf,1);
                    %alpha       2    %alpha
          %alpha   x       %alpha  - x       %alpha
(%o3)/T/ x       + -------------------------------- + . . .
                                 2 x
(%i4) map('factor,%);
                                       %alpha - 1
         %alpha   (%alpha - 1) %alpha x
(%o4)   x       + -------------------------------
                                  2
@end example

Функция @code{stirling} различает переменную 'gamma' и функцию gamma:

@example
(%i5) stirling(gamma + gamma(x),0);
                                    x - 1/2   - x
(%o5)    gamma + sqrt(2) sqrt(%pi) x        %e
(%i6) stirling(gamma(y) + gamma(x),0);
                         y - 1/2   - y
(%o6) sqrt(2) sqrt(%pi) y        %e
                                              x - 1/2   - x
                         + sqrt(2) sqrt(%pi) x        %e
@end example


Для использования этой функции сначала напишите @code{load("stirling")}.

@opencatbox
@category{Гамма-функция и факториал} @category{Пакеты библиотеки share} @category{Пакет stirling}
@closecatbox

@end deffn
