@c Language: Brazilian Portuguese, Encoding: iso-8859-1
@c /ggf.texi/1.4/Sat Jun  2 00:13:21 2007//
@menu
* Funç@~{o}es e Vari@'{a}veis Definidas para ggf::
@end menu

@node Funç@~{o}es e Vari@'{a}veis Definidas para ggf,  , ggf, ggf
@section Funç@~{o}es e Vari@'{a}veis Definidas para ggf

@defvr {Vari@'{a}vel de Opç@~{a}o} GGFINFINITY
Valor padr@~{a}o: 3

Essa @'{e} uma vari@'{a}vel de opç@~{a}o para a funç@~{a}o @code{ggf}.

Quando calculando a fraç@~{a}o cont@'{i}nua da
funç@~{a}o geradora, um quociente parcial tendo um grau
(estritamente) maior que @var{GGFINFINITY} ser@'{a} descartado e
o convergente atual ser@'{a} considerado como o valor exato
da funç@~{a}o geradora; na grande mioria dos casos o grau de todos
os quocientes parciais ser@'{a} ou 0 ou 1; se voc@^{e} usar um valor muito grande,
ent@~{a}o voc@^{e} poder@'{a} fornecer termos suficientes com o objetivo de fazer o
c@'{a}lculo preciso o bastante.


Veja tamb@'{e}m @code{ggf}.
@end defvr


@defvr {Vari@'{a}vel de opç@~{a}o} GGFCFMAX
Valor padr@~{a}o: 3

Essa @'{e} uma vari@'{a}vel de opç@~{a}o para a funç@~{a}o @code{ggf}.

Quando calculando a fraç@~{a}o cont@'{i}nua da
funç@~{a}o geradora, se nenhum bom resultado for encontrado (veja
o sinalizador @var{GGFINFINITY}) ap@'{o}s se ter calculado uma quantidade de @var{GGFCFMAX} quocientes
parciais, a funç@~{a}o geradora ser@'{a} considerada como
n@~{a}o sendo uma fraç@~{a}o de dois polin@^{o}mios e a funç@~{a}o ir@'{a}
terminar. Coloque livemente um valor muito grande para funç@~{o}es geradoras
mais complicadas.

Veja tamb@'{e}m @code{ggf}.
@end defvr

@deffn {Funç@~{a}o} ggf (@var{l})
Calcula a funç@~{a}o geradora (se for uma fraç@~{a}o de dois
polin@^{o}mios) de uma seq@"{u}@^{e}ncia, sendo dados seus primeiros termos. @var{l}
@'{e} uma lista de n@'{u}meros.

A soluç@~{a}o @'{e} retornada como uma fraç@~{a}o de dois polin@^{o}mios.
Se nenhuma soluç@~{a}o tiver sido encontrada, @'{e} retornado @code{done}.

Essa funç@~{a}o @'{e} controlada attrav@'{e}s das vari@'{a}veis globais @var{GGFINFINITY} e @var{GGFCFMAX}. Veja tamb@'{e}m @var{GGFINFINITY} e @var{GGFCFMAX}.

Para usar essa funç@~{a}o primeiro escreva @code{load("ggf")}.
@end deffn
