# -*-mode: makefile; fill-column: 75; tab-width: 8; coding: iso-latin-1-unix -*-
#
#	$Id: Makefile,v 1.1 2002-09-22 03:16:20 mikeclarkson Exp $
#

default::	pdf

pdf::
	pdflatex EMIntro.tex

dvi::
	latex EMIntro.tex

ps::	dvi
	dvips EMIntro


