/* Code by Fabrizio Caruso */

dir : "./sarag/";

modLoad(modName) :=
  load(concat(dir,modName));

modLoad("settings.mac");

modLoad("aliases.mac");

modLoad("constants.mac");

modLoad("lowLevel.mac");

modLoad("sarag_linear_algebra.mac");

modLoad("rootCounting.mac");

modLoad("rootIsolation.mac");

modLoad("signDetermination.mac");

modLoad("intervalArithmetic.mac");

modLoad("topology.mac");

modLoad("examples.mac");

modLoad("topology_examples.mac");


