#!/usr/bin/perl

# an additional filter for update_examples

use warnings;
use strict;

my $example_output_beg = '^@example\s*$';
my $example_output_end = '^@end\s+example\s*$';
my $input_line_beg     = '^\s*\(%i\d+\)';
my @buff;

my $in_example_output = 0;

sub print_buf {
    print "\@group\n"     if scalar @_ >= 2;
    print @_;
    print "\@end group\n" if scalar @_ >= 2;
    @buff = ();
}

foreach (<>) {
    if (/$example_output_end/) {
        $in_example_output = 0;
        &print_buf(@buff);
    }
    elsif (/$example_output_beg/) {
        $in_example_output = 1;
    }
    elsif ($in_example_output) {
        &print_buf(@buff) if /$input_line_beg/;
        push @buff, $_;
        next;
    }
    print;
}
