\input texinfo
@setfilename  maxima.info
@finalout
@include include-maxima.texi

@c Include documentation categories
@ifhtml
@node Documentation Categories, , Function and Variable Index
@chapter Documentation Categories
@c Documentation categories section gets filled in by the script build_html.sh
@end ifhtml
@bye
