The package @code{ratpow} provides functions that find the exponents
of the denominator in a CRE polynomial. If the exponents in the denominator
are needed instead @mref{ratdenom} can be used to extract this denominator
first. Returned coefficients are in CRE form except for numbers.

In order to get a list of vars in a CRE polynomial @mref{showratvars} can be
used.

@menu
* Functions and Variables for ratpow::
@end menu

@node Functions and Variables for ratpow, , Top, Top
@section Functions and Variables for ratpow



@anchor{ratp_hipow}
@deffn {Function} ratp_hipow @
@fname{ratp_hipow} (@var{expr}, @var{x}) @

Finds the highest power of the main variable in @code{ratnumer(expr)}

@c ===beg===
@c load("ratpow")$
@c ratp_hipow( x^(5/2) + x^2 , x);
@c ratp_hipow( x^(5/2) + x^2 , sqrt(x));
@c ===end===
@example
(%i1) load("ratpow")$
@group
(%i2) ratp_hipow( x^(5/2) + x^2 , x);
(%o2)                           2
@end group
@group
(%i3) ratp_hipow( x^(5/2) + x^2 , sqrt(x));
(%o3)                           5
@end group
@end example

@opencatbox
@category{Package ratpow}
@closecatbox
@end deffn


@anchor{ratp_coeffs}
@deffn {Function} ratp_coeffs @
@fname{ratp_coeffs} (@var{expr}, @var{x}) @

Generates a list of powers and coefficients of the main variable
@code{ratnumer(expr)}.
@c ===beg===
@c load("ratpow")$
@c ratp_coeffs( 4*x^3 + x + sqrt(x), x);
@c ===end===
@example
(%i1) load("ratpow")$
@group
(%i2) ratp_coeffs( 4*x^3 + x + sqrt(x), x);
(%o2)/R/         [[3, 4], [1, 1], [0, sqrt(x)]]
@end group
@end example
@opencatbox
@category{Package ratpow}
@closecatbox
@end deffn

@anchor{ratp_dense_coeffs}
@deffn {Function} ratp_dense_coeffs @
@fname{ratp_dense_coeffs} (@var{expr}, @var{x}) @

Generates a list of coefficients in @code{ratnumer(expr)}; returned
coefficients are in CRE form except for numbers.

@c ===beg===
@c load("ratpow")$
@c ratp_dense_coeffs( 4*x^3 + x + sqrt(x), x);
@c ===end===
@example
(%i1) load("ratpow")$
@group
(%i2) ratp_dense_coeffs( 4*x^3 + x + sqrt(x), x);
(%o2)/R/               [4, 0, 1, sqrt(x)]
@end group
@end example

@opencatbox
@category{Package ratpow}
@closecatbox
@end deffn

