@menu
* Introduction for Runtime Environment::  
* Interrupts::                  
* Definitions for Runtime Environment::  
@end menu


@node Introduction for Runtime Environment, Interrupts, Runtime Environment, Runtime Environment
@section Introduction for Runtime Environment
@c THIS DISCUSSION OF maxima-init.mac REPLACES AN EARLIER WRITE-UP. !!!
@c HOWEVER IT SEEMS THAT THIS TEXT REALLY WANTS TO BE UNDER A DIFFERENT HEADING. !!!
@code{maxima-init.mac} is a file which is loaded automatically when Maxima starts.
You can use @code{maxima-init.mac} to customize your Maxima environment.
@code{maxima-init.mac}, if it exists, is typically placed in the
directory named by @code{:lisp (default-userdir)},
although it can be in any directory searched by the function @code{file_search}.

Here is an example @code{maxima-init.mac} file:

@example
setup_autoload ("specfun.mac", ultraspherical, assoc_legendre_p);
showtime:all;
@end example

In this example, @code{setup_autoload} tells Maxima to load the
specified file
(@code{specfun.mac}) if any of the functions (@code{ultraspherical},
@code{assoc_legendre_p}) are called but not yet defined.
Thus you needn't remember to load the file before calling the functions.

The statement @code{showtime: all} tells Maxima to set the @code{showtime} variable.
The @code{maxima-init.mac} file can contain any other assignments or
other Maxima statements.

@node Interrupts, Definitions for Runtime Environment, Introduction for Runtime Environment, Runtime Environment
@section Interrupts

The user can stop a time-consuming computation with the
^C (control-C) character.
The default action is to stop the computation
and print another user prompt.
In this case, it is not possible to restart a stopped computation.

If the variable @code{*debugger-hook*} is set to @code{nil}, by executing

@example
:lisp (setq *debugger-hook* nil)
@end example

@noindent
then upon receiving ^C, Maxima will enter the Lisp debugger,
and the user may use the debugger to inspect the Lisp environment.
The stopped computation can be restarted by entering
@code{continue} in the Lisp debugger.
The means of returning to Maxima from the Lisp debugger
(other than running the computation to completion)
is different for each version of Lisp.

On Unix systems, the character ^Z (control-Z) causes Maxima
to stop altogether, and control is returned to the shell prompt.
The @code{fg} command causes Maxima
to resume from the point at which it was stopped.

@c end concepts Runtime Environment
@node Definitions for Runtime Environment,  , Interrupts, Runtime Environment
@section Definitions for Runtime Environment

@c NEEDS EXPANSION AND CLARIFICATION
@defvr declaration feature
Maxima understands two distinct types of features,
system features and features which apply to mathematical expressions.
See also @code{status} for information about system features.
See also @code{features} and @code{featurep} for information about mathematical features.
@c PROPERTIES, DECLARATIONS FALL UNDER THIS HEADING AS WELL
@c OTHER STUFF ??

@code{feature} itself is not the name of a function or variable.

@end defvr

@c NEEDS CLARIFICATION, ESPECIALLY WRT THE EXTENT OF THE FEATURE SYSTEM
@c (I.E. WHAT KINDS OF THINGS ARE FEATURES ACCORDING TO featurep)
@defun featurep (@var{a}, @var{f})
Attempts to determine whether the object @var{a} has the
feature @var{f} on the basis of the facts in the current database.  If so,
it returns @code{true}, else @code{false}.  See also @code{features}.

@example
(%i1) declare (j, even)$
(%i2) featurep (j, integer);
(%o2)                           true
@end example

@end defun

@defun room ()
@defunx room (true)
@defunx room (false)
Prints out a description of the state of storage and
stack management in Maxima. @code{room} calls the Lisp function of 
the same name.

@itemize @bullet
@item
@code{room ()} prints out a moderate description.
@item
@code{room (true)} prints out a verbose description.
@item
@code{room (false)} prints out a terse description.
@end itemize

@end defun

@defun status (feature)
@defunx status (feature, @var{putative_feature})
@defunx status (status)
Returns information about the presence or absence of certain
system-dependent features.

@itemize @bullet
@item
@code{status (feature)} returns a list of system features.
These include Lisp version, operating system type, etc.
The list may vary from one Lisp type to another.
@item @code{status (feature, @var{putative_feature})} returns @code{true} if @var{putative_feature}
is on the list of items returned by @code{status (feature)} and @code{false} otherwise.
@code{status} quotes the argument @var{putative_feature}.
The double single quotes operator, @code{'@w{}'}, defeats the quotation.
A feature whose name contains a special character, such as a hyphen,
must be given as a string argument. For example,
@code{status (feature, "ansi-cl")}.
@item
@code{status (status)} returns a two-element list @code{[feature, status]}.
@code{feature} and @code{status} are the two arguments accepted by the @code{status} function;
it is unclear if this list has additional significance.
@end itemize

The variable @code{features} contains a list of features which apply to 
mathematical expressions. See @code{features} and @code{featurep} for more information.

@end defun

@defun time (%o1, %o2, %o3, ...)
Returns a list of the times, in seconds, taken to compute the output
lines @code{%o1}, @code{%o2}, @code{%o3}, .... The time returned is Maxima's estimate of
the internal computation time, not the elapsed time. @code{time} can only
be applied to output line variables; for any other variables, @code{time}
returns @code{unknown}.

Set @code{showtime: true} to make Maxima print out the computation time 
and elapsed time with each output line.

@end defun
