@c end concepts Statistics
@menu
* Definitions for Statistics::  
@end menu

@node Definitions for Statistics,  , Statistics, Statistics
@section Definitions for Statistics

@deffn {Function} gauss (@var{mean}, @var{sd})
Returns a random floating point number from a normal
distribution with mean @var{mean} and standard deviation @var{sd}.

@end deffn
