      SUBROUTINE RHOA(A,LAMBDA,X,PAR,IPAR)
      DOUBLE PRECISION A(1),LAMBDA,X(1),PAR(1)
      INTEGER IPAR(1)
C
C PAR(1:*) AND IPAR(1:*) ARE ARRAYS FOR (OPTIONAL) USER PARAMETERS,
C    WHICH ARE SIMPLY PASSED THROUGH TO THE USER WRITTEN SUBROUTINES
C    RHOA, RHOJS.
C
C CALCULATE AND RETURN IN  A  THE VECTOR Z SUCH THAT
C  RHO(Z,LAMBDA,X) = 0 .
C
      RETURN
      END
