@c /impdiff.texi/1.1/Sun Mar 19 20:02:45 2006//
@menu
* Definições para impdiff::
@end menu

@node Definições para impdiff,  , impdiff, impdiff
@section Definições para impdiff

@deffn {Função} implicit_derivative (@var{f},@var{indvarlist},@var{orderlist},@var{depvar})
Essa subrotina calcula derivadas implícitas de funções de várias variáveis.
@var{f} é uma função do tipo array, os índices são o grau da derivada na ordem @var{indvarlist};
@var{indvarlist} é a lista de variáveis independentes; @var{orderlist} é a ordem desejada; e 
@var{depvar} é a variável dependente.

Para usar essa função escreva primeiro @code{load("impdiff")}.
@end deffn

