@menu
* Introduction to Numerical::   
* Fourier packages::                     
* Definitions for Numerical::   
* Definitions for Fourier Series::
@end menu

@node Introduction to Numerical, Fourier packages, Numerical, Numerical
@section Introduction to Numerical

@node Fourier packages, Definitions for Numerical, Introduction to Numerical, Numerical
@section Fourier packages

THIS SECTION NEEDS TO BE TRANSLATED.

@node Definitions for Numerical, Definitions for Fourier Series, Fourier packages, Numerical
@section Definitions for Numerical

THIS SECTION NEEDS TO BE TRANSLATED.

@node Definitions for Fourier Series, , Definitions for Numerical, Numerical
@section Definitions for Fourier Series

THIS SECTION NEEDS TO BE TRANSLATED.
