@menu
* Definitions for Affine::
@end menu

@node Definitions for Affine,  , Affine, Affine
@section Definitions for Affine

@deffn {Function} fast_linsolve ([@mvar{expr_1}, ..., @mvar{expr_m}], [@mvar{x_1}, ..., @mvar{x_n}])
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} grobner_basis ([@mvar{expr_1}, ..., @mvar{expr_m}])
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} set_up_dot_simplifications (@mvar{eqns}, @mvar{check_through_degree})
@deffnx {Function} set_up_dot_simplifications (@mvar{eqns})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} declare_weights (@mvar{x_1}, @mvar{w_1}, ..., @mvar{x_n}, @mvar{w_n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} nc_degree (@mvar{p})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} dotsimp (@mvar{f})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} fast_central_elements ([@mvar{x_1}, ..., @mvar{x_n}], @mvar{n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} check_overlaps (@mvar{n}, @mvar{add_to_simps})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} mono ([@mvar{x_1}, ..., @mvar{x_n}], @mvar{n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} monomial_dimensions (@mvar{n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} extract_linear_equations ([@mvar{p_1}, ..., @mvar{p_n}], [@mvar{m_1}, ..., @mvar{m_n}])
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} list_nc_monomials ([@mvar{p_1}, ..., @mvar{p_n}])
@deffnx {Function} list_nc_monomials (@mvar{p})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} all_dotsimp_denoms
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

