@menu
* Definitions for augmented_lagrangian::
@end menu

@node Definitions for augmented_lagrangian,  , augmented_lagrangian, augmented_lagrangian
@section Definitions for augmented_lagrangian

@deffn {Function} augmented_lagrangian_method (@var{FOM}, @var{xx}, @var{C}, @var{yy})
@deffnx {Function} augmented_lagrangian_method (@var{FOM}, @var{xx}, @var{C}, @var{yy}, optional_args)
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

