@menu
* Definitions for Differentiation::  
@end menu

@node Definitions for Differentiation,  , Differentiation, Differentiation
@section Definitions for Differentiation

@deffn {Function} antid (@mvar{expr}, @mvar{x}, @mvar{u(x)}) 
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} antidiff (@mvar{expr}, @mvar{x}, @mvar{u}(@mvar{x}))
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Property} atomgrad
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} atvalue (@mvar{expr}, [@mvar{x_1} = @mvar{a_1}, ..., @mvar{x_m} = @mvar{a_m}], @mvar{c})
@deffnx {Function} atvalue (@mvar{expr}, @mvar{x_1} = @mvar{a_1}, @mvar{c})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} cartan  -
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} del (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} delta (@mvar{t})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {System variable} dependencies
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} depends (@mvar{f_1}, @mvar{x_1}, ..., @mvar{f_n}, @mvar{x_n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} derivabbrev
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} derivdegree (@mvar{expr}, @mvar{y}, @mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} derivlist (@mvar{var_1}, ..., @mvar{var_k})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} derivsubst
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} diff (@mvar{expr}, @mvar{x_1}, @mvar{n_1}, ..., @mvar{x_m}, @mvar{n_m})
@deffnx {Function} diff (@mvar{expr}, @mvar{x}, @mvar{n})
@deffnx {Function} diff (@mvar{expr}, @mvar{x})
@deffnx {Function} diff (@mvar{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Special symbol} diff
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} dscalar (@mvar{f})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} express (@mvar{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} gradef (@mvar{f}(@mvar{x_1}, ..., @mvar{x_n}), @mvar{g_1}, ..., @mvar{g_m})
@deffnx {Function} gradef (@mvar{a}, @mvar{x}, @mvar{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {System variable} gradefs
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} laplace (@mvar{expr}, @mvar{t}, @mvar{s})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

