@menu
* Definitions for Equations::   
@end menu

@node Definitions for Equations,  , Equations, Equations
@section Definitions for Equations

@defvr {System variable} %rnum_list
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} algexact
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} algsys ([@mvar{expr_1}, ..., @mvar{expr_m}], [@mvar{x_1}, ..., @mvar{x_n}])
@deffnx {Function} algsys ([@mvar{eqn_1}, ..., @mvar{eqn_m}], [@mvar{x_1}, ..., @mvar{x_n}])
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} allroots (@mvar{expr})
@deffnx {Function} allroots (@mvar{eqn})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} backsubst
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} breakup
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} dimension (@mvar{eqn})
@deffnx {Function} dimension (@mvar{eqn_1}, ..., @mvar{eqn_n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} dispflag
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} funcsolve (@mvar{eqn}, @mvar{g}(@mvar{t}))
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} globalsolve
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} ieqn (@mvar{ie}, @mvar{unk}, @mvar{tech}, @mvar{n}, @mvar{guess})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} ieqnprint
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} lhs (@mvar{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} linsolve ([@mvar{expr_1}, ..., @mvar{expr_m}], [@mvar{x_1}, ..., @mvar{x_n}])
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} linsolvewarn
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} linsolve_params
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {System variable} multiplicities
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} nroots (@mvar{p}, @mvar{low}, @mvar{high})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} nthroot (@mvar{p}, @mvar{n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} programmode
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} realonly
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} realroots (@mvar{expr}, @mvar{bound})
@deffnx {Function} realroots (@mvar{eqn}, @mvar{bound})
@deffnx {Function} realroots (@mvar{expr})
@deffnx {Function} realroots (@mvar{eqn})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} rhs (@mvar{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} rootsconmode
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} rootscontract (@mvar{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} rootsepsilon
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} solve (@mvar{expr}, @mvar{x})
@deffnx {Function} solve (@mvar{expr})
@deffnx {Function} solve ([@mvar{eqn_1}, ..., @mvar{eqn_n}], [@mvar{x_1}, ..., @mvar{x_n}])
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} solvedecomposes
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} solveexplicit
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} solvefactors
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} solvenullwarn
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} solveradcan
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} solvetrigwarn
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} solve_inconsistent_error
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

