@menu
* Comments::
* Files::                       
* Definitions for Input and Output::  
@end menu

@node Comments, Files, Input and Output, Input and Output
@section Comments

@node Files, Definitions for Input and Output, Comments, Input and Output
@section Files

@node Definitions for Input and Output,  , Files, Input and Output
@section Definitions for Input and Output

@defvr {System variable} __
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {System variable} _
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {System variable} %
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {System variable} %%
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} %edispflag
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} %th (@mvar{i})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Special symbol} ?
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} absboxchar
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} file_output_append
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} appendfile (@mvar{filename})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} batch (@mvar{filename})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} batchload (@mvar{filename})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} closefile ()
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} collapse (@mvar{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} concat (@mvar{arg_1}, @mvar{arg_2}, ...)
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} sconcat (@mvar{arg_1}, @mvar{arg_2}, ...)
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} disp (@mvar{expr_1}, @mvar{expr_2}, ...)
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} dispcon (@mvar{tensor_1}, @mvar{tensor_2}, ...)
@deffnx {Function} dispcon (all)
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} display (@mvar{expr_1}, @mvar{expr_2}, ...)
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} display2d
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} display_format_internal
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} dispterms (@mvar{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} error_size
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} error_syms
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} expt (@mvar{a}, @mvar{b})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} exptdispflag
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} filename_merge (@mvar{path}, @mvar{filename})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} file_search (@mvar{filename})
@deffnx {Function} file_search (@mvar{filename}, @mvar{pathlist})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} file_search_maxima
@defvrx {Option variable} file_search_lisp
@defvrx {Option variable} file_search_demo
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} file_type (@mvar{filename})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} grind (@mvar{expr})
@deffnx {Option variable} grind
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} ibase
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} inchar
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} ldisp (@mvar{expr_1}, ..., @mvar{expr_n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} ldisplay (@mvar{expr_1}, ..., @mvar{expr_n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} linechar
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} linel
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} lispdisp
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} load (@mvar{filename})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} loadfile (@mvar{filename})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} loadprint
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} obase
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} outchar
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} packagefile
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} pfeformat
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} print (@mvar{expr_1}, ..., @mvar{expr_n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} tcl_output (@mvar{list}, @mvar{i0}, @mvar{skip})
@deffnx {Function} tcl_output (@mvar{list}, @mvar{i0})
@deffnx {Function} tcl_output ([@mvar{list_1}, ..., @mvar{list_n}], @mvar{i})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} read (@mvar{expr_1}, ..., @mvar{expr_n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} readonly (@mvar{expr_1}, ..., @mvar{expr_n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} reveal (@mvar{expr}, @mvar{depth})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} rmxchar
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} save (@mvar{filename}, @mvar{name_1}, @mvar{name_2}, @mvar{name_3}, ...)
@deffnx {Function} save (@mvar{filename}, values, functions, labels, ...)
@deffnx {Function} save (@mvar{filename}, [@mvar{m}, @mvar{n}])
@deffnx {Function} save (@mvar{filename}, @mvar{name_1}=@mvar{expr_1}, ...)
@deffnx {Function} save (@mvar{filename}, all)
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} savedef
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} show (@mvar{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} showratvars (@mvar{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} stardisp
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} string (@mvar{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Lisp variable} stringdisp
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} stringout (@mvar{filename}, @mvar{expr_1}, @mvar{expr_2}, @mvar{expr_3}, ...)
@deffnx {Function} stringout (@mvar{filename}, [@mvar{m}, @mvar{n}])
@deffnx {Function} stringout (@mvar{filename}, input)
@deffnx {Function} stringout (@mvar{filename}, functions)
@deffnx {Function} stringout (@mvar{filename}, values)
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} tex (@mvar{expr})
@deffnx {Function} tex (@mvar{label})
@deffnx {Function} tex (@mvar{expr}, @mvar{filename})
@deffnx {Function} tex (@mvar{label}, @mvar{filename})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} texput (@mvar{a}, @mvar{s})
@deffnx {Function} texput (@mvar{a}, @mvar{s}, @mvar{operator_type})
@deffnx {Function} texput (@mvar{a}, [@mvar{s_1}, @mvar{s_2}], matchfix)
@deffnx {Function} texput (@mvar{a}, [@mvar{s_1}, @mvar{s_2}, @mvar{s_3}], matchfix)
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} system (@mvar{command})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} ttyoff
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} with_stdout (@mvar{filename}, @mvar{expr_1}, @mvar{expr_2}, @mvar{expr_3}, ...)
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} writefile (@mvar{filename})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

