@menu
* Definitions for opsubst::
@end menu

@node Definitions for opsubst,  , opsubst, opsubst
@section Definitions for opsubst

@deffn {Function} opsubst (@mvar{f},@mvar{g},@mvar{e})
@deffnx {Function} opsubst (@mvar{g}=@mvar{f},@mvar{e})
@deffnx {Function} opsubst ([@mvar{g1}=@mvar{f1},@mvar{g2}=@mvar{f2},..., @mvar{gn}=@mvar{fn}],@mvar{e})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

