@menu
* Introduction to Polynomials::  
* Definitions for Polynomials::  
@end menu

@node Introduction to Polynomials, Definitions for Polynomials, Polynomials, Polynomials
@section Introduction to Polynomials

@node Definitions for Polynomials,  , Introduction to Polynomials, Polynomials
@section Definitions for Polynomials

@defvr {Option variable} algebraic
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} berlefact
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} bezout (@var{p1}, @var{p2}, @var{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} bothcoef (@var{expr}, @var{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} coeff (@var{expr}, @var{x}, @var{n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} combine (@var{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} content (@var{p_1}, @var{x_1}, ..., @var{x_n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} denom (@var{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} divide (@var{p_1}, @var{p_2}, @var{x_1}, ..., @var{x_n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} eliminate ([@var{eqn_1}, ..., @var{eqn_n}], [@var{x_1}, ..., @var{x_k}])
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} ezgcd (@var{p_1}, @var{p_2}, @var{p_3}, ...)
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} facexpand
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} factcomb (@var{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} factor (@var{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} factorflag
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} factorout (@var{expr}, @var{x_1}, @var{x_2}, ...)
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} factorsum (@var{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} fasttimes (@var{p_1}, @var{p_2})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} fullratsimp (@var{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} fullratsubst (@var{a}, @var{b}, @var{c})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} gcd (@var{p_1}, @var{p_2}, @var{x_1}, ...)
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} gcdex (@var{f}, @var{g})
@deffnx {Function} gcdex (@var{f}, @var{g}, @var{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} gcfactor (@var{n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} gfactor (@var{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} gfactorsum (@var{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} hipow (@var{expr}, @var{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} intfaclim
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} keepfloat
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} lratsubst (@var{L}, @var{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} modulus
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} num (@var{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} polydecomp (@var{p}, @var{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} quotient (@var{p_1}, @var{p_2})
@deffnx {Function} quotient (@var{p_1}, @var{p_2}, @var{x_1}, ..., @var{x_n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} rat (@var{expr})
@deffnx {Function} rat (@var{expr}, @var{x_1}, ..., @var{x_n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} ratalgdenom
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} ratcoef (@var{expr}, @var{x}, @var{n})
@deffnx {Function} ratcoef (@var{expr}, @var{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} ratdenom (@var{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} ratdenomdivide
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} ratdiff (@var{expr}, @var{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} ratdisrep (@var{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} ratepsilon
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} ratexpand (@var{expr})
@deffnx {Option variable} ratexpand
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} ratfac
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} ratnumer (@var{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} ratnump (@var{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} ratp (@var{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} ratprint
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} ratsimp (@var{expr})
@deffnx {Function} ratsimp (@var{expr}, @var{x_1}, ..., @var{x_n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} ratsimpexpons
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} ratsubst (@var{a}, @var{b}, @var{c})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} ratvars (@var{x_1}, ..., @var{x_n})
@deffnx {Function} ratvars ()
@deffnx {System variable} ratvars
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} ratweight (@var{x_1}, @var{w_1}, ..., @var{x_n}, @var{w_n})
@deffnx {Function} ratweight ()
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {System variable} ratweights
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} ratwtlvl
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} remainder (@var{p_1}, @var{p_2})
@deffnx {Function} remainder (@var{p_1}, @var{p_2}, @var{x_1}, ..., @var{x_n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} resultant (@var{p_1}, @var{p_2}, @var{x})
@deffnx {Variable} resultant
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} savefactors
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} sqfr (@var{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} tellrat (@var{p_1}, ..., @var{p_n})
@deffnx {Function} tellrat ()
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} totaldisrep (@var{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} untellrat (@var{x_1}, ..., @var{x_n})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

