@menu
* Introduction to Trigonometric::  
* Definitions for Trigonometric::  
@end menu

@node Introduction to Trigonometric, Definitions for Trigonometric, Trigonometric, Trigonometric
@section Introduction to Trigonometric

@node Definitions for Trigonometric,  , Introduction to Trigonometric, Trigonometric
@section Definitions for Trigonometric

@deffn {Function} acos (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} acosh (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} acot (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} acoth (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} acsc (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} acsch (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} asec (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} asech (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} asin (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} asinh (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} atan (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} atan2 (@mvar{y}, @mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} atanh (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Package} atrig1
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} cos (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} cosh (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} cot (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} coth (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} csc (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} csch (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} halfangles
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Package} ntrig
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} sec (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} sech (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} sin (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} sinh (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} tan (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} tanh (@mvar{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} trigexpand (@mvar{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} trigexpandplus
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} trigexpandtimes
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@defvr {Option variable} triginverses
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} trigreduce (@mvar{expr}, @mvar{x})
@deffnx {Function} trigreduce (@mvar{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Option variable} trigsign
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} trigsimp (@mvar{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} trigrat (@mvar{expr})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

