@menu
* Introduction to Units::       
* Definitions for Units::       
@end menu

@node Introduction to Units, Definitions for Units, unit, unit
@section Introduction to Units

@node Definitions for Units,  , Introduction to Units, unit
@section Definitions for Units

@deffn {Function} setunits (@var{list})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} uforget (@var{list})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@deffn {Function} convert (@var{expr}, @var{list})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Optional variable} usersetunits
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

@deffn {Function} metricexpandall (@var{x})
THIS ITEM NEEDS TO BE TRANSLATED.
@end deffn

@defvr {Variable} %unitexpand
THIS ITEM NEEDS TO BE TRANSLATED.
@end defvr

