xy: [[10,.6],[20,.9],[30,1.1],[40,1.3],[50,1.4]]$
plot2d ([[discrete,xy], 2*%pi*sqrt(l/980)], [l,0,50], [style,points,lines],
  [color,red,blue], [point_type,asterisk], [legend,"experiment","theory"],
  [xlabel,"pendulum's length (cm)"], [ylabel, "period (s)"],
  [pdf_file,"./plotting16.pdf"]);
plot2d ([[discrete,xy], 2*%pi*sqrt(l/980)], [l,0,50], [style,points,lines],
  [color,red,blue], [point_type,asterisk], [legend,"experiment","theory"],
  [xlabel,"pendulum's length (cm)"], [ylabel, "period (s)"],
  [png_file,"./plotting16.png"]);
