/***************************************
 *
 * This file contains some examples for closed_form function
 *
 * Use:
 *   load("closed_form");
 *   load("closed_form_test");
 *
 ***************************************/

test_sum(s, ass, use_gamma, smp) := block(
  [product_use_gamma : use_gamma, cs, f],
  if length(ass)>0 then apply(assume, ass),
  cs : closed_form(s),
  for f in smp do cs : apply(f, [cs]),
  print("|----------------------------------------------------------|"),
  if length(ass)>0 then print("Assuming:", ass),
  print(s = cs),
  print("|----------------------------------------------------------|"),
  if length(ass)>0 then apply(forget, ass)
  )$

test_sum(
  sum(r/k*binom(n,r)*binom(m,k-r)/binom(n+m,k),r,0,k),
  [n>k, m>k-1],
  true,
  [makefact, minfactorial]
)$

test_sum(
  sum(binom(n,k)/(k+1), k, 0, n),
  [],
  true,
  []
);

test_sum(
  sum((-1)^k * binomial(a+b, a+k) * binomial(b+c, b+k) * binomial(c+a, c+k), k, -a, a),
  [a<b, a<c],
  true,
  [factcomb]
)$

test_sum(
  sum((-1)^k * binom(n,k)*x/(x+k), k, 0, n),
  [],
  true,
  [factcomb]
)$

test_sum(
  sum((-1)^k * binomial(2*n, k)^2, k, 0, 2*n),
  [],
  false,
  []
)$

test_sum(
  sum((binom(3*k+1,k)*binom(3*(n-k),n-k))/(3*k+1), k, 0, n),
  [],
  false,
  []
)$

test_sum(
  sum(binomial(n, k) * binomial(m, r - k), k, 0, r),
  [m>r, n>r],
  true,
  [factcomb]
)$

test_sum(
  sum(binomial(2*n,2*k), k, 0, n),
  [],
  true,
  []
)$

test_sum(
  sum((-1)^k*binom(x-2*k,n-k)*binom(x-k+1,k),k,0,n),
  [x>2*n, x>n-1],
  true,
  []
)$

test_sum(
  sum((-1)^s*binom(2*m, s)^3, s, 0, 2*m),
  [],
  false,
  []
)$

test_sum(
  sum((-1)^k*binom(k,n-k), k, 0, n),
  [],
  true,
  [rectform, trigreduce]
)$

test_sum(
  sum(binom(n,k)^2*binom(3*n+k,2*n), k, -inf, inf),
  [n>0],
  false,
  []
)$

test_sum(
  sum((-1)^k*binom(n-k,k)*2^(n-2*k), k, 0, n),
  [],
  true,
  []
)$

test_sum(
  sum(k*binom(2*n+k,2*k+1), k, 0, 2*n-1),
  [n>0],
  true,
  []
)$

test_sum(
  sum(binom(x,k)*binom(y,k), k, 0, y),
  [x>y],
  true,
  [factcomb]
)$

test_sum(
  sum((-1)^(n-k)*binom(n,k)*binom(k+b,k), k, 0, n),
  [b>0],
  true,
  [factcomb]
)$

test_sum(
  sum(binom(n+k,k)/2^k,k,0,n),
  [],
  true,
  []
)$

test_sum(
  sum((2^(4*k)*binom(2*n-2*k,n-k))/(2*k*(2*k+1)*binom(2*k,k)), k, 1, n),
  [],
  true,
  []
)$

test_sum(
  sum(k^2 * binomial(n, k), k, 1, n),
  [],
  true,
  []
)$

test_sum(
  sum(2^(n-k)*binom(n+k,2*k),k,-inf,inf),
  [n>0],
  true,
  []
)$

test_sum(
  sum(((-1)^k*binom(2*k,k)*binom(n,k))/4^k,k,0,n),
  [],
  true,
  []
)$

test_sum(
  sum((-1)^k*binom(2*k,k)*binom(2*n,k)*binom(4*n-2*k,2*n-k),k,0,2*n),
  [],
  true,
  []
)$
