;;; -*-  Mode: Lisp; Package: Maxima; Syntax: Common-Lisp; Base: 8 -*- ;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;     The data in this file contains enhancments.                    ;;;;;
;;;                                                                    ;;;;;
;;;  Copyright (c) 1984,1987 by William Schelter,University of Texas   ;;;;;
;;;     All rights reserved                                            ;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(in-package "MAXIMA")
;;to do add for other cl implementations.
;(defun remove-type ( l)
;  (sloop for v in l
;	 when (consp v) do (setq v (car v))
;	 when (symbolp v)
;	 do (remprop v
;		     #+ti 'compiler::variable-type
;		     #+kcl 'compiler::cmp-type
;		     #-(or ti kcl) nil
;		     )))

(defvar *macro-file* nil)

#+gcl
(progn 
  (clines "#define MAKE_UNSPECIAL(x) (check_type_symbol(&(x)),(x)->s.s_stype = stp_ordinary, Cnil)")
  (defentry make-unspecial (object) (object "MAKE_UNSPECIAL")))


(defmacro declare-top (&rest decl-specs)
  `(eval-when
    ,(cond (*macro-file*  #+gcl '(compile eval load)
			  #-gcl '(:compile-toplevel :load-toplevel :execute) )
	   (t #+gcl '(eval compile) #-gcl '(:compile-toplevel :execute)))
    ,@(sloop for v in decl-specs
	     unless (member (car v) '(special unspecial)) do nil 
	     else
	     when (eql (car v) 'unspecial)
	     collect `(progn
		       ,@(sloop for w in (cdr v)
				collect #-gcl  `(remprop ',w
						 #-excl 'special
						 #+excl 'excl::.globally-special.)
				#+gcl `(make-unspecial ',w)))
	     else collect `(proclaim ',v))))

;;this list should contain all specials required by runtime or more
;;than one macsyma file, except for some specials declared in the macro
;;files, eg displm

(declaim
 (special
  $% $%% $%EDISPFLAG $%EMODE $%ENUMER $%E_TO_NUMLOG $%IARGS $%PIARGS
  $%RNUM $%RNUM_LIST $ABSBOXCHAR $ACTIVECONTEXTS $ALGEBRAIC $ALGEXACT
  $ALIASES $ARRAYS $ASKEXP $ASSUMESCALAR $BACKSUBST $BERLEFACT
  $BETA_ARGS_SUM_TO_INTEGER $BFTORAT $BFTRUNC $BOTHCASES $BOXCHAR
  $BREAKUP $CAUCHYSUM $CHANGE_FILEDEFAULTS $COMPGRIND $CONTEXT
  $CONTEXTS $CURRENT_LET_RULE_PACKAGE $CURSORDISP $DEBUGMODE
  $DEFAULT_LET_RULE_PACKAGE $DEMOIVRE $DEPENDENCIES $DERIVABBREV
  $DERIVSUBST $DETOUT $DIREC $DISPFLAG $DISPLAY2D $DISPLAYSET
  $DISPLAY_FORMAT_INTERNAL $DOALLMXOPS $DOMAIN $DOMXEXPT $DOMXMXOPS
  $DOMXNCTIMES $DOMXPLUS $DOMXTIMES $DONTFACTOR $DOSCMXOPS
  $DOSCMXPLUS $DOT0NSCSIMP $DOT0SIMP $DOT1SIMP $DOTASSOC
  $DOTCONSTRULES $DOTDISTRIB $DOTEXPTSIMP $DOTIDENT $DOTSCRULES
  $DSKGC $ERFFLAG $ERREXP $ERROR $ERROR_SIZE $ERROR_SYMS $EXPON
  $EXPONENTIALIZE $EXPOP $EXPTDISPFLAG $EXPTISOLATE $EXPTSUBST
  $FACEXPAND $FACTORFLAG $FEATURES $FILE_SEARCH $FILE_STRING_PRINT
  $FILE_TYPES $FLOAT $FLOAT2BF $FLOATFORMAT $FLOATFRAC $FLOATINT
  $FLOATOPTIONS $FLOATPREC $FLOATWIDTH $FORTFLOAT $FORTINDENT
  $FORTSPACES $FPPREC $FPPRINTPREC $FPTRUNC $FUNCTIONS $GAMMALIM $GCD
  $GENINDEX $GENSUMNUM $GLOBALSOLVE $GRADEFS $HALFANGLES $HOMOG_HACK
  $INCHAR $INFEVAL $INFLAG $INTEGRATION_CONSTANT_COUNTER $INTFACLIM
  $ISOLATE_WRT_TIMES $KEEPFLOAT $LABELS $LEFTJUST $LETRAT $LETVARSIMP
  $LET_RULE_PACKAGES $LIFLAG $LINECHAR $LINEDISP $LINENUM $linel
  $LINSOLVEWARN $LINSOLVE_PARAMS $LISPDISP $LISTARITH $LISTCONSTVARS
  $LMXCHAR $LOGARC $LOGCONCOEFFP $LOGEXPAND $LOGNEGINT $LOGNUMER
  $LOGSIMP $M1PBRANCH $MACROEXPANSION $MACROS $MAPERROR $MAPPRINT
  $MATRIX_ELEMENT_ADD $MATRIX_ELEMENT_MULT $MATRIX_ELEMENT_TRANSPOSE
  $MAXAPPLYDEPTH $MAXAPPLYHEIGHT $MAXNEGEX $MAXPOSEX $MAXPRIME
  $MAXTAYORDER $MODE_CHECKP $MODE_CHECK_ERRORP $MODE_CHECK_WARNP
  $MOREWAIT $MULTIPLICITIES $MX0SIMP $MYOPTIONS $NALGFAC $NEGDISTRIB
  $NEGSUMDISPFLAG $NEWFAC $NOLABELS $NOREPEAT $NOUNDISP $NUMER
  $NUMER_PBRANCH $OPERATORS $OPSUBST $OPTIMPREFIX $OPTIONSET $OUTCHAR
  $PAGEPAUSE $PARSEWINDOW $PARTSWITCH $PFEFORMAT $PIECE $POINTBOUND
  $POISLIM $POWERDISP $PREDERROR $PRODHACK $PROGRAMMODE $PROPS
  $RADEXPAND $RATALGDENOM $RATDENOMDIVIDE $RATEPSILON $RATEXPAND
  $RATFAC $RATMX $RATPRINT $RATSIMPEXPONS $RATVARS $RATWEIGHTS
  $RATWTLVL $REALONLY $REFCHECK $RESULTANT $RMXCHAR $ROMBERGABS
  $ROMBERGIT $ROMBERGIT_USED $ROMBERGMIN $ROMBERGTOL $ROOTSCONMODE
  $RULES $SAVEDEF $SAVEFACTORS $SCALARMATRIXP $SETCHECK
  $SETCHECKBREAK $SETVAL $SHOWTIME $SIGNBFLOAT $SIMP $SIMPSUM
  $SOLVEDECOMPOSES $SOLVEEXPLICIT $SOLVEFACTORS $SOLVENULLWARN
  $SOLVERADCAN $SOLVETRIGWARN $SOLVE_INCONSISTENT_ERROR $SPARSE
  $SPECIAL $SQRTDISPFLAG $STARDISP $STORENUM $SUBLIS_APPLY_LAMBDA
  $SUBNUMSIMP $SUBSCRMAP $SUMEXPAND $SUMHACK $SUMSPLITFACT
  $SUPERLOGCON $SUSPEND $TAYLOR_LOGEXPAND
  $TAYLOR_TRUNCATE_POLYNOMIALS $TIMER $TIMER_DEVALUE
  $TO_CALL_LISP_COMPILER $TRACE $TRACE_BREAK_ARG $TRACE_MAX_INDENT
  $TRACE_SAFETY $TRANSBIND $TRANSCOMPILE $TRANSLATE $TRANSRUN
  $TRIGEXPAND $TRIGEXPANDPLUS $TRIGEXPANDTIMES $TRIGINVERSES
  $TRIGSIGN $TR_ARRAY_AS_REF $TR_BOUND_FUNCTION_APPLYP
  $TR_FILE_TTY_MESSAGESP $TR_FLOAT_CAN_BRANCH_COMPLEX
  $TR_FUNCTION_CALL_DEFAULT $TR_GEN_TAGS $TR_NUMER
  $TR_OPTIMIZE_MAX_LOOP $TR_OUTPUT_FILE_DEFAULT
  $TR_PREDICATE_BRAIN_DAMAGE $TR_SEMICOMPILE $TR_STATE_VARS
  $TR_TRUE_NAME_OF_FILE_BEING_TRANSLATED $TR_WARN_BAD_FUNCTION_CALLS
  $TR_WARN_FEXPR $TR_WARN_MEVAL $TR_WARN_MODE $TR_WARN_UNDECLARED
  $TR_WARN_UNDEFINED_VARIABLE $TR_WINDY $TTYINTFUN $TTYINTNUM
  $UNIVERSE $USER_MESFILE $USE_FAST_ARRAYS $VALUES $VECT_CROSS
  $ZEROBERN %E-VAL %P%I %PI-VAL %PI//2 %PI//4 %PI2 &** *$ANY-MODES*
  *ALPHA *CONST* *FNEWVARSW *GCDL* *IN *IN-$BATCHLOAD* *IN-COMPILE*
  *IN-MACSYMA-INDEXER* *IN-TRANSLATE-FILE* *INV* *IRREDS *MIN* *MX*
  *N *OPERS-LIST *OUT *RATWEIGHTS *TR-WARN-BREAK* *TRANSL-BACKTRACE*
  *TRANSL-DEBUG* *TRANSL-FILE-DEBUG* *WARNED-FEXPRS*
  *WARNED-MODE-VARS* *WARNED-UN-DECLARED-VARS* *ZEXPTSIMP? |-1//2|
  -SQRT2//2 -SQRT3//2 |1//2| ADN* AEXPRP ALGFAC* ALGNOTEXACT
  ALIASLIST ALPHA ALPHABET ARRAYS ARYP ASSIGNS ATP ATVARS BAKTRCL
  BFHALF BFMHALF BIGFLOAT%E BIGFLOAT%PI BIGFLOATONE BIGFLOATZERO
  BIGPRIMES BINDLIST BVARS CASEP DEBUG
  DECLARES DEFINED_VARIABLES DEFINTDEBUG DERIVFLAG DERIVLIST
  DERIVSIMP DISPLAYP DN* DOSIMP DSKSETP DUMMY-VARIABLE-OPERATORS
  DUMPING ENVLIST ERRORSW ERRRJFFLAG EVARRP EVP EXPANDFLAG EXPANDP
  EXPRS EXPTRLSW FACTLIST FEATUREL FEXPRERRP FEXPRS FMAPLVL
  FORMS-TO-COMPILE-QUEUE FOURTH%PI FR-FACTOR FUNDEFSIMP GAUSS
  GENERATE-ATAN2 GENPAIRS GENVAR HALF%PI HALF%PI3 HMODULUS
  IMPLICIT-REAL IN-P INFINITESIMALS INFINITIES INRATSIMP INSIDE-MPROG
  INTEGERL ISLINP LEXPRS LIMIT-ANSWERS LIMITP LINEL
  LINELABLE LNORECURSE LOCAL LOCLIST LOW* MAPLP MASTER-MESFILE MDOP
  META-PROP-L META-PROP-P MFEXPRP MINPOLY* MLOCP MM* MODULUS MOPL
  MPLC* MPROGP MPROPLIST MSPECLIST MSPECLIST2 MSUMP MUNBINDP
  NEED-PROG? NEGPRODS NEGSUMS NN* NOEVALARGS NOITEMS NONINTEGERL
  NOUNL NOUNSFLAG OPERS OPERS-LIST OPEXPRP OUTARGS1 OUTARGS2 OUTFILES
  PLUSFLAG PRESERVE-DIRECTION PRODS PUTL RADCANP RADPE RD*
  REAL-INFINITIES REALONLYRATNUM REFCHKL RETURN-MODE RETURNS RULEFCNL
  RULESW SCANMAPP SFINDEX SIGN-IMAG-ERRP SIMPLIMPLUS-PROBLEMS
  SMALLPRIMES SPECIALS SQRT2//2 SQRT3//2 STATE-PDL STRINGDISP SUBSTP
  SUMS TELLRATLIST TIMESINP TIMESP TR-ABORT TR-PROGRET TR-UNIQUE
  TRAMP1$ TRAMP2$ TRAMP3$ TRANSL-FILE TRANSLATE-TIME-EVALABLES TRANSP
  TSTACK TYPEL USER-MESFILE USER-TIMESOFAR VARLIST WFLAG ^DMSG-OFF
  ^DMSG-ON
  $wtlevel $cflength $weightlevels *trunclist $taylordepth
  $maxtaydiff $verbose $psexpand ps-bmt-disrep
  silent-taylor-flag $DEFINE_VARIABLE))

(declaim (declaration splitfile unspecial muzzled no-type genprefix flonum
		      *lexpr *fexpr *expr mapex macros array* object))
