;; -*- Mode: lisp -*-
;;
;; Setup the share-subdirs-list.  This is a list of each subdirectory
;; (basically) of share that contains code that can be run by maxima.
;;
;; A default version is checked in, but configure will update this
;; with the correct values.  The default checked in version is useful
;; if you're doing a lisp-only build without configure.  But configure
;; is the preferred way to build.
(in-package :maxima)

(defun share-subdirs-list ()
  '#.(remove-if-not
      #'stringp
      ;; DO NOT EDIT THIS LIST.  It is automatically
      ;; generated by configure.
      '(
        "affine" \
        "algebra" \
        "algebra/charsets" \
        "algebra/solver" \
        "calculus" \
        "cobyla" \
        "cobyla/ex" \
        "cobyla/lisp" \
        "colnew" \
        "colnew/ex1" \
        "colnew/ex2" \
        "colnew/ex3" \
        "colnew/lisp" \
        "combinatorics" \
        "contrib" \
        "contrib/Grobner" \
        "contrib/Zeilberger" \
        "contrib/altsimp" \
        "contrib/amatrix" \
        "contrib/bitwise" \
        "contrib/boolsimp" \
        "contrib/descriptive" \
        "contrib/diffequations" \
        "contrib/diffequations/tests" \
        "contrib/distrib" \
        "contrib/ezunits" \
        "contrib/finance" \
        "contrib/format" \
        "contrib/fourier_elim" \
        "contrib/fractals" \
        "contrib/fresnel" \
        "contrib/gentran" \
        "contrib/gentran/man" \
        "contrib/gentran/test" \
        "contrib/gf" \
        "contrib/graphs" \
        "contrib/integration" \
        "contrib/levin" \
        "contrib/lurkmathml" \
        "contrib/maximaMathML" \
        "contrib/mcclim" \
        "contrib/namespaces" \
        "contrib/noninteractive" \
        "contrib/nset" \
        "contrib/numericalio" \
        "contrib/pdiff" \
        "contrib/prim" \
        "contrib/rand" \
        "contrib/sarag" \
        "contrib/simplex" \
        "contrib/simplex/Tests" \
        "contrib/solve_rec" \
        "contrib/state" \
        "contrib/stats" \
        "contrib/stringproc" \
        "contrib/unit" \
        "contrib/vector3d" \
        "diff_form" \
        "diffequations" \
        "draw" \
        "dynamics" \
        "hypergeometric" \
        "integequations" \
        "integration" \
        "lapack" \
        "lapack/blas" \
        "lapack/lapack" \
        "lbfgs" \
        "linearalgebra" \
        "macro" \
        "matrix" \
        "minpack" \
        "minpack/ex" \
        "minpack/lisp" \
        "misc" \
        "numeric" \
        "orthopoly" \
        "physics" \
        "simplification" \
        "sym" \
        "tensor" \
        "trigonometry" \
        "utils" \
        "vector" 
	)))
