/* ODE tests - Equations 1-100

  Reference:
    E Kamke, Differentialgleichungen Losungsmethoden und Losungen, 
    Vol 1, Geest & Portig, Leipzig, 1961

*/
/* Don't kill(all); It messes up trigsimp */

/* Print ode number*/
(pn_(n_):=print("Kamke ODE ",n_),true);
true;

/* Need these indentities to check solutions */
besjident(n,x):=bessel_j(n,x)=2*(n-1)*bessel_j(n-1,x)/x-bessel_j(n-2,x);
besjident(n,x):=bessel_j(n,x)=2*(n-1)*bessel_j(n-1,x)/x-bessel_j(n-2,x);
besiident(n,x):=bessel_i(n,x)=-2*(n-1)*bessel_i(n-1,x)/x+bessel_i(n-2,x);
besiident(n,x):=bessel_i(n,x)=-2*(n-1)*bessel_i(n-1,x)/x+bessel_i(n-2,x);
beskident(n,x):=bessel_k(n,x)=2*(n-1)*bessel_k(n-1,x)/x+bessel_k(n-2,x);
beskident(n,x):=bessel_k(n,x)=2*(n-1)*bessel_k(n-1,x)/x+bessel_k(n-2,x);

/*   1 */
(pn_(1),ans:contrib_ode(eqn:'diff(y,x)-(a4*x^4+a3*x^3+a2*x^2+a1*x+a0)^(-1/2),y,x));
[y = 'integrate(1/sqrt(a4*x^4+a3*x^3+a2*x^2+a1*x+a0),x)+%c];
[method,ode_check(eqn,ans[1])];
[linear,0];

/* 2 */
(pn_(2),ans:contrib_ode(eqn:'diff(y,x)+a*y-c*exp(b*x),y,x));
[y = %e^-(a*x)*(c*%e^(b*x+a*x)/(b+a)+%c)];
[method,ode_check(eqn,ans[1])];
[linear,0];

/* 3 */
(pn_(3),ans:contrib_ode(eqn:'diff(y,x)+a*y-b*sin(c*x),y,x));
[y=%e^-(a*x)*(b*%e^(a*x)*(a*sin(c*x)-c*cos(c*x))/(c^2+a^2)+%c)];
[method,ode_check(eqn,ans[1])];
[linear,0];

/* 4 */
(pn_(4),ans:contrib_ode(eqn:'diff(y,x)+2*x*y-x*exp(-x^2),y,x));
[y=(x^2/2+%c)*%e^-x^2];
[method,ode_check(eqn,ans[1])];
[linear,0];


/* 5 */
(pn_(5),ans:contrib_ode(eqn:'diff(y,x)+y*cos(x)-exp(2*x),y,x));
[y=%e^-sin(x)*('integrate(%e^(sin(x)+2*x),x)+%c)];
[method,ode_check(eqn,ans[1])];
[linear,0];

/* 6 */
(pn_(6),ans:contrib_ode(eqn:'diff(y,x)+y*cos(x)-sin(2*x)/2,y,x));
[y=%e^-sin(x)*((sin(x)-1)*%e^sin(x)+%c)];
[method,trigrat(ode_check(eqn,ans[1]))];
[linear,0];

/* 7 */
(pn_(7),ans:contrib_ode(eqn:'diff(y,x)+y*cos(x)-exp(-sin(x)),y,x));
[y = (x+%c)*%e^-sin(x)];
[method,ode_check(eqn,ans[1])];
[linear,0];

/* 8 */
(pn_(8),ans:contrib_ode(eqn: 'diff(y,x) + y*tan(x) - sin(2*x),y,x));
[y = (%c-2*cos(x))/sec(x)];
[method,trigrat(ode_check(eqn,ans[1]))];
[linear,0];

/* 9 */
(pn_(9),ans:contrib_ode(eqn:'diff(y,x)-(sin(log(x))+cos(log(x))+a)*y,y,x));
[y=%c*%e^(x*(sin(log(x))+cos(log(x)))/2+x*(sin(log(x))-cos(log(x)))/2+a*x)];
[method,ode_check(eqn,ans[1])];
[linear,0];

/* 10 */
(pn_(10),ans:contrib_ode(eqn: 'diff(y,x) + 'diff(f(x),x)*y - f(x)*'diff(f(x),x),y,x));
[y=%e^-f(x)*('integrate(f(x)*%e^f(x)*'diff(f(x),x,1),x)+%c)];
[method,ode_check(eqn,ans[1])];
[linear,0];

/* 11 */
(pn_(11),ans:contrib_ode(eqn: 'diff(y,x)  + f(x)*y - g(x),y,x));
[y = %e^-('integrate(f(x),x))*('integrate(g(x)*%e^'integrate(f(x),x),x)+%c)];
[method,ode_check(eqn,ans[1])];
[linear,0];

/* 12 */
(pn_(12),ans:contrib_ode(eqn:'diff(y,x) + y^2 - 1,y,x));
[(log(y+1)-log(y-1))/2=x+%c];
solve(map(exp,2*ans[1]),y);
[y = (%e^(2*x+2*%c)+1)/(%e^(2*x+2*%c)-1)];
[method,ode_check(eqn,%[1])];
[separable,0];

/* 13 - Riccati eqn */
(pn_(13),ans:contrib_ode(eqn:'diff(y,x) + y^2 - a*x - b,y,x));
[[y='diff(%u,x,1)/%u,%u*(a*x+b)-'diff(%u,x,2)=0]];

/* 14 - The constraints need some work 
         want m # -2, rather than m > -2 */
assume(m>-2,a>0);
[m>-2,a>0];
(pn_("14i"),ans:contrib_ode(eqn: 'diff(y,x) + y^2 + a*x^m,y,x));
[y = (sqrt(a)*(%c*bessel_j(-(m+3)/(m+2),2*sqrt(a)*x^(m/2+1)/(m+2))+bessel_j(-(m+1)/(m+2),2*sqrt(a)*x^(m/2+1)/(m+2)))*x^(m/2+1)+%c*bessel_j(-1/(m+2),2*sqrt(a)*x^(m/2+1)/(m+2)))/((bessel_j(1/(m+2),2*sqrt(a)*x^(m/2+1)/(m+2))+%c*bessel_j(-1/(m+2),2*sqrt(a)*x^(m/2+1)/(m+2)))*x)];
forget(m>-2,a>0);
[m>-2,a>0];

assume(m>-2,a<0);
[m>-2,a<0];
(pn_("14ii"),ans:contrib_ode(eqn: 'diff(y,x) + y^2 + a*x^m,y,x));
 [y = -sqrt(-a)*(%c*bessel_k((m+1)/(m+2),2*sqrt(-a)*x^(m/2+1)/(m+2))-bessel_i(-(m+1)/(m+2),2*sqrt(-a)*x^(m/2+1)/(m+2)))*x^(m/2)/(%c*bessel_k(1/(m+2),2*sqrt(-a)*x^(m/2+1)/(m+2))+bessel_i(1/(m+2),2*sqrt(-a)*x^(m/2+1)/(m+2)))];
forget(m>-2,a<0);
[m>-2,a<0];

(m:-2,assume(a > 1/4));
[a>1/4];
(pn_("14iii"),ans:contrib_ode(eqn: 'diff(y,x) + y^2 + a*x^m,y,x));
[ x = %c*%e^-(2*atan((2*x*y-1)/sqrt(4*a-1))/sqrt(4*a-1))];
solve(map(log,ans[1]/%c),y);
[y = -(sqrt(4*a-1)*tan(sqrt(4*a-1)*log(x/%c)/2)-1)/(2*x)];
 solve(map(log,ans[1]/%c),y);
[y = -(sqrt(4*a-1)*tan(sqrt(4*a-1)*log(x/%c)/2)-1)/(2*x)];
[method,trigsimp(ode_check(eqn,%[1]))];
[genhom,0];
(kill(m),forget(a > 1/4));
[a>1/4];

(m:-2,assume(a < 1/4));
[a < 1/4];
(pn_("14iv"),ans:contrib_ode(eqn: 'diff(y,x) + y^2 + a*x^m,y,x));
[x = %c*%e^-(log(-(-2*x*y+sqrt(1-4*a)+1)/(2*x*y+sqrt(1-4*a)-1))/sqrt(1-4*a))];
solve(map(log,ans[1]/%c),y);
[y = ((sqrt(1-4*a)+1)*%e^(sqrt(1-4*a)*log(x/%c))+sqrt(1-4*a)-1)/(2*x*%e^(sqrt(1-4*a)*log(x/%c))-2*x)];
[method,trigsimp(ode_check(eqn,%[1]))];
[genhom,0];  
(kill(m),forget(a < 1/4));
[a < 1/4];

/* 15 This is a Riccati eqn */
(pn_(15),ans:contrib_ode(eqn:'diff(y,x) + y^2 - 2*x^2*y + x^4 -2*x-1,y,x));
[(log(-y+x^2+1)-log(-y+x^2-1)+2*x)/2 = %c];
solve(map(exp,2*ans[1]-2*x),y);
[y = ((x^2-1)*%e^(2*%c-2*x)-x^2-1)/(%e^(2*%c-2*x)-1)];
[method,ode_check(eqn,%[1])];
[lie,0];

/* 16 This is a Riccati eqn */
(pn_(16),ans:contrib_ode(eqn:'diff(y,x) + y^2 +(x*y-1)*f(x),y,x));
[[y='diff(%u,x,1)/%u,-'diff(%u,x,1)*x*f(x)+%u*f(x)-'diff(%u,x,2)=0]];

/* 17 */
(pn_(17),ans:contrib_ode(eqn:'diff(y,x) - y^2 -3*y + 4,y,x));
[-(log(y+4)-log(y-1))/5 = x+%c];
solve(map(exp,ans[1]*5),y);
[y = -(4*%e^(5*x+5*%c)+1)/(%e^(5*x+5*%c)-1)];
[method,ode_check(eqn,%[1])];
[separable,0];

/* 18 */
(pn_(18),ans:contrib_ode(eqn:'diff(y,x)-y^2-x*y-x+1,y,x));
[[y=-'diff(%u,x,1)/%u,-'diff(%u,x,1)*x+%u*(x-1)+'diff(%u,x,2)=0]];

/* 19 */
(pn_(19),ans:contrib_ode(eqn:'diff(y,x) - (y + x)^2,y,x));
[[x=%c-atan(sqrt(%t)),y=-x-sqrt(%t)],[x=atan(sqrt(%t))+%c,y=sqrt(%t)-x]];
solve(ans[1][2],sqrt(%t));
[sqrt(%t) = -y-x];
ans[1][1],%;
x=atan(y+x)+%c;
ans[1]:first(solve(%,y));
y = tan(x-%c)-x;
solve(ans[2][2],sqrt(%t));
[sqrt(%t) = y+x];
ans[2][1],%;
x = atan(y+x)+%c;
ans[2]:first(solve(%,y));
y = tan(x-%c)-x;
[method,trigsimp(ode_check(eqn,ans[1])),trigsimp(ode_check(eqn,ans[1]))];
[lagrange,0,0];

/* 20 */
(pn_(20),ans:contrib_ode(eqn:'diff(y,x)-y^2+(x^2+1)*y-2*x,y,x));
[y = ((x^2+1)*'integrate(%e^(x^3/3+x),x)-%e^(x^3/3+x)+%c*x^2+%c)/('integrate(%e^(x^3/3+x),x)+%c)];
[method,ode_check(eqn,ans[1])];
[riccati,0];

/* 21 */
(pn_(21),ans:contrib_ode(eqn:'diff(y,x)-y^2+y*sin(x)-cos(x),y,x));
 [y = (%e^cos(x)*sin(x)*'integrate(%e^-cos(x),x)+%c*%e^cos(x)*sin(x)-1)/(%e^cos(x)*'integrate(%e^-cos(x),x)+%c*%e^cos(x))];
[method,ode_check(eqn,ans[1])];
[riccati,0];

/* 22 */
(pn_(22),ans:contrib_ode(eqn:'diff(y,x)-y^2-y*sin(2*x)-cos(2*x),y,x));
[[y=-'diff(%u,x,1)/%u,-'diff(%u,x,1)*sin(2*x)+%u*cos(2*x)+'diff(%u,x,2)=0]];

/* 23 */
assume(a>0,b>0);
[a>0,b>0];
(pn_(23),ans:contrib_ode(eqn:'diff(y,x) + a*y^2 - b,y,x));
[-log(-(sqrt(a)*sqrt(b)-a*y)/(a*y+sqrt(a)*sqrt(b)))/(2*sqrt(a)*sqrt(b))=x+%c];
solve(map(exp,2*sqrt(a)*sqrt(b)*ans[1]),y);
[y=sqrt(b)*(%e^(2*sqrt(a)*sqrt(b)*x+2*%c*sqrt(a)*sqrt(b))+1)/(sqrt(a)*(%e^(2*sqrt(a)*sqrt(b)*x+2*%c*sqrt(a)*sqrt(b))-1))];
[method,ode_check(eqn,%[1])];
[separable,0];
forget(a>0,b>0);
[a>0,b>0];

/* 24 */
assume(nu>-2,a>0,b>0);
[nu > -2,a>0,b>0];
(pn_(24),ans:contrib_ode(eqn:'diff(y,x) + a*y^2 - b*x^nu,y,x));
[y = -sqrt(a)*sqrt(b)*(%c*bessel_k((nu+1)/(nu+2),2*sqrt(a)*sqrt(b)*x^(nu/2+1)/(nu+2))-bessel_i(-(nu+1)/(nu+2),2*sqrt(a)*sqrt(b)*x^(nu/2+1)/(nu+2)))*x^(nu/2)/(%c*a*bessel_k(1/(nu+2),2*sqrt(a)*sqrt(b)*x^(nu/2+1)/(nu+2))+a*bessel_i(1/(nu+2),2*sqrt(a)*sqrt(b)*x^(nu/2+1)/(nu+2)))];
method;
riccati;
forget(nu>-2,a>0,b>0);
[nu>-2,a>0,b>0];

/* 25 - This is a Riccati equation */
(pn_(25),ans:contrib_ode(eqn:'diff(y,x)+a*y^2-b*x^(2*nu)-c*x^(nu-1),y,x));
[[y='diff(%u,x,1)/(%u*a),%u*a^2*(b*x^(2*nu)+c*x^(nu-1))-'diff(%u,x,2)*a=0]];
method;
riccati;

/* 26 */
(pn_(26),ans:contrib_ode(eqn:'diff(y,x)-(A*y- a)*(B*y-b),y,x));
[(log(B*y-b)-log(A*y-a))/(A*b-a*B) = x+%c];
solve(map(exp,ans[1]*(A*b-a*B)),y);
[y=(b-a*%e^(-a*B*x+A*b*x-%c*a*B+%c*A*b))/(B-A*%e^(-a*B*x+A*b*x-%c*a*B+%c*A*b))];
[method,ode_check(eqn,%[1])];
[separable,0];

/* 27 */
(pn_(27),ans:contrib_ode(eqn:'diff(y,x) + a*y*(y-x) - 1,y,x));
[y=(sqrt(2)*sqrt(%pi)*a*x*%e^(a*x^2/2)*erf(sqrt(a)*x/sqrt(2))+sqrt(a)*(2*%c*a*x*%e^(a*x^2/2)+2))/(sqrt(2)*sqrt(%pi)*a*%e^(a*x^2/2)*erf(sqrt(a)*x/sqrt(2))+2*%c*a^(3/2)*%e^(a*x^2/2))];
[method,ode_check(eqn,ans[1])];
[riccati,0];

/* 28 */
(pn_(28),ans:contrib_ode(eqn:'diff(y,x)+x*y^2-x^3*y-2*x,y,x));
[[y='diff(%u,x,1)/(%u*x),-'diff(%u,x,1)*(-x^4-1)+2*%u*x^3-'diff(%u,x,2)*x=0]];

/* 29 */
(pn_(29),ans:contrib_ode(eqn:'diff(y,x) - x*y^2 - 3*x*y,y,x));
[-(log(y+3)-log(y))/3 = x^2/2+%c];
solve(map(exp,3*ans[1]),y);
[y = -3*%e^(3*x^2/2+3*%c)/(%e^(3*x^2/2+3*%c)-1)];
[method,ode_check(eqn,%[1])];
[separable,0];

/* 30 */
(pn_(30),ans:contrib_ode(eqn:'diff(y,x)+x^(-a-1)*y^2-x^a,y,x));
[[y='diff(%u,x,1)*x^(a+1)/%u,%u*x^(a+2*(-a-1))-'diff(%u,x,2)*x^(-a-1)+'diff(%u,x,1)*(-a-1)*x^(-a-2)=0]];

/* 31 */
assume(n>-1);
[n>-1];
(pn_(31),ans:contrib_ode(eqn:'diff(y,x) - a*x^n*(y^2+1),y,x));
[atan(y)/a = x^(n+1)/(n+1)+%c];
solve(ans[1],y);
[y = tan(a*x^(n+1)/(n+1)+%c*a*n/(n+1)+%c*a/(n+1))];
[method,trigsimp(ode_check(eqn,%[1]))];
[separable,0];
forget(n>-1);
[n>-1];

/* 32 - Why the %i in the solution? */
(pn_(32),ans:contrib_ode(eqn:'diff(y,x) + y^2*sin(x) - 2*sin(x)/cos(x)^2,y,x));
[y = ((3*%c-%i)*sinh(3*log(cos(x))/2)+(%c-3*%i)*cosh(3*log(cos(x))/2))/(2*%i*cos(x)*sinh(3*log(cos(x))/2)-2*%c*cos(x)*cosh(3*log(cos(x))/2))];
[method,ode_check(eqn,ans[1])];
[riccati,0];

/* 33 */
(pn_(33),ans:contrib_ode(eqn:'diff(y,x)-y^2*'diff(f(x),x)/g(x)+'diff(g(x),x)/f(x),y,x));
[[y = -'diff(%u,x,1)*g(x)/(%u*'diff(f(x),x,1)),-'diff(%u,x,1)*('diff(f(x),x,2)/g(x)-'diff(f(x),x,1)*'diff(g(x),x,1)/g(x)^2)-%u*('diff(f(x),x,1))^2*'diff(g(x),x,1)/(f(x)*g(x)^2)+'diff(%u,x,2)*'diff(f(x),x,1)/g(x)=0]];
method;
riccati;

/* 34 */
(pn_(34),ans:contrib_ode(eqn:'diff(y,x)+f(x)*y^2+g(x)*y,y,x));
[y=%e^-('integrate(g(x),x))/('integrate(f(x)*%e^-'integrate(g(x),x),x)+%c)];
[method,ode_check(eqn,ans[1])];
[bernoulli,0];

/* 35 */
assume(4*a^2>4*b);
[4*a^2>4*b];
(pn_(35),ans:contrib_ode(eqn:'diff(y,x)+f(x)*(y^2+2*a*y+b),y,x));
[-log(-(-y+sqrt(a^2-b)-a)/(y+sqrt(a^2-b)+a))/(2*sqrt(a^2-b))='integrate(f(x),x)+%c];
solve(map(exp,2*sqrt(a^2-b)*ans[1]),y);
[y=(sqrt(a^2-b)*(%e^(2*sqrt(a^2-b)*'integrate(f(x),x)+2*%c*sqrt(a^2-b))+1)+a*(1-%e^(2*sqrt(a^2-b)*'integrate(f(x),x)+2*%c*sqrt(a^2-b))))/(%e^(2*sqrt(a^2-b)*'integrate(f(x),x)+2*%c*sqrt(a^2-b))-1)];
[method,ode_check(eqn,%[1])];
[separable,0];
forget(4*a^2>4*b);
[4*a^2>4*b];

/* 36 */
(pn_(36),ans:contrib_ode(eqn:'diff(y,x) + y^3 + a*x*y^2,y,x));
false;

/* 37 */
(pn_(37),ans:contrib_ode(eqn:'diff(y,x)-y^3-a*exp(x)*y^2,y,x));
false;

/* Kamke 38 - Chini invariant constant - 1/(8*a*b^2) 

   One integrable case is a:-1/6  b:1/3
*/
(pn_(38),a:-1/6,b:1/3,ans:contrib_ode(eqn:'diff(y,x) - a*y^3 - b*x^(-3/2),y,x));
[x = %c*%e^((sqrt(x)*(2*y*log(sqrt(x)*y+1)-2*y*log(sqrt(x)*y-2))+2*log(sqrt(x)*y+1)-2*log(sqrt(x)*y-2)-6)/(3*sqrt(x)*y+3))];
method;
genhom;
kill(a,b);
done;

/* 39 */
(pn_(39),ans:contrib_ode(eqn:'diff(y,x)-a3*y^3-a2*y^2-a1*y-a0,y,x));
['integrate(1/(a3*y^3+a2*y^2+a1*y+a0),y)=x+%c];

/* 40 */
(pn_(40),ans:contrib_ode(eqn:'diff(y,x)+3*a*y^3+6*a*x*y^2,y,x));
false;

/* 41 */
assume(b^2+4*a>0);
[b^2+4*a>0];
(pn_(41),ans:contrib_ode(eqn:'diff(y,x)+a*x*y^3+b*y^2,y,x));
[x=%c*%e^-((b*log(-(-2*a*x*y+sqrt(b^2+4*a)-b)/(2*a*x*y+sqrt(b^2+4*a)+b))+sqrt(b^2+4*a)*(log(a*x^2*y^2+b*x*y-1)-2*log(x*y)))/(2*sqrt(b^2+4*a)))];
method;
genhom;
forget(b^2+4*a>0);
[b^2+4*a>0];

/* 42 */
(pn_(42),ans:contrib_ode(eqn:'diff(y,x)-x*(x+2)*y^3-(x+3)*y^2,y,x));
false;

/* 43 - runs "forever" */

/* 44 */
(pn_(44),ans:contrib_ode(eqn:'diff(y,x)+2*a*x^3*y^3+2*x*y,y,x));
[y=%e^-x^2/sqrt(%c-a*(2*x^2+1)*%e^-(2*x^2)/2)];
[method,ode_check(eqn,ans[1])];
[bernoulli,0];

/* 45 */
(pn_(45),ans:contrib_ode(eqn:'diff(y,x)+2*(a^2*x^3-b^2*x)*y^3+3*b*y^2,y,x));
false;

/* 46 Abel eqn with relative invariant = 0 */
(kn_("46i"),a:1,ans:contrib_ode(eqn:'diff(y,x)- x^a*y^3+3*y^2-x^(-a)*y-x^(-2*a)+ a*x^(-a-1),y,x));
[x = %c*%e^-((2*log(x*y-1)-log(x*y-2)-log(x*y))/2)];
/* This doesn't work.  Bug is ode_check??  ***FIXME***
[method,ode_check(eqn,ans[1])];
[genhom,0]; */
radcan(ans[1])^2;
x^2 = %c^2*x*y*(x*y-2)/(x*y-1)^2;
ans:solve(%,y);
[y = (%c*sqrt(%c^2-x^2)+x^2-%c^2)/(x^3-%c^2*x), y = -(%c*sqrt(%c^2-x^2)-x^2+%c^2)/(x^3-%c^2*x)];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[genhom,0,0];
kill(a);
done;

(pn_("46ii"),assume(a>1),ans:contrib_ode(eqn:'diff(y,x) - x^a*y^3 + 3*y^2 - x^(-a)*y -x^(-2*a) + a*x^(-a-1),y,x));
[y = %e^-(2*x^(1-a)/(1-a))/sqrt(%c-2*'integrate(x^a*%e^-(4*x^(1-a)/(1-a)),x))+1/x^a];
[method,ode_check(eqn,ans[1])];
[abel,0];
forget(a>1);
[a>1];

/* 47 - Too general */

/* 48 - Too general */


/* 53 */


(kill(besjident,besiident,beskident),done);
done;
