/* ODE tests 

  Reference: 
    G M Murphy, Ordinary Differential Equations and Their 
    Solutions, Van Nostrand, 1960, pp 15-23

    First Order and Second or Higher Degree, p278 ff
*/

/* Don't kill(all); It messes up trigsimp */

(load('contrib_ode),put('contrib_ode,true,'verbose),done);
done;
(load('pdiff),use_pdiff:false);
false;

/* Eliminate parameter t from singular solution */
(elim_(ans,x,y,t):=block([s],s:first(solve(ans[2],t)),s:solve(ev(ans[1],s),y),s[1]),done);
done;

/* Print ode number*/
(pn_(n_):=print("ODE ",n_),true);
true;

/* 1 */
assume(not(equal(n,-2)));
[not(equal(n, -2))];
(pn_(1),ans:contrib_ode(eqn:'diff(y,x)^2=a*x^n,y,x));
[-((n+2)*y+2*x*sqrt(a*x^n))/(n+2)=%c];
solve(ans[1],y); 
[y=-(2*x*sqrt(a*x^n)+%c*n+2*%c)/(n+2)];
[method,ode_check(eqn,%[1])];
[lie,0];
forget(not(equal(n,-2)));
'[not(equal(n,-2))];

/* 2 */
(pn_(2),ans:contrib_ode(eqn:'diff(y,x)^2=y,y,x));
[4*y-x^2+2*%C*x-%C^2=0];
solve(ans[1],y);
[y=(x^2-2*%C*x+%C^2)/4];
[method,ode_check(eqn,%[1])];
[lagrange,0];

/* 3 */
(pn_(3),ans:contrib_ode(eqn:'diff(y,x)^2=x-y,y,x));
[[x=%c-2*(log(%t-1)+%t),y=x-%t^2]]; /* Correct */
method;
lagrange;

/* 4 Very long "answer" from ode1_lie */
/* (pn_(4),ans:contrib_ode(eqn:'diff(y,x)^2=x^2+y,y,x)); */

/* 5 Very long "answer" from ode1_lie */
/* (pn_(5),ans:contrib_ode(eqn:'diff(y,x)^2+x^2=4*y,y,x)); */

/* 6 Very long "answer" from ode1_lie */
/* (pn_(6),ans:contrib_ode(eqn:'diff(y,x)^2+3*x^2=8*y,y,x)); */

/* 7 ode1_lie takes forever */
/* (pn_(7),ans:contrib_ode(eqn:'diff(y,x)^2+a*x^2+b*y=0,y,x)); */

/* 8 */ /* CHECKME */
(pn_(8),ans:contrib_ode(eqn:'diff(y,x)^2=1+y^2,y,x));
[[x=%c-log(2*sqrt(%t^2-1)+2*%t),y=-sqrt(%t^2-1)],[x=log(2*sqrt(%t^2-1)+2*%t)+%c,y=sqrt(%t^2-1)]];
method;
lagrange;

/* 9 */
(pn_(9),ans:contrib_ode(eqn:'diff(y,x)^2=1-y^2,y,x));
[[x = asin(%t)+%c,y = -sqrt(1-%t^2)],[x=%c-asin(%t),y=sqrt(1-%t^2)]];
solve(ans[1][1],%t);
[%t = sin(x-%c)];
ans:ans[1][2],%;
y = -sqrt(1-sin(x-%c)^2); /* y = sin(x+%c) */
[method,trigsimp(ode_check(eqn,ans))];
[lagrange,0];
/* ans[2] has %c -> -%c */
/* Other solutions y=1, y=-1 */

/* 10 */
(pn_(10),ans:contrib_ode(eqn:'diff(y,x)^2=a^2-y^2,y,x));
[[x=asin(%t/abs(a))+%c,y=-sqrt(a^2-%t^2)],[x=%c-asin(%t/abs(a)),y=sqrt(a^2-%t^2)]];
solve(ans[1][1],%t);
[%t = abs(a)*sin(x-%c)];
ans:ans[1][2],%;
y=-sqrt(a^2-a^2*sin(x-%c)^2);
[method,trigsimp(ode_check(eqn,ans))];
[lagrange,0];
/* Solutions in Murphy are
     y=(a*(1-%c^2)*sin(x)+2*%c*a*cos(x))/(1+%c^2))
     y+a*sin(x)=0
     y=a, y=-a
*/

/* 11 */
(pn_(11),ans:contrib_ode(eqn:'diff(y,x)^2=a^2*y^2,y,x));
[y = %c*%e^(a*x),y = %c*%e^-(a*x)];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[factor,0,0];

/* 12 */
assume(a>0,b>0);
[a>0,b>0];
(pn_(12),ans:contrib_ode(eqn:'diff(y,x)^2=a+b*y^2,y,x));
[[x=%c-log(2*sqrt(%t^2-a)+2*%t)/sqrt(b),y=-sqrt(%t^2-a)/sqrt(b)],[x=log(2*sqrt(%t^2-a)+2*%t)/sqrt(b)+%c,y=sqrt(%t^2-a)/sqrt(b)]]; /* CHECKME */
method;
lagrange;
forget(a>0,b>0);
[a>0,b>0];

/* 13 */
(pn_(13),ans:contrib_ode(eqn:'diff(y,x)^2=x^2*y^2,y,x));
[y = %c*%e^(x^2/2),y = %c*%e^-(x^2/2)];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[factor,0,0];

/* 14 FIXME: crashes ode1_lagrange */
/* (pn_(14),ans:contrib_ode(eqn:'diff(y,x)^2=(y-1)*y^2,y,x)); */

/* 15 ode1_lagrange takes "forever" */
/* (pn_(15),ans:contrib_ode(eqn:'diff(y,x)^2=(y-a)*(y-b)*(y-c),y,x)); */

/* 16 ode1_lagrange returns a "solution" */
/* (pn_(16),ans:contrib_ode(eqn:'diff(y,x)^2=a^2*y^n,y,x)); */

/* 17 ode1_lie crashes */
/* (pn_(17),ans:contrib_ode(eqn:'diff(y,x)^2=a^2*(1-log(y)^2)*y^2,y,x)); */

/* 18 to 24 are very (too?) general */

/* 25 */
(pn_(25),ans:contrib_ode(eqn:'diff(y,x)^2+2*'diff(y,x)+x=0,y,x));
[-(3*y+SQRT(1-x)*(2*x-2)+3*x)/3 = %C];
solve(ans[1],y);
[y = -((2*SQRT(1-x)+3)*x-2*SQRT(1-x)+3*%C)/3];
[method,ode_check(eqn,%)];
[lie,0];

/* 26 */
(pn_(26),ans:contrib_ode(eqn:'diff(y,x)^2-2*'diff(y,x)+a*(x-y)=0,y,x));
[-(4*sqrt(a*y-a*x+1)+2*a*x-4)/(sqrt(2)*sqrt(3)*sqrt(-a)) = %c];
solve(ans[1],sqrt(a*y-a*x+1));
[sqrt(a*y-a*x+1) = -(2*a*x+sqrt(2)*sqrt(3)*%c*sqrt(-a)-4)/4];
%[1]^2;
a*y-a*x+1 = (2*a*x+sqrt(2)*sqrt(3)*%c*sqrt(-a)-4)^2/16;
solve(%,y);
[y = (2*a^2*x^2+2*sqrt(2)*sqrt(3)*%c*sqrt(-a)*a*x-3*%c^2*a-4*sqrt(2)*sqrt(3)*%c*sqrt(-a))/(8*a)];
[method,ode_check(eqn,%[1])];
[lie,0];
/* Murphy gives a*(C+x)^2=4*(C+y), a*y=1+a*x */

/* 27 */
(pn_(27),ans:contrib_ode(eqn:'diff(y,x)^2-2*'diff(y,x)-y^2=0,y,x));
[[x=-log(2*sqrt(%t^2-2*%t)+2*%t-2)+sqrt(%t^2-2*%t)/%t+%c,y=-sqrt(%t^2-2*%t)],[x=log(2*sqrt(%t^2-2*%t)+2*%t-2)-sqrt(%t^2-2*%t)/%t+%c,y=sqrt(%t^2-2*%t)]];
method; /* CHECKME */
lagrange;

/* 28 */
(pn_(28),ans:contrib_ode(eqn:'diff(y,x)^2-5*'diff(y,x)+6=0,y,x));
[y=3*x+%c,y=2*x+%c];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[factor,0,0];

/* 29 */
(pn_(29),ans:contrib_ode(eqn:'diff(y,x)^2-7*'diff(y,x)+12=0,y,x));
[y=4*x+%c,y=3*x+%c];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[factor,0,0];


/* 30 */
(pn_(30),ans:contrib_ode(eqn:'diff(y,x)^2+a*'diff(y,x)+b=0,y,x));
[-(2*y+SQRT(a^2-4*b)*x+a*x)/2 = %C];
solve(ans[1],y);
[y = -((SQRT(a^2-4*b)+a)*x+2*%C)/2];
[method,ode_check(eqn,%)];
[lie,0];

/* 31 */
(pn_(31),ans:contrib_ode(eqn:'diff(y,x)^2+a*'diff(y,x)+b*x=0,y,x));
[-(12*b*y+SQRT(a^2-4*b*x)*(4*b*x-a^2)+6*a*b*x)/(12*b) = %C];
solve(ans[1],y);
[y = -(SQRT(a^2-4*b*x)*(4*b*x-a^2)+6*a*b*x+12*%C*b)/(12*b)];
[method,ode_check(eqn,%)];
[lie,0];

/* 32 */
(pn_(32),ans:contrib_ode(eqn:'diff(y,x)^2+a*'diff(y,x)+b*y=0,y,x));
[[x=%c-(log(%t)*a+2*%t)/b,y = -(%t*a+%t^2)/b]]; /* Correct */
method;
lagrange;

/* 33 */
(pn_(33),ans:contrib_ode(eqn:'diff(y,x)^2+x*'diff(y,x)+1=0,y,x));
[-(4*y-4*log(2*sqrt(x^2-4)+2*x)+x*sqrt(x^2-4)+x^2)/4=%c];
solve(ans[1],y);
[y=(4*log(2*sqrt(x^2-4)+2*x)-x*sqrt(x^2-4)-x^2-4*%c)/4];
[method,ode_check(eqn,%)];
[lie,0];

/* 34 */
(pn_(34),ans:contrib_ode(eqn:'diff(y,x)^2+x*'diff(y,x)-y=0,y,x));
[y=%C*x+%C^2,y=-x^2/4];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[clairault,0,0];

/* 35 */
(pn_(35),ans:contrib_ode(eqn:'diff(y,x)^2-x*'diff(y,x)+y=0,y,x));
[y=%C*x-%C^2,y=x^2/4];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[clairault,0,0];

/* 36 */
(pn_(36),ans:contrib_ode(eqn:'diff(y,x)^2-x*'diff(y,x)-y=0,y,x));
[[x=%e^-(log(%t)/2)*(2*%e^(3*log(%t)/2)/3+%c),y=%t^2-%t*x]];
ans:radcan(%);
[[x=(2*%t^(3/2)+3*%c)/(3*sqrt(%t)),y=%t^2-%t*x]];
ans:ans,3*%c=%c; /* change constant */
[[x=(2*%t^(3/2)+%c)/(3*sqrt(%t)),y=%t^2-%t*x]];
ans[1][2]:ans[1][2],ans[1][1];
y=%t^2-sqrt(%t)*(2*%t^(3/2)+%c)/3;
expand(3*ans);
[[3*x = 2*%t+%c/sqrt(%t),3*y = %t^2-%c*sqrt(%t)]];  /* correct */
method;
lagrange;

/* 37 */
(pn_(37),ans:contrib_ode(eqn:'diff(y,x)^2+x*'diff(y,x)+x-y=0,y,x));
[[x=%e^-%t*(%c-2*(%t-1)*%e^%t),y = (%t+1)*x+%t^2]];
ans[1][2]:ans[1][2],ans[1][1];
y=(%t+1)*%e^-%t*(%c-2*(%t-1)*%e^%t)+%t^2;
expand(ans);
[[x=%c*%e^-%t-2*%t+2,y=%c*%t*%e^-%t+%c*%e^-%t-%t^2+2]]; /* correct */
method;
lagrange;

/* 38 */
(pn_(38),ans:contrib_ode(eqn:'diff(y,x)^2+(1-x)*'diff(y,x)+y=0,y,x));
[y=%C*x-%C-%C^2,y=(x^2-2*x+1)/4];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[clairault,0,0];

/* 39 */
(pn_(39),ans:contrib_ode(eqn:'diff(y,x)^2-(1+x)*'diff(y,x)+y=0,y,x));
[y=%C*x-%C^2+%C,y=(x^2+2*x+1)/4];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[clairault,0,0];

/* 40 */
(pn_(40),ans:contrib_ode(eqn:'diff(y,x)^2-(2-x)*'diff(y,x)+1-y=0,y,x));
[y=%C*x+%C^2-2*%C+1,y=-(x^2-4*x)/4];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[clairault,0,0];

/* 41 */
(pn_(41),ans:contrib_ode(eqn:'diff(y,x)^2+(a+x)*'diff(y,x)-y=0,y,x));
[y=%C*x+%C*a+%C^2,y=-(x^2+2*a*x+a^2)/4];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[clairault,0,0];

/* 42 */
(pn_(42),ans:contrib_ode(eqn:'diff(y,x)^2-2*x*'diff(y,x)+1=0,y,x));
[-(2*y-log(2*sqrt(x^2-1)+2*x)+x*sqrt(x^2-1)-x^2)/2=%c];
solve(ans[1],y);
[y=(log(2*sqrt(x^2-1)+2*x)-x*sqrt(x^2-1)+x^2-2*%c)/2];
[method,ode_check(eqn,%)];
[lie,0];

/* 43 */
(pn_(43),ans:contrib_ode(eqn:'diff(y,x)^2+2*x*'diff(y,x)-3*x^2=0,y,x));
[y = x^2/2+%C,y = %C-3*x^2/2];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[FACTOR,0,0];

/* 44 */
(pn_(44),ans:contrib_ode(eqn:'diff(y,x)^2*x*'diff(y,x)-y=0,y,x));
[[x = %c*%e^-(3*log(%t^2-1)/2),y = %t^3*x]]; /* Parametric soln */
first(solve(ans[1][1]^2,%t));
%t=-sqrt(x^(2/3)+%c^(2/3))/x^(1/3);
ans:ev(ans[1][2],%);
y=-(x^(2/3)+%C^(2/3))^(3/2);
[method,ode_check(eqn,ans)];
[lagrange,0];

/* 45 */
(pn_(45),ans:contrib_ode(eqn:'diff(y,x)^2+2*x*diff(y,x)-y=0,y,x));
[4*y-x^2+2*%C*x-%C^2=0];
ans:solve(ans[1],y);
[y = (x^2-2*%C*x+%C^2)/4];
[method,ode_check(eqn,ans[1])];
[lagrange,0];

/* 46 */
(pn_(46),ans:contrib_ode(eqn:'diff(y,x)^2-2*x*'diff(y,x)+2*y=0,y,x));
[y=(2*%C*x-%C^2)/2,y=x^2/2];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[clairault,0,0];

/* 47 CHECKME */
(pn_(47),ans:contrib_ode(eqn:'diff(y,x)^2+(1+2*x)*diff(y,x)-x*(1-x)=0,y,x));
[-(8*y+ASIN(2*x-1)+(4*x-2)*SQRT(x-x^2))/8 = %C];
solve(ans[1],y);
[y = -(ASIN(2*x-1)+(4*x-2)*SQRT(x-x^2)+8*%C)/8];
[method,ode_check(eqn,%)];
[lie,-(16*x^4-32*x^3+SQRT(4*x-4*x^2)*SQRT(x-x^2)*(8*x^2-8*x+1)+18*x^2-2*x)/(64*x^4-128*x^3+64*x^2)];

/* 48 */
(pn_(48),ans:contrib_ode(eqn:'diff(y,x)^2+(1-x)*diff(y,x)-2*(x-y)=0,y,x));
[-(2*sqrt(x-y)-sqrt(2)*log(sqrt(2)*sqrt(x-y)+1)-sqrt(2)*x)/sqrt(2)=%c];
method;
lie;

/* 49 */
(pn_(49),ans:contrib_ode(eqn:'diff(y,x)^2+3*x*'diff(y,x)-y=0,y,x));
[[x = %e^-(3*log(%t)/2)*(%c-2*%e^(5*log(%t)/2)/5),y = 3*%t*x+%t^2]]; /* CHECKME */
method;
lagrange;

/* 50 */
(pn_(50),ans:contrib_ode(eqn:'diff(y,x)^2-4*(1+x)*'diff(y,x)+4*y=0,y,x));
[y=(4*%C*x-%C^2+4*%C)/4,y=x^2+2*x+1];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[clairault,0,0];

/* 51 */
assume(4*c+a^2>0,b>0);
[4*c+a^2 > 0,b > 0];
(pn_(51),ans:contrib_ode(eqn:'diff(y,x)^2+a*x*'diff(y,x)=b+c*x^2,y,x));
[-(SQRT(4*c+a^2)*(4*y+a*x^2)+4*b*ASINH(SQRT(4*c+a^2)*x/(2*SQRT(b)))+SQRT(4*c+a^2)*x*SQRT((4*c+a^2)*x^2+4*b))/(4*SQRT(4*c+a^2))=%C];
solve(ans[1],y);
[y = -(4*b*ASINH(SQRT(4*c+a^2)*x/(2*SQRT(b)))+SQRT(4*c+a^2)*x*SQRT(4*c*x^2+a^2*x^2+4*b)+a*SQRT(4*c+a^2)*x^2+4*%C*SQRT(4*c+a^2))/(4*SQRT(4*c+a^2))];
[method,ode_check(eqn,%[1])];
[lie,0];
forget(4*c+a^2>0,b>0);
[4*c+a^2>0,b>0];

/* 52 */
(pn_(52),ans:contrib_ode(eqn:'diff(y,x)^2-a*x*'diff(y,x)+a*y=0,y,x));
[y=(%C*a*x-%C^2)/a,y=a*x^2/4];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[clairault,0,0];

/* 53 ode1_lie takes forever */
/* (pn_(53),ans:contrib_ode(eqn:'diff(y,x)^2+a*x*'diff(y,x)+b*x^2+c*y=0,y,x));*/

/* 54 */
(pn_(54),ans:contrib_ode(eqn:'diff(y,x)^2+(a+b*x)*'diff(y,x)+c=b*y,y,x));
[y=(%C*b*x+c+%C*a+%C^2)/b,y=-(b^2*x^2+2*a*b*x-4*c+a^2)/(4*b)];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[clairault,0,0];

/* 55 ode1_lie takes forever */
/*(pn_(55),ans:contrib_ode(eqn:'diff(y,x)^2-2*x^2*'diff(y,x)+2*x*y=0,y,x));*/

/* 56 ode1_lie takes forever */
/*(pn_(56),ans:contrib_ode(eqn:'diff(y,x)^2-a*x^2*'diff(y,x)+b*x*y=0,y,x));*/

/* 57 */
(pn_(57),ans:contrib_ode(eqn:'diff(y,x)^2-a*x^3*'diff(y,x)+2*a*x^2*y=0,y,x));
[-(sqrt(a)*sqrt(a^2*x^4-8*a*y)-a^(3/2)*x^2)/(sqrt(3)*a) = %c];
solve(ans[1],sqrt(a^2*x^4-8*a*y));
[sqrt(a^2*x^4-8*a*y) = (a^(3/2)*x^2-sqrt(3)*%c*a)/sqrt(a)];
%[1]^2;
a^2*x^4-8*a*y = (a^(3/2)*x^2-sqrt(3)*%c*a)^2/a;
ans:solve(%,y);
[y=(2*sqrt(3)*%c*a^(5/2)*x^2-3*%C^2*a^2)/(8*a^2)];
[method,ode_check(eqn,ans[1])];
[lie,0];

/* 58 ode1_lie takes forever */
/* (pn_(58),ans:contrib_ode(eqn:'diff(y,x)^2-a*x^3*'diff(y,x)+4*a*x^2*y=0,y,x));*/

/* 59 */
(pn_(59),ans:contrib_ode(eqn:'diff(y,x)^2+4*x^5*'diff(y,x)-12*x^4*y=0,y,x));
[(4*%i*sqrt(3*y+x^6)+4*%i*x^3)/(3*sqrt(2)) = %c];
ans[1]/%i,%c=%i*%c;
-%i*(4*%i*sqrt(3*y+x^6)+4*%i*x^3)/(3*sqrt(2)) = %c;
expand(%);
4*sqrt(3*y+x^6)/(3*sqrt(2))+4*x^3/(3*sqrt(2)) = %c;
solve(%,sqrt(3*y+x^6));
[sqrt(3*y+x^6) = -(4*x^3-3*sqrt(2)*%c)/4];
%[1]^2;
3*y+x^6 = (4*x^3-3*sqrt(2)*%c)^2/16;
ans:solve(%,y);
[y = -(4*sqrt(2)*%c*x^3-3*%c^2)/8];
[method,ode_check(eqn,ans[1])];
[lie,0];

/* 60 */
(pn_(60),ans:contrib_ode(eqn:'diff(y,x)^2+2*'diff(y,x)*cosh(x)+1=0,y,x));
[-%e^-x*(2*%e^x*y+2*%e^x*sinh(x)+%e^(2*x)+1)/2 = %c];
solve(ans[1],y);
[y = -%e^-x*(2*%e^x*sinh(x)+%e^(2*x)+2*%c*%e^x+1)/2];
expand(ev(%[1],sinh(x)=1/2*(exp(x)-exp(-x))));
y=-%e^x-%c;
ode_check(eqn,%);
-2*%e^x*cosh(x)+%e^(2*x)+1;
expand(ev(%,cosh(x)=1/2*(exp(x)+exp(-x))));
0;
method;
lie;

/* 61 */
(pn_(61),ans:contrib_ode(eqn:'diff(y,x)^2+y*'diff(y,x)=x*(x+y),y,x));
[y = x^2/2+%C,y = %E^-x*(%C-(x-1)*%E^x)];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[FACTOR,0,0];

/* 62 */
(pn_(62),ans:contrib_ode(eqn:'diff(y,x)^2-y*'diff(y,x)+exp(x)=0,y,x));
[2*log(sqrt(y^2-4*%e^x)+y)=%c];
map(exp,ans[1]/2);
sqrt(y^2-4*%e^x)+y=%e^(%c/2);
%,exp(%c/2)=%c;
sqrt(y^2-4*%e^x)+y=%c;
(%-y)^2;
y^2-4*%e^x=(%c-y)^2;
solve(expand(%),y);
[y=(4*%e^x+%c^2)/(2*%c)];
[method,ode_check(eqn,%[1])];
[lie,0];
/* FIXME? y=2*sqrt(exp(x)) and y=-2*sqrt(exp(x)) are singular solutions */

/* 63 */
(pn_(63),ans:contrib_ode(eqn:'diff(y,x)^2+(x+y)*'diff(y,x)+x*y=0,y,x));
[y = %C-x^2/2,y = %C*%E^-x];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[factor,0,0];

/* [[x = %c-log(%t),y = -%t]];
ans[1][1],solve(ans[1][2],%t);
x=%c-log(-y);
solve(%,y);
[y=-%e^(%c-x)];
[method,ode_check(eqn,%[1])];
[lagrange,0]; */
/* FIXME: y=(%c-x^2)/2 also a solution */

/* 64 */
(pn_(64),ans:contrib_ode(eqn:'diff(y,x)^2+2*y*'diff(y,x)-2*x=0,y,x));
false;

/* 65 */
(pn_(65),ans:contrib_ode(eqn:'diff(y,x)^2+(1+2*y)*'diff(y,x)+y*(y-1)=0,y,x));
[[x=(4*log(sqrt(1-8*%t)-1)-12*log(sqrt(1-8*%t)+1))/4+%c,y=-(2*%t+sqrt(1-8*%t)-1)/2],[x=(4*log(sqrt(1-8*%t)+1)-12*log(sqrt(1-8*%t)-1))/4+%c,y=(-2*%t+sqrt(1-8*%t)+1)/2]];
method;
lagrange;
/* CHECKME */

/* 66 */
(pn_(66),ans:contrib_ode(eqn:'diff(y,x)^2-2*(x-y)*'diff(y,x)-4*x*y=0,y,x));
[y=x^2+%c,y=%c*%e^-(2*x)];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[factor,0,0];

/* 67 */
(pn_(67),ans:contrib_ode(eqn:'diff(y,x)^2-(1+4*y)*'diff(y,x)-(1+4*y)*y=0,y,x));
[[x=%c-(-asinh(%t/abs(%t)-1/(4*abs(%t)))+2*asinh((64*%t-8)/8)/sqrt(2)+log(%t))/2,y=-(sqrt(32*%t^2-8*%t+1)+4*%t+1)/8],[x=%c-(asinh(%t/abs(%t)-1/(4*abs(%t)))-2*asinh((64*%t-8)/8)/sqrt(2)+log(%t))/2,y = (sqrt(32*%t^2-8*%t+1)-4*%t-1)/8]];
method;
lagrange;
/* CHECKME */

/* 68 */
(pn_(68),ans:contrib_ode(eqn:'diff(y,x)^2-2*(1-3*y)*'diff(y,x)-(4-9*y)*y=0,y,x));
[[x=%c-(3*log((2*sqrt(3*%t+2)-2*sqrt(2))/(2*sqrt(3*%t+2)+2*sqrt(2)))/2+3*log(3*%t))/9,y=-(sqrt(2)*sqrt(3*%t+2)+3*%t-2)/9],[x=%c-(3*log(3*%t)-3*log((2*sqrt(3*%t+2)-2*sqrt(2))/(2*sqrt(3*%t+2)+2*sqrt(2)))/2)/9,y=(sqrt(2)*sqrt(3*%t+2)-3*%t+2)/9]];
method;
lagrange;
/* CHECKME */

/* 69 ode1_lie takes forever */
/*(pn_(69),ans:contrib_ode(eqn:'diff(y,x)^2-(a+6*y)*'diff(y,x)+y(3*a+b+9*y)=0,y,x));*/

/* 70 */
(pn_(70),ans:contrib_ode(eqn:'diff(y,x)^2+a*y*'diff(y,x)-a*x=0,y,x));
false;

/* 71 */
(pn_(71),ans:contrib_ode(eqn:'diff(y,x)^2-a*y*'diff(y,x)-a*x=0,y,x));
false;

/* 72 */
(pn_(72),ans:contrib_ode(eqn:'diff(y,x)^2+(a*x+b*y)*'diff(y,x)-a*b*x*y=0,y,x));
false;

/* 73 */
(pn_(73),ans:contrib_ode(eqn:'diff(y,x)^2-x*y*'diff(y,x)+y^2*log(a*y)=0,y,x));
[x-sqrt(x^2-4*log(a*y))=%c];
(ans[1]-x)^2;
x^2-4*log(a*y)=(%c-x)^2;
map(exp,(x^2-%)/4);
a*y=%e^((x^2-(%c-x)^2)/4);
%/a;
y=%e^((x^2-(%c-x)^2)/4)/a;
[method,ode_check(eqn,%)];
[lie,0];
/* FIXME?  there is a second solution */

/* 74 ode1_lie takes forever */
/*(pn_(74),ans:contrib_ode(eqn:'diff(y,x)^2-(1+2*x*y)*'diff(y,x)+y^2*x*y=0,y,x));*/

/* 75 */
(pn_(75),ans:contrib_ode(eqn:'diff(y,x)^2-(4+y^2)*'diff(y,x)+4+y^2=0,y,x));
[[x=1/sqrt(%t-1)+%c,y=-(%t-2)/sqrt(%t-1)],[x=%c-1/sqrt(%t-1),y=(%t-2)/sqrt(%t-1)]];
solve(ans[1][1],sqrt(%t-1));
[sqrt(%t-1) = 1/(x-%c)];
%[1]^2+1;
%t = 1/(x-%c)^2+1;
ans[1][2],%;
y = -(1/(x-%c)^2-1)*abs(x-%c);
%,abs(x-%c)=(x-%c);
y = -(x-%c)*(1/(x-%c)^2-1);
[method,ode_check(eqn,%)];
[lagrange,0];

/* 76 ode1_lie takes forever */
/*(pn_(76),ans:contrib_ode(eqn:'diff(y,x)^2-(x-y)*y*'diff(y,x)+x*y^3=0,y,x));*/

/* 77 ode1_lie takes forever */
/*(pn_(77),ans:contrib_ode(eqn:'diff(y,x)^2+x*y^2*'diff(y,x)+y^3=0,y,x));*/

/* 78 Very long "answer" from ode1_lie */
/*(pn_(78),ans:contrib_ode(eqn:'diff(y,x)^2-2*x^3*y^2*'diff(y,x)+4*x^2*y^3=0,y,x));*/

/* 79 */
(pn_(79),ans:contrib_ode(eqn:'diff(y,x)^2+x*y*(x^2+y^2)*'diff(y,x)+x^4*y^4=0,y,x));
[y=%c*%e^-(x^4/4),1/(2*y^2)=x^2/2+%c];
solve(ans[2],y);
[y=-1/sqrt(x^2+2*%c),y=1/sqrt(x^2+2*%c)];
[method,ode_check(eqn,ans[1]),ode_check(eqn,%[1]),ode_check(eqn,%[2])];
[factor,0,0,0];

/* 80  Very long "answer" from ode1_lie */
/*(pn_(80),ans:contrib_ode(eqn:'diff(y,x)^2+x*y^3*'diff(y,x)+y^4=0,y,x));*/

/* 81 ode1_lie takes forever */
/* (pn_(81),ans:contrib_ode(eqn:'diff(y,x)^2+2*y*'diff(y,x)*cot(x)-y^2=0,y,x));*/

/* 82 ode1_lie takes forever */
/*(pn_(82),ans:contrib_ode(eqn:'diff(y,x)^2-3*x*y^(2/3)*'diff(y,x)+9*y^(5/3)=0,y,x));*/

/* 83 There is a typo in this eqn in Murphy.  This matches the solution given  
      Very long "answer" from ode1_lie */
/*(pn_(83),ans:contrib_ode(eqn:'diff(y,x)^2+exp(4*x-2*y)*('diff(y,x)-1)=0,y,x));*/

/* 84 */
(pn_(84),ans:contrib_ode(eqn:2*'diff(y,x)^2+x*'diff(y,x)-2*x=0,y,x));
[-(8*y-64*LOG(2*SQRT(x^2+16*x)+2*x+16)+(x+8)*SQRT(x^2+16*x)+x^2)/8 = %C];
solve(ans[1],y);
[y = (64*LOG(2*SQRT(x^2+16*x)+2*x+16)+(-x-8)*SQRT(x^2+16*x)-x^2-8*%C)/8];
[method,ode_check(eqn,%)];
[lie,0];

/* 85  */
(pn_(85),ans:contrib_ode(eqn:2*'diff(y,x)^2-(1-x)*'diff(y,x)-y=0,y,x));
[y=%C*x+2*%C^2-%C,y=-(x^2-2*x+1)/8];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[clairault,0,0];

/* 86 Very long "answer" from ode1_lie that doesn't satisfy ode*/
/*(pn_(86),ans:contrib_ode(eqn:2*'diff(y,x)^2-2*x^2*'diff(y,x)+3*x*y=0,y,x));*/

/* 87 */
(pn_(87),ans:contrib_ode(eqn:2*'diff(y,x)^2-2*(6*y-1)*'diff(y,x)+3*y*(6*y-1)=0,y,x));
[[x=2*log(sqrt(1-8*%t)-1)/3+%c,y=-(-4*%t+sqrt(1-8*%t)-1)/12],[x=2*log(sqrt(1-8*%t)+1)/3+%c,y=(4*%t+sqrt(1-8*%t)+1)/12]];
map(exp,(ans[1][1]-%c)*3/2)+1;
%e^(3*(x-%c)/2)+1 = sqrt(1-8*%t);
%^2;
(%e^(3*(x-%c)/2)+1)^2=1-8*%t;
%,%c=-(2/3)*log(%c); /* a better constant */
(%e^(3*(x+2*log(%c)/3)/2)+1)^2=1-8*%t;
radcan(%);
%c^2*%e^(3*x)+2*%c*%e^(3*x/2)+1 = 1-8*%t;
solve(%,%t);
[%t=-(%c^2*%e^(3*x)+2*%c*%e^(3*x/2))/8];
ans[1][2],%;
y=-(sqrt(%c^2*%e^(3*x)+2*%c*%e^(3*x/2)+1)+(%c^2*%e^(3*x)+2*%c*%e^(3*x/2))/2-1)/12;
radcan(%);
y=-(%c^2*%e^(3*x)+4*%c*%e^(3*x/2))/24;
[method,ode_check(eqn,%)];
[lagrange,0];

/* 88 */
(pn_(88),ans:contrib_ode(eqn:3*'diff(y,x)^2-2*x*'diff(y,x)+y=0,y,x));
[4*y^3-x^2*y^2-18*%C*x*y+4*%C*x^3+27*%C^2 = 0];
method;
lagrange;

/* 89 */
(pn_(89),ans:contrib_ode(eqn:3*'diff(y,x)^2+4*x*'diff(y,x)+x^2-y=0,y,x));
[(4*%i*sqrt(3*y+x^2)+2*%i*x)/(3*sqrt(2)) = %c];
expand(ans[1]/%i);
4*sqrt(3*y+x^2)/(3*sqrt(2))+2*x/(3*sqrt(2)) = -%i*%c;
%,%c=%i*%c;
4*sqrt(3*y+x^2)/(3*sqrt(2))+2*x/(3*sqrt(2)) = %c;
solve(%,sqrt(3*y+x^2));
[sqrt(3*y+x^2) = -(2*x-3*sqrt(2)*%c)/4];
%[1]^2;
3*y+x^2 = (2*x-3*sqrt(2)*%c)^2/16;
solve(%,y);
[y = -(2*x^2+2*sqrt(2)*%c*x-3*%c^2)/8];
[method,ode_check(eqn,%[1])];
[lie,0];

/* 90 */
(pn_(90),ans:contrib_ode(eqn:4*'diff(y,x)^2=9*x,y,x));
[-y-x^(3/2)=%c];
solve(ans[1],y);
[y=-x^(3/2)-%c];
[method,ode_check(eqn,%)];
[lie,0];

/* 91 Very long "answer" from ode1_lie that doesn't satisfy ode */
/* (pn_(91),ans:contrib_ode(eqn:4*'diff(y,x)^2+2*x*exp(-2*y)*'diff(y,x)-exp(-2*y)=0,y,x));*/

/* 92 */
(pn_(92),ans:contrib_ode(eqn:4*'diff(y,x)^2+2*exp(2*x-2*y)*'diff(y,x)-exp(2*x-2*y)=0,y,x));
false;

/* 93 */
(pn_(93),ans:contrib_ode(eqn:5*'diff(y,x)^2+3*x*'diff(y,x)-y=0,y,x));
[[x=%e^-(3*log(%t)/2)*(%c-2*%e^(5*log(%t)/2)),y=3*%t*x+5*%t^2]];
map(radcan,ans);
[[x=-(2*%t^(5/2)-%c)/%t^(3/2),y=3*%t*x+5*%t^2]]; /*CHECKME*/
method;
lagrange;

/* 94  Very long "answer" from ode1_lie that doesn't satisfy ode */
/* (pn_(94),ans:contrib_ode(eqn:5*'diff(y,x)^2+6*x*'diff(y,x)-2*y=0,y,x)); */

/* 95 ode1_lie takes forever */
/* (pn_(95),ans:contrib_ode(eqn:9*'diff(y,x)^2+3*x*y^4*'diff(y,x)+y^5=0,y,x));*/

/* 96 */
(pn_(96),ans:contrib_ode(eqn:x*'diff(y,x)^2=a,y,x));
[-y-2*sqrt(a/x)*x = %c];
solve(ans[1],y);
[y = -2*sqrt(a/x)*x-%c];
[method,ode_check(eqn,%[1])];
[lie,0];

/* 97 */
(pn_(97),ans:contrib_ode(eqn:x*'diff(y,x)^2=(a-x)^2,y,x));
[-(3*y+sqrt(x)*(2*x-6*a))/3=%c];
solve(ans[1],y);
[y=-(2*x^(3/2)-6*a*sqrt(x)+3*%c)/3];
[method,ode_check(eqn,%)];
[lie,0];

/* 98 */
(pn_(98),ans:contrib_ode(eqn:x*'diff(y,x)^2=y,y,x));
[x^2*(y^2+(-2*x-2*%C)*y+x^2-2*%C*x+%C^2) = 0];
ans:solve(expand(%[1]),y);
[y = -2*SQRT(%C*x)+x+%C,y = 2*SQRT(%C*x)+x+%C];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[lagrange,0,0];

/* 99 */
(pn_(99),ans:contrib_ode(eqn:x*'diff(y,x)^2+x-2*y=0,y,x));
[[x=%c*%e^-(2*(log(%t-1)-1/(%t-1))),y=(%t^2+1)*x/2]]; /* CHECKME */
method;
lagrange;

/* 100 */
(pn_(100),ans:contrib_ode(eqn:x*'diff(y,x)^2+'diff(y,x)=y,y,x));
[[x = (log(%t)-%t+%c)/(%t-1)^2,y = %t^2*x+%t]]; /* CHECKME */
method;
lagrange;

/* 101 */
(pn_(101),ans:contrib_ode(eqn:x*'diff(y,x)^2+2*'diff(y,x)-y=0,y,x));
[[x = (%c-2*(%t-log(%t)))/(%t-1)^2,y = %t^2*x+2*%t]]; /* CHECKME */
method;
lagrange;

/* 102 */
(pn_(102),ans:contrib_ode(eqn:x*'diff(y,x)^2-2*'diff(y,x)-y=0,y,x));
[[x = (2*(%t-log(%t))+%c)/(%t-1)^2,y = %t^2*x-2*%t]]; /* CHECKME */
method;
lagrange;

/* 103 ode1_lie takes forever */
/*(pn_(103),ans:contrib_ode(eqn:x*'diff(y,x)^2+4*'diff(y,x)-2*y=0,y,x));*/

/* 104  */
(pn_(104),ans:contrib_ode(eqn:x*'diff(y,x)^2+x*'diff(y,x)-y=0,y,x));
[[x=%c*%e^(1/%t)/%t^2,y=(%t^2+%t)*x]];
map(radcan,ans);
[[x=%c*%e^(1/%t)/%t^2,y=(%t^2+%t)*x]]; /* correct */
method;
lagrange;

/* 105 */
(pn_(105),ans:contrib_ode(eqn:x*'diff(y,x)^2+(1-x^2)*'diff(y,x)+x=0,y,x));
[-(4*y+2*'INTEGRATE(%E^(LOG(x^2+2*x-1)/2+LOG(x^2-2*x-1)/2)/x,x)+2*LOG(x)-x^2)/4=%C];
solve(ans[1],y);
[y=-(2*'INTEGRATE(%E^(LOG(x^2+2*x-1)/2+LOG(x^2-2*x-1)/2)/x,x)+2*LOG(x)-x^2+4*%C)/4];
[method,expand(ode_check(eqn,%))];
[lie,0];

/* 106 FIXME: Check solution */
(pn_(106),ans:contrib_ode(eqn:x*'diff(y,x)^2+y*'diff(y,x)+a=0,y,x));
[(4*log(sqrt(y^2-4*a*x)+2*y)+2*log(sqrt(y^2-4*a*x)-y))/3 = %c];
method;
lie;

/* 107 */
(pn_(107),ans:contrib_ode(eqn:x*'diff(y,x)^2-y*'diff(y,x)+a=0,y,x));
[y=(%C^2*x+a)/%C,y=-2*sqrt(a*x),y=2*sqrt(a*x)];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3])];
[clairault,0,0,0];

/* 108 */
(pn_(108),ans:contrib_ode(eqn:x*'diff(y,x)^2-y*'diff(y,x)+a*x=0,y,x));
[[x=%c*%e^-((%t^2/2-log(%t)*a)/a),y=(a+%t^2)*x/%t]];
radcan(ans);
[[x=%c*%t*%e^-(%t^2/(2*a)),y=(a+%t^2)*x/%t]]; /* correct */
method;
lagrange;

/* 109 ode1_lie finds symmetry but returns long complex "answer" */
/* (pn_(109),ans:contrib_ode(eqn:x*'diff(y,x)^2+y*'diff(y,x)-x^2=0,y,x));*/

/* 110 ode1_lie finds symmetry but returns long complex "answer" */
/* (pn_(110),ans:contrib_ode(eqn:x*'diff(y,x)^2+y*'diff(y,x)-x^3=0,y,x)); */

/* 111 */
(pn_(111),ans:contrib_ode(eqn:x*'diff(y,x)^2-y*'diff(y,x)+a*y=0,y,x));
[[x=%c*(%t-a)*%e^-(%t/a),y=%t^2*x/(%t-a)]];
[ans[1][1],ev(ans[1][2],ans[1][1])];
[x=%c*(%t-a)*%e^-(%t/a),y=%c*%t^2*%e^-(%t/a)]; /* correct */
method;
lagrange;

/* 112 */
(pn_(112),ans:contrib_ode(eqn:x*'diff(y,x)^2+y*'diff(y,x)-y^4=0,y,x));
[2*LOG(SQRT(4*x*y^2+1)-1)-2*LOG(y)=%C]; /*CHECKME*/
expand(%[1]/2);
LOG(SQRT(4*x*y^2+1)-1)-LOG(y)=%C/2;
map(exp,%);
(SQRT(4*x*y^2+1)-1)/y=%E^(%C/2);
%*y;
SQRT(4*x*y^2+1)-1=%E^(%C/2)*y;
%,%e^(%c/2)=%c;
SQRT(4*x*y^2+1)-1=%C*y;
(%+1)^2;
4*x*y^2+1=(%C*y+1)^2;
solve(expand(%),y);
[y=2*%C/(4*x-%C^2),y=0];
[method,ode_check(eqn,%[1]),ode_check(eqn,%[2])];
[lie,0,0];
/* Murphy gives y*(x-C)^2=C, y=0, 4*x*y^2+1=0 */

/* 113 */ 
(pn_(113),ans:contrib_ode(eqn:x*'diff(y,x)^2+(a-y)*'diff(y,x)+b=0,y,x));
[y=(%C^2*x+b+%C*a)/%C,y = a-2*SQRT(b*x),y = 2*SQRT(b*x)+a];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3])];
[clairault,0,0,0];

/* 114 */
(pn_(114),ans:contrib_ode(eqn:x*'diff(y,x)^2+(x-y)*'diff(y,x)+1-y=0,y,x));
[y=((%c^2+%c)*x+1)/(%c+1),y=-x-2*sqrt(x),y=2*sqrt(x)-x];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3])];
[clairault,0,0,0];

/* 115 */
(pn_(115),ans:contrib_ode(eqn:x*'diff(y,x)^2+(a+x-y)*'diff(y,x)-y=0,y,x));
[y=((%c^2+%c)*x+%c*a)/(%c+1),y=-2*sqrt(-a*x)-x+a,y=2*sqrt(-a*x)-x+a];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3])];
[clairault,0,0,0];

/* 116 */
(pn_(116),ans:contrib_ode(eqn:x*'diff(y,x)^2-(3*x-y)*'diff(y,x)+y=0,y,x));
[[x=%c*(%t+1)*%e^-(3*log(%t)/2),y=-(%t^2-3*%t)*x/(%t+1)]];
ans:map(radcan,ans);
[[x=(%c*%t+%c)/%t^(3/2),y=-(%t^2-3*%t)*x/(%t+1)]];
ans[1][2],ans[1][1];
y=-(%c*%t+%c)*(%t^2-3*%t)/(%t^(3/2)*(%t+1));
(ans[1][2]:factor(%),ans);
[[x=(%c*%t+%c)/%t^(3/2),y=-%c*(%t-3)/sqrt(%t)]]; /* correct */
method;
lagrange;

/* 117 */
(pn_(117),ans:contrib_ode(eqn:x*'diff(y,x)^2+(a+b*x-y)*'diff(y,x)-b*y=0,y,x));
[y=((%C*b+%C^2)*x+%C*a)/(b+%C),y=-2*SQRT(-a*b*x)-b*x+a,y=2*SQRT(-a*b*x)-b*x+a];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3])];
[clairault,0,0,0];

/* 118 */
(pn_(118),ans:contrib_ode(eqn:x*'diff(y,x)^2-2*y*'diff(y,x)+a=0,y,x));
[(2*log(2*sqrt(y^2-a*x)-y)+4*log(sqrt(y^2-a*x)+y))/3 = %c]; /* CHECKME */
method;
lie;

/* 119 */
(pn_(119),ans:contrib_ode(eqn:x*'diff(y,x)^2+2*y*'diff(y,x)-x=0,y,x));
[[x=%c*%t*%e^-(2*log(3*%t^2-1)/3),y=-(%t^2-1)*x/(2*%t)]];
ans:map(radcan,ans); 
[[x=%c*%t/(3*%t^2-1)^(2/3),y=-(%t^2-1)*x/(2*%t)]];  /*CHECKME*/
method;
lagrange;

/* 120 */
(pn_(120),ans:contrib_ode(eqn:x*'diff(y,x)^2-2*y*'diff(y,x)+a*x=0,y,x));
[x*(2*%C*y-x^2-%C^2*a)=0];
ans[1]/x;
2*%C*y-x^2-%C^2*a=0;
ans:solve(%,y);
[y=(x^2+%C^2*a)/(2*%C)];
[method,ode_check(eqn,ans[1])];
[lagrange,0];
/* Second solution y^2=a*x^2 */

/* 121 */
(pn_(121),ans:contrib_ode(eqn:x*'diff(y,x)^2-2*y*'diff(y,x)+x+2*y=0,y,x));
[x*(2*%c*y-x^2-2*%c*x-2*%c^2)=0];
ans[1]/x;
2*%c*y-x^2-2*%c*x-2*%c^2=0;
ans:solve(%,y);
[y=(x^2+2*%c*x+2*%c^2)/(2*%c)];
[method,ode_check(eqn,ans[1])];
[lagrange,0];
/* Second solution (x-y)^2=2*x^2 */

/* 122 */
(pn_(122),ans:contrib_ode(eqn:x*'diff(y,x)^2-3*y*'diff(y,x)+9*x^2=0,y,x));
[(log(sqrt(y^2-4*x^3)+y)-log(sqrt(y^2-4*x^3)-y)+3*log(x))/3=%C]; /*CHECKME*/
method;
lie;

/* 123 */
(pn_(123),ans:contrib_ode(eqn:x*'diff(y,x)^2-(2*x+3*y)*'diff(y,x)+6*y=0,y,x));
[y = 2*x+%C,y = %C*x^3];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[FACTOR,0,0];

/* 124 */
(pn_(124),ans:contrib_ode(eqn:x*'diff(y,x)^2-a*y*'diff(y,x)+b=0,y,x));
[(2*a*log(sqrt(a^2*y^2-4*b*x)+a*y)+(2*a-2)*log(sqrt(a^2*y^2-4*b*x)+(1-a)*y))/(2*a-1)=%c];
/* Have my doubts on this one */
method;
lie;

/* 125 */
(pn_(125),ans:contrib_ode(eqn:x*'diff(y,x)^2+a*y*'diff(y,x)+b*x=0,y,x));
[[x=%c*%t*%e^-((a+2)*log(b+%t^2*(a+1))/(2*a+2)),y=-(b+%t^2)*x/(%t*a)]];
/* CHECKME:  Looks ok but ... */
method;
lagrange;

/* 126 */
(pn_(126),ans:contrib_ode(eqn:x*'diff(y,x)^2-(1+x*y)*'diff(y,x)+y=0,y,x));
[y=log(x)+%c,y=%c*%e^x];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[factor,0,0];

/* 127 */
(pn_(127),ans:contrib_ode(eqn:x*'diff(y,x)^2+(1-x)*y*'diff(y,x)-y^2=0,y,x));
[y=%c*%e^x,y=%c/x];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[factor,0,0];

/* 128 */
(pn_(128),ans:contrib_ode(eqn:x*'diff(y,x)^2+(1-x^2*y)*'diff(y,x)-x*y=0,y,x));
[y=%c-log(x),y=%c*%e^(x^2/2)];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[factor,0,0];

/* 129 */
(pn_(129),ans:contrib_ode(eqn:(1+x)*'diff(y,x)^2=y,y,x));
[(x^2+2*x+1)*(y^2+(-2*x-2*%c-4)*y+x^2-2*%c*x+%c^2)=0]; /* CHECKME */
method;
lagrange;
/* Second solution y=0 */

/* 130 */
(pn_(129),ans:contrib_ode(eqn:(1+x)*'diff(y,x)^2-(x+y)*'diff(y,x)+y=0,y,x));
[y=((%C^2-%C)*x+%C^2)/(%C-1),y=-2*SQRT(x+1)+x+2,y=2*SQRT(x+1)+x+2];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3])];
[clairault,0,0,0];

/* 131 */
(pn_(131),ans:contrib_ode(eqn:(a-x)*'diff(y,x)^2+y*'diff(y,x)-b=0,y,x));
[y = (%C^2*x+b-%C^2*a)/%C,y = -2*SQRT(b*x-a*b),y = 2*SQRT(b*x-a*b)];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3])];
[clairault,0,0,0];

/* 132 - Too general */

/* 133 FIXME: ode1_lie takes "forever" */
/* ans:contrib_ode(eqn:2*x*'diff(y,x)^2-(2*x-y)*'diff(y,x)+1-y=0,y,x);
false; */

/* 134 ode1_lie takes "forever" */
/* (pn_(134),ans:contrib_ode(eqn:3*x*'diff(y,x)^2+(2*x-y)*'diff(y,x)+1-y=0,y,x));*/

/* 135 */
(pn_(134),ans:contrib_ode(eqn:(1+3*x)*'diff(y,x)^2-3*(2+y)*'diff(y,x)+9=0,y,x));
[y=(3*%C^2*x+%C^2-6*%C+9)/(3*%C),y=-2*SQRT(3*x+1)-2,y=2*SQRT(3*x+1)-2];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3])];
[clairault,0,0,0];

/* 136 */
(pn_(134),ans:contrib_ode(eqn:(5+3*x)*'diff(y,x)^2-(x+3*y)*'diff(y,x)+y=0,y,x));
[y=((3*%C^2-%C)*x+5*%C^2)/(3*%C-1),y=-(2*SQRT(5)*SQRT(3*x+5)-3*x-10)/9,y=(2*SQRT(5)*SQRT(3*x+5)+3*x+10)/9];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3])];
[clairault,0,0,0];

/* 137 */
(pn_(137),ans:contrib_ode(eqn:4*x*'diff(y,x)^2=(a-3*x)^2,y,x));
[(a-x)*sqrt(x)-y=%c];
solve(ans[1],y);
[y=-x^(3/2)+a*sqrt(x)-%c];
[method,ode_check(eqn,%)];
[lie,0];

/* 138 */
(pn_(138),ans:contrib_ode(eqn:4*x*'diff(y,x)^2+2*x*'diff(y,x)-y=0,y,x));
[x^2*(y^2-8*%C*y-4*%C*x+16*%C^2)=0];
ans[1]/x^2;
y^2-8*%C*y-4*%C*x+16*%C^2=0;
%,%c=%c/4;
y^2-2*%C*y-%C*x+%C^2=0;
ans:solve(%,y);
[y=%C-SQRT(%C*x),y=SQRT(%C*x)+%C];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[lagrange,0,0];
/* Another solution y=-x/4 */

/* 139  ode1_lie finds symmetry but returns long complex "answer" */
(pn_(139),ans:contrib_ode(eqn:4*x*'diff(y,x)^2-3*y*'diff(y,x)+3=0,y,x));
[-(3*LOG((SQRT(3*y^2-16*x)-SQRT(3)*y)/(SQRT(3*y^2-16*x)+SQRT(3)*y))+2*LOG(SQRT(3)*SQRT(3*y^2-16*x)+y)-3*LOG(-16*x))/2=%C];
method;
lie;

/* 140 ode1_lie finds symmetry but returns long complex "answer" */
(pn_(140),ans:contrib_ode(eqn:4*x*'diff(y,x)^2+4*y*'diff(y,x)=1,y,x));
[(4*LOG(SQRT(y^2+x)+2*y)+2*LOG(SQRT(y^2+x)-y))/3 = %C];
method;
lie;

/* 141 ode1_lie finds symmetry but ... */
(pn_(141),ans:contrib_ode(eqn:4*x*'diff(y,x)^2+4*y*'diff(y,x)-y^4=0,y,x));
[2*LOG(SQRT(x*y^2+1)-1)-2*LOG(y) = %C]; /* Have doubts */
method;
lie;

/* 142 */
(pn_(142),ans:contrib_ode(eqn:4*(2-x)*'diff(y,x)^2+1=0,y,x));
[-y-sqrt(x-2)=%c];
solve(ans[1],y);
[y=-sqrt(x-2)-%c];
[method,ode_check(eqn,%)];
[lie,0];

/* 143 ode1_lie finds symmetry but ... */
(pn_(143),ans:contrib_ode(eqn:16*x*'diff(y,x)^2+8*y*'diff(y,x)+y^6=0,y,x));
[2*LOG(SQRT(1-x*y^4)-1)-4*LOG(y) = %C]; /* Have doubts */
method;
lie;

/* 144 */
(pn_(144),ans:contrib_ode(eqn:x^2*'diff(y,x)^2=a^2,y,x));
[y=a*log(x)+%c,y=%c-a*log(x)];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[factor,0,0];

/* 145 */
(pn_(145),ans:contrib_ode(eqn:x^2*'diff(y,x)^2=y^2,y,x));
[y=%c*x,y=%c/x];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[factor,0,0];

/* 146 ???? */
(pn_(146),ans:contrib_ode(eqn:x^2*'diff(y,x)^2+x^2-y^2=0,y,x));
[[x=%c*%e^-'integrate(%t/(%t*sqrt(%t^2+1)+%t^2+1),%t),y=-sqrt(%t^2+1)*x],[x=%c*%e^'integrate(%t/(%t*sqrt(%t^2+1)-%t^2-1),%t),y=sqrt(%t^2+1)*x]];
method;
lagrange;

/* 147 */
(pn_(147),ans:contrib_ode(eqn:x^2*'diff(y,x)^2=(x-y)^2,y,x));
[y=x*(%c-log(x)),y=(x^2/2+%c)/x];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[factor,0,0];

/* 148 Crashes ode1_lie */
/* (pn_(148),ans:contrib_ode(eqn:x^2*'diff(y,x)^2+y^3-y^4=0,y,x)); */

/* 149 */
(pn_(149),ans:contrib_ode(eqn:x^2*'diff(y,x)^2-x*'diff(y,x)+y*(1-y)=0,y,x));
[y=%c*x,y=(x+%c)/x];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[factor,0,0];

/* 150 ode1_lie takes "forever" */
/*(pn_(150),ans:contrib_ode(eqn:x^2*'diff(y,x)^2+2*a*x*'diff(y,x)+a^2+x^2-2*a*y=0,y,x));*/

/* 151 Crashes ode1_lie */
/*(pn_(151),ans:contrib_ode(eqn:x^2*'diff(y,x)^2-2*x*y*'diff(y,x)-x+y*(1+y)=0,y,x));*/

/* 152 */
assume(x>0,y>0);
[x>0,y>0];
(pn_(152),ans:contrib_ode(eqn:x^2*'diff(y,x)^2-2*x*y*'diff(y,x)-x^4+(1-x^2)*y^2=0,y,x));
[asinh(y/x)+x = %c];
ans:solve(ans[1],y);
[y=-x*sinh(x-%c)];
[method,trigsimp(ode_check(eqn,ans[1]))];
[lie,0];
forget(x>0,y>0);
[x>0,y>0];
/* Other solution is y=x*sinh(x-%c) */

/* 153 */
(pn_(153),ans:contrib_ode(eqn:x^2*'diff(y,x)^2-(1+2*x*y)*'diff(y,x)+1+y^2=0,y,x));
[y=%c*x-sqrt(%C-1),y=%C*x+sqrt(%C-1),y=(4*x^2-1)/(4*x)];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3])];
[clairault,0,0,0];

/* 154 */
(pn_(154),ans:contrib_ode(eqn:x^2*'diff(y,x)^2-(a+2*x*y)*'diff(y,x)+1+y^2=0,y,x));
[y=%C*x-sqrt(%C*a-1),y=%C*x+sqrt(%C*a-1),y=(4*x^2-a^2)/(4*a*x)];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3])];
[clairault,0,0,0];

/* 155 ode1_lie takes "forever" */
/*(pn_(155),ans:contrib_ode(eqn:x^2*'diff(y,x)^2-x*(x-2*y)*'diff(y,x)+y^3=0,y,x));*/

/* 156 ode1_lie finds symmetry but ... symtest # 0 */
/* (pn_(156),ans:contrib_ode(eqn:x^2*'diff(y,x)^2+2*x*(2*x+y)*'diff(y,x)-4*a+y^2=0,y,x));*/

/* 157 ode1_lie takes "forever" */
/*(pn_(157),ans:contrib_ode(eqn:x^2*'diff(y,x)^2+x*(x^3+2*y)*'diff(y,x)-(2*x^3-y)*y=0,y,x));*/

/* 158 */
(pn_(158),ans:contrib_ode(eqn:x^2*'diff(y,x)^2+3*x*y*'diff(y,x)+2*y^2=0,y,x));
[y=%c/x,y=%c/x^2];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[factor,0,0];

/* [[x=%c*%e^-(log(%t)/2),y=-%t*x]];
radcan(%);
[[x=%c/sqrt(%t),y=-%t*x]];
solve(ans[1][1]^2,%t);
[%t=%c^2/x^2];
ans:ans[1][2],%;
y=-%c^2/x;
[method,ode_check(eqn,%)];
[lagrange,0];*/
/* Other solution is y=%c/x */

/* 159 ode1_lie finds symmetry but ... */
(pn_(159),ans:contrib_ode(eqn:x^2*'diff(y,x)^2-3*x*y*'diff(y,x)+x^3+2*y^2=0,y,x));
[LOG(SQRT(y^2-4*x^3)+y)-LOG(SQRT(y^2-4*x^3)-y)+LOG(x)=%C]; /* Have doubts */
method;
lie;

/* 160 */
(pn_(160),ans:contrib_ode(eqn:x^2*'diff(y,x)^2+4*x*y*'diff(y,x)-5*y^2=0,y,x));
[y=%c*x,y=%c/x^5];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[factor,0,0];

/* 161 Crashes lie_ode1 */
/*(pn_(161),ans:contrib_ode(eqn:x^2*'diff(y,x)^2-4*x*(2+y)*'diff(y,x)-4*(2+y)*y=0,y,x));*/

/* 162 */
(pn_(162),ans:contrib_ode(eqn:x^2*'diff(y,x)^2-5*x*y*'diff(y,x)+6*y^2=0,y,x));
[y=%c*x^2,y=%c*x^3];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2])];
[factor,0,0];

/* 163 ode1_lie takes "forever" */
/*(pn_(163),ans:contrib_ode(eqn:x^2*'diff(y,x)^2+x*(x^2+x*y-2*y)*'diff(y,x)+(1-x)*(x^2-y)*y=0,y,x));*/

/* 164  ode1_lie finds symmetry but ... */
assume(x>0);
[x>0];
(pn_(164),ans:contrib_ode(eqn:x^2*'diff(y,x)^2+(2*x+y)*y*'diff(y,x)+y^2=0,y,x));
[LOG(SQRT(y^2+4*x*y)-y) = %C]; /* Have doubts */
method;
lie;
forget(x>0);
[x>0];

/* 165 ode1_lie finds symmetry but ... */
assume(x>0);
[x>0];
(pn_(165),ans:contrib_ode(eqn:x^2*'diff(y,x)^2-(2*x-y)*y*'diff(y,x)+y^2=0,y,x));
[(y*LOG(SQRT(y^2-4*x*y)-y)+SQRT(y^2-4*x*y))/y = %C]; /* Have doubts */
method;
lie;
forget(x>0);
[x>0];

/* 166 */
(pn_(166),ans:contrib_ode(eqn:x^2*'diff(y,x)^2+(a+b*x^2*y^3)*'diff(y,x)+a*b*y^3=0,y,x));
[y=a/x+%C,1/(2*b*y^2)=x+%C];
solve(ans[2],y);
[y=-1/(sqrt(2)*sqrt(b*x+%c*b)),y=1/(sqrt(2)*sqrt(b*x+%c*b))];
[method,ode_check(eqn,ans[1]),ode_check(eqn,%[1]),ode_check(eqn,%[2])];
[factor,0,0,0];

/* 167 Crashes ode1_lie */
/*(pn_(167),ans:contrib_ode(eqn:(1-x^2)*'diff(y,x)^2=1-y^2,y,x));*/

/* 168 ode1_lie finds symmetry but ... */
(pn_(168),ans:contrib_ode(eqn:(1-x^2)*'diff(y,x)^2+2*x*y*'diff(y,x)+4*x^2=0,y,x));
[LOG(SQRT(y^2+4*x^2-4)+y) = %C]; /* Have doubts */
method;
lie;

/* 169 */
(pn_(169),ans:contrib_ode(eqn:(a^2+x^2)*'diff(y,x)^2=b^2,y,x));
[-y-b*ASINH(x/ABS(a))=%C];
solve(ans[1],y);
[y=-b*ASINH(x/ABS(a))-%C];
[method,ode_check(eqn,%[1])];
[lie,0];

/* 170 */
(pn_(170),ans:contrib_ode(eqn:(a^2-x^2)*'diff(y,x)^2+b^2=0,y,x));
[-y-b*log(2*sqrt(x^2-a^2)+2*x)=%c];
solve(ans[1],y);
[y = -b*log(2*sqrt(x^2-a^2)+2*x)-%c];
[method,ode_check(eqn,%[1])];
[lie,0];

/* 171 */
(pn_(171),ans:contrib_ode(eqn:(a^2-x^2)*'diff(y,x)^2=b^2,y,x));
[-y-b*asin(x/abs(a))=%c];
solve(ans[1],y);
[y=-b*asin(x/abs(a))-%c];
[method,ode_check(eqn,%[1])];
[lie,0];

/* 172 */
(pn_(172),ans:contrib_ode(eqn:(a^2-x^2)*'diff(y,x)^2=x^2,y,x));
[sqrt(a^2-x^2)-y=%c];
solve(ans[1],y);
[y=sqrt(a^2-x^2)-%c];
[method,ode_check(eqn,%[1])];
[lie,0];

/* 173 ode1_lie finds symmetry but ... */
(pn_(173),ans:contrib_ode(eqn:(a^2-x^2)*'diff(y,x)^2+2*x*y*'diff(y,x)+x^2=0,y,x));
[LOG(SQRT(y^2+x^2-a^2)-y) = %C]; /* Have doubts */
method;
lie;

/* 174 ode1_lie finds symmetry but ... */
(pn_(174),ans:contrib_ode(eqn:(a^2-x^2)*'diff(y,x)^2-2*x*y*'diff(y,x)-x^2=0,y,x));
[(LOG(SQRT(y^2-x^2+a^2)+y)+2*LOG(SQRT(y^2-x^2+a^2)-2*y))/3 = %C]; /* Have doubts */
method;
lie;

/* 175 */
(pn_(175),ans:contrib_ode(eqn:(a^2+x^2)*'diff(y,x)^2-2*x*y*'diff(y,x)+b+y^2=0,y,x));
[y=%c*x-sqrt(-b-%c^2*a^2),y=%c*x+sqrt(-b-%c^2*a^2),y=-sqrt(-b)*sqrt(x^2+a^2)/a,y=sqrt(-b)*sqrt(x^2+a^2)/a];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3]),ode_check(eqn,ans[4])];
[clairault,0,0,0,0];

/* 176 ode1_lie takes "forever" */
/*(pn_(176),ans:contrib_ode(eqn:(1+2*x^2)*'diff(y,x)^2-(2+x^2+2*x*y+y^2)*'diff(y,x)+1+2*y^2=0,y,x));*/

/* 177 */
(pn_(177),ans:contrib_ode(eqn:4*x^2*'diff(y,x)^2-4*x*y*'diff(y,x)=8*x^3-y^2,y,x));
[-(2*log(y+sqrt(x)*(sqrt(2)*x-%c))-log(x))/2=%c];
solve(ans[1],y);
[y=%e^(log(x)/2-%c)-sqrt(2)*x^(3/2)+%c*sqrt(x)];
[method,ode_check(eqn,%[1])];
[lie,0];

/* 178 ode1_lie finds symmetry but ... */
/*(pn_(178),ans:contrib_ode(eqn:a*x^2*'diff(y,x)^2-2*a*x*y*'diff(y,x)+a*(a-1)*x^2+y^2=0,y,x));*/

/* 179 ode1_lie finds symmetry but ... */
/*(pn_(179),ans:contrib_ode(eqn:(1-a^2)*x^2*'diff(y,x)^2-2*x*y*'diff(y,x)-a^2*x^2+y^2=0,y,x));*/

/* 180 */
(pn_(180),ans:contrib_ode(eqn:x^3*'diff(y,x)^2=a,y,x));
[2*sqrt(a/x)-y=%c];
solve(ans[1],y);
[y=2*sqrt(a/x)-%c];
[method,ode_check(eqn,%[1])];
[lie,0];

/* 181 ode1_lie takes "forever"*/
/*(pn_(181),ans:contrib_ode(eqn:x^3*'diff(y,x)^2+x*'diff(y,x)-y=0,y,x));*/

/* 182 ode1_lie finds symmetry but ... */
/*assume(a>0);
[a>0];
(pn_(182),ans:contrib_ode(eqn:x^3*'diff(y,x)^2+x^2*y*'diff(y,x)+a=0,y,x));
[log((sqrt(x*y^2-4*a)+sqrt(x)*y)/sqrt(x))-log((sqrt(x*y^2-4*a)-sqrt(x)*y)/sqrt(x))+log(x)=%c];
method;
lie;
forget(a>0);
[a>0];*/

/* 183 ode1_lie finds symmetry but takes "forever" */
/* (pn_(183),ans:contrib_ode(eqn:x^3*'diff(y,x)^2-(1+2*x^2*y)*'diff(y,x)+x*y^2=0,y,x));*/

/* 184 */
(pn_(184),ans:contrib_ode(eqn:x*(1-x^2)*'diff(y,x)^2+2*(1-x^2)*y*'diff(y,x)+x*(1-y^2)=0,y,x));
false;

/* 185 */
(pn_(185),ans:contrib_ode(eqn:4*x*(a-x)*(b-x)*'diff(y,x)^2=(a*b-2*x*(a+b)+3*x^2)^2,y,x));
[-(2*y+'integrate((3*x^2+(-2*b-2*a)*x+a*b)/sqrt(x^3+(-b-a)*x^2+a*b*x),x))/2=%c];
solve(ans[1],y);
[y=-('integrate(3*x^2/sqrt(x^3-b*x^2-a*x^2+a*b*x)-2*b*x/sqrt(x^3-b*x^2-a*x^2+a*b*x)-2*a*x/sqrt(x^3-b*x^2-a*x^2+a*b*x)+a*b/sqrt(x^3-b*x^2-a*x^2+a*b*x),x)+2*%c)/2];
[method,ode_check(eqn,%[1])];
[lie,0];

/* 186 ode1_lie finds symmetry but ... */
(pn_(186),ans:contrib_ode(eqn:x^4*'diff(y,x)^2-x*'diff(y,x)-y=0,y,x));
[(2*%i*x^2*sqrt(4*x^2*y+1)*'integrate((abs(x)*sqrt(4*x^2*y+1)-abs(x))/(x^3*sqrt(4*x^2*y+1)),x)+8*%i*x^2*abs(x)*y+2*%i*'integrate(abs(x)/x,x)+2*%i*abs(x))/(sqrt(2)*sqrt(3)*x^2*sqrt(4*x^2*y+1))=%c];
method;
lie;

/* 187 ode1_lie finds symmetry but ... */
(pn_(187),ans:contrib_ode(eqn:x^4*'diff(y,x)^2+2*x^3*y*'diff(y,x)-4=0,y,x));
[(y*asinh(x*y^2/(2*abs(y)))+log(x)*abs(y))/abs(y)=%c];
method;
lie;

/* 188  ode1_lie finds symmetry but returns long "answer" */
/*(pn_(188),ans:contrib_ode(eqn:x^4*'diff(y,x)^2+x*y^2*'diff(y,x)-y^3=0,y,x));*/

/* 189 */
assume(a>0);
[a>0];
(pn_(189),ans:contrib_ode(eqn:x^2*(a^2-x^2)*'diff(y,x)^2+1=0,y,x));
[-(a*y-ASIN(a/ABS(x)))/a = %C];
solve(ans[1],y);
[y = (ASIN(a/ABS(x))-%C*a)/a];
[method,ode_check(eqn,%[1])];
[lie,0];
forget(a>0);
[a>0];

/* 190 ode1_lie finds symmetry but ... */
(pn_(190),ans:contrib_ode(eqn:3*x^4*'diff(y,x)^2-x*y-y=0,y,x));
[(4*sqrt(2)*sqrt(3)*%i*x*sqrt((x+1)*y)+sqrt(x+1)*(sqrt(2)*%i*x*log(sqrt(x+1)-1)-sqrt(2)*%i*x*log(sqrt(x+1)+1))-2*sqrt(2)*%i*x-2*sqrt(2)*%i)/(6*x*sqrt(x+1))=%c];
method;
lie;

/* 191 ode1_lie finds symmetry but ... */
assume(x>0);
[x>0];
(pn_(191),ans:contrib_ode(eqn:4*x^5*'diff(y,x)^2+12*x^4*y*'diff(y,x)+9=0,y,x));
[(LOG((SQRT(x^3*y^2-1)+x^(3/2)*y)/x^(3/2))-LOG((SQRT(x^3*y^2-1)-x^(3/2)*y)/x^(3/2))+3*LOG(x))/3=%C]; /* really?? */
method;
lie;
forget(x>0);
[x>0];

/* 192 Why the complex solution? */
(pn_(192),ans:contrib_ode(eqn:x^6*'diff(y,x)^2-2*x*'diff(y,x)-4*y=0,y,x));
[(2*%i*sqrt(4*x^4*y+1)-2*%i)/(sqrt(2)*sqrt(3)*x^2) = %c];
/* surprisingly this is correct */
expand(sqrt(3)*x^2*ans[1]/(sqrt(2)*%i));
sqrt(4*x^4*y+1)-1 = -sqrt(3)*%i*%c*x^2/sqrt(2);
%,%c=-sqrt(2)*%c/(sqrt(3)*%i);
sqrt(4*x^4*y+1)-1=%c*x^2;
(%+1)^2;
4*x^4*y+1=(%c*x^2+1)^2;
ans:solve(%,y);
[y = (%c^2*x^2+2*%c)/(4*x^2)];
[method,ode_check(eqn,%[1])];
[lie,0];
/* There is a second solution 4*x^4*y+1=0*/

/* 193 */
assume(x>0);
[x>0];
(pn_(193),ans:contrib_ode(eqn:x^8*'diff(y,x)^2+3*x*'diff(y,x)+9*y=0,y,x));
[-(2*SQRT(1-4*x^6*y)+2)/(SQRT(2)*SQRT(3)*x^3) = %C];
/* It works, and the solution can be tidied up */
expand(ans[1]*sqrt(3)*x^3/sqrt(2));
-sqrt(1-4*x^6*y)-1=sqrt(3)*%c*x^3/sqrt(2);
%+1,%c=%c*sqrt(2)/sqrt(3);
-sqrt(1-4*x^6*y)=%c*x^3+1;
%^2;
1-4*x^6*y=(%C*x^3+1)^2;
solve(%,y);
[y=-(%C^2*x^3+2*%C)/(4*x^3)];
[method,ode_check(eqn,%[1])];
[lie,0];
forget(x>0);
[x>0];
/* there is a second solution 4*x^6*y=1 */

/* 194 */
(pn_(194),ans:contrib_ode(eqn:y*'diff(y,x)^2=a,y,x));
[a^2*(4*y^3+a*(-9*x^2+18*%C*x-9*%C^2)) = 0];
ans[1]/a^2;
4*y^3+a*(-9*x^2+18*%C*x-9*%C^2)=0;
solve(%,y);
[y = (SQRT(3)*9^(1/3)*%I-9^(1/3))*a^(1/3)*(x-%C)^(2/3)/(2*4^(1/3)),y = -(SQRT(3)*9^(1/3)*%I+9^(1/3))*a^(1/3)*(x-%C)^(2/3)/(2*4^(1/3)),y=9^(1/3)*a^(1/3)*(x-%C)^(2/3)/4^(1/3)];
[method,ode_check(eqn,%[1]),ode_check(eqn,%[2]),ode_check(eqn,%[3])];
[lagrange,0,0,0];

/* 195 */
(pn_(195),ans:contrib_ode(eqn:y*'diff(y,x)^2=a^2*x,y,x));
[[x = %c*%e^-(2*a^2*(log(%t^3-a^2)/(3*a^2)-log(%t)/a^2)),y = a^2*x/%t^2]];
radcan(%);
[[x=%c*%t^2/(%t^3-a^2)^(2/3),y=a^2*x/%t^2]]; /* Answer seems about right */
method;
lagrange;

/* 196 Crash in lie_FxHx */
/* (pn_(196),ans:contrib_ode(eqn:y*'diff(y,x)^2=exp(2*x),y,x));*/

/* 197 */
(pn_(197),ans:contrib_ode(eqn:y*'diff(y,x)^2+2*a*x*'diff(y,x)-a*y=0,y,x));
[[x=%c*%e^(2*(log(%t^2-a)/(2*a)-log(%t)/a)*a),y=-2*%t*a*x/(%t^2-a)]];
radcan(%);
[[x=-(%c*a-%c*%t^2)/%t^2,y=2*%t*a*x/(a-%t^2)]];
method;
lagrange;

/* 198 */
(pn_(198),ans:contrib_ode(eqn:y*'diff(y,x)^2-4*a^2*x*'diff(y,x)+a^2*y=0,y,x));
[[x=%c*(a^2+%t^2)*%e^(-log(%t^2-3*a^2)/3-4*log(%t)/3),y=4*%t*a^2*x/(a^2+%t^2)]];
ans:radcan(ans);
[[x=(%c*a^2+%c*%t^2)/(%t^(4/3)*(%t^2-3*a^2)^(1/3)),y=4*%t*a^2*x/(a^2+%t^2)]];
method;
lagrange;

/* 252 */
/*(pn_(252),ans:contrib_ode(eqn:a^2*(b^2-(c*x-a*y)^2)*'diff(y,x)^2+2*a*b^2*c*'diff(y,x)+c^2*(b^2-(c*x-a*y)^2)=0,y,x));*/

/* 285 */
(pn_(285),ans:contrib_ode(eqn:'diff(y,x)^3+a*x*'diff(y,x)-a*y=0,y,x));
[y=(%c*a*x+%c^3)/a,y=-2*x*sqrt(-a*x)/(3*sqrt(3)),y=2*x*sqrt(-a*x)/(3*sqrt(3))];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3])];
[clairault,0,0,0];

/* 286 */
(pn_(286),ans:contrib_ode(eqn:'diff(y,x)^3-(a+b*x)*'diff(y,x)+b*y=0,y,x));
[y=(%c*b*x+%c*a-%c^3)/b,y=-2*(b*x+a)^(3/2)/(3*sqrt(3)*b),y=2*(b*x+a)^(3/2)/(3*sqrt(3)*b)];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3])];
[clairault,0,0,0];

/* 297 */
(pn_(297),ans:contrib_ode(eqn:'diff(y,x)^3-'diff(y,x)^2+x*'diff(y,x)-y=0,y,x));
[y=%c*x+%c^3-%c^2,y=-(sqrt(1-3*x)*(6*x-2)-9*x+2)/27,y=(sqrt(1-3*x)*(6*x-2)+9*x-2)/27];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3])];
[clairault,0,0,0];

/* 313 */
(pn_(313),ans:contrib_ode(eqn:x*'diff(y,x)^3-y*'diff(y,x)^2+a=0,y,x));
[y=(%c^3*x+a)/%c^2,y =(3*sqrt(3)*%i-3)*a^(1/3)*x^(2/3)/(2*4^(1/3)),y=-(3*sqrt(3)*%i+3)*a^(1/3)*x^(2/3)/(2*4^(1/3)),y=3*a^(1/3)*x^(2/3)/4^(1/3)];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3]),ode_check(eqn,ans[4])];
[clairault,0,0,0,0];

/* 314 */
(pn_(314),ans:contrib_ode(eqn:x*'diff(y,x)^3+(2*x-y)*'diff(y,x)^2+(x-2*y)*'diff(y,x)+1-y=0,y,x));
[y=((%c^3+2*%c^2+%c)*x+1)/(%c^2+2*%c+1),y=3*(-sqrt(3)*%i/2-1/2)*x^(2/3)/4^(1/3)-x,y=3*(sqrt(3)*%i/2-1/2)*x^(2/3)/4^(1/3)-x,y=(9*x^(2/3)/4^(1/3)-3*x)/3];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3]),ode_check(eqn,ans[4])];
[clairault,0,0,0,0];

/* 320 */
(pn_(320),ans:contrib_ode(eqn:x^2*'diff(y,x)^3-2*x*y*'diff(y,x)^2+y^2*'diff(y,x)+1=0,y,x));
[y=(SQRT(-%C)*%C*x+1)/SQRT(-%C),y=-(3*SQRT(3)*%I-3)*x^(1/3)/(2*4^(1/3)),y=(3*SQRT(3)*%I+3)*x^(1/3)/(2*4^(1/3)),y=-3*x^(1/3)/4^(1/3)];
[method,ode_check(eqn,ans[1]),ode_check(eqn,ans[2]),ode_check(eqn,ans[3]),ode_check(eqn,ans[4])];
[clairault,0,0,0,0];

/* 367 FIXME - check second solution */
(pn_(367),ans:contrib_ode(eqn:'diff(y,x)^n+x*'diff(y,x)-y=0,y,x));
[y=%C*x+%C^n,[-y+%t*x+%t^n=0,(%t*x+n*%t^n)/%t=0]];
[method,ode_check(eqn,ans[1])];
[clairault,0];

/* 373 */
(pn_(373),ans:contrib_ode(eqn:2*sqrt(a*'diff(y,x))+x*'diff(y,x)-y=0,y,x));
[y=%c*x+2*sqrt(%c*a),[-y+%t*x+2*sqrt(a*%t)=0,(sqrt(a*%t)*x+a)/sqrt(a*%t)=0]];
assume(a>0,x<0);
[a>0,x<0];
first(solve(ans[2][2],%t));
%t=a/x^2;
ans[2][1],%;
-y-a/x=0;
s:first(solve(%,y));
y=-a/x;
[method,ode_check(eqn,ans[1]),ode_check(eqn,s)];
[clairault,0,0];
forget(a>0,x<0);
[a>0,x<0];

/* 375 */
(pn_(375),ans:contrib_ode(eqn:2*(1+'diff(y,x))^(3/2)+3*x*'diff(y,x)-3*y=0,y,x));
[y=(3*%c*x+sqrt(%c+1)*(2*%c+2))/3,[-3*y+3*%t*x+2*(%t+1)^(3/2)=0,3*x+3*sqrt(%t+1)=0]];
assume(u>0);
[u>0];
s:subst(u^2-1,%t,ans[2]);
[-3*y+3*(u^2-1)*x+2*u^3=0,3*x+3*u=0];
solve(s[2],u);
[u=-x]; /* So x<0 for singular solution */
s[1],%[1];
-3*y-2*x^3+3*x*(x^2-1)=0;
ans[2]:first(solve(%,y));
y=(x^3-3*x)/3;
[method,ode_check(eqn,ans[1]),(assume(x<0),ode_check(eqn,ans[2]))];
[clairault,0,0];
forget(u>0,x<0);
[u>0,x<0];

/* 381 FIXME - check second solution */
(pn_(381),ans:contrib_ode(eqn:sqrt(a^2+b^2*'diff(y,x)^2)+x*'diff(y,x)-y=0,y,x));
[y=%C*x+sqrt(%C^2*b^2+a^2),[-y+%t*x+sqrt(b^2*%t^2+a^2)=0,(sqrt(b^2*%t^2+a^2)*x+b^2*%t)/sqrt(b^2*%t^2+a^2)=0]];
[method,ode_check(eqn,ans[1])];
[clairault,0];

/* 382 FIXME - check second solution */
(pn_(382),ans:contrib_ode(eqn:sqrt(a+2*b*'diff(y,x)+c*'diff(y,x)^2)+(x*'diff(y,x)-y)*sqrt(a*c-b^2)=0,y,x));
[y=(%c*sqrt(a*c-b^2)*x+sqrt(%c^2*c+2*%c*b+a))/sqrt(a*c-b^2),[-sqrt(a*c-b^2)*y+sqrt(a*c-b^2)*%t*x+sqrt(c*%t^2+2*b*%t+a)=0,(sqrt(a*c-b^2)*sqrt(c*%t^2+2*b*%t+a)*x+c*%t+b)/sqrt(c*%t^2+2*b*%t+a)=0]];
[method,ode_check(eqn,ans[1])];
[clairault,0];

/* 388 FIXME - check second solution */
(pn_(388),ans:contrib_ode(eqn:a*(1+'diff(y,x))^(1/3)+x*'diff(y,x)-y=0,y,x));
[y=%c*x+(%c+1)^(1/3)*a,[-y+%t*x+a*(%t+1)^(1/3)=0,(3*(%t+1)^(2/3)*x+a)/(3*(%t+1)^(2/3))=0]];
[method,ode_check(eqn,ans[1])];
[clairault,0];

/* 389 FIXME - check second solution */
(pn_(389),ans:contrib_ode(eqn:(y-x*'diff(y,x))*sqrt(1+'diff(y,x)^2)+a*'diff(y,x)=0,y,x));
[y=(%c*sqrt(%c^2+1)*x-%c*a)/sqrt(%c^2+1),[sqrt(%t^2+1)*(y-%t*x)+%t*a=0,(%t*y-2*%t^2*x-x+sqrt(%t^2+1)*a)/sqrt(%t^2+1) = 0]];
[method,ode_check(eqn,ans[1])];
[clairault,0];

/* 390 */
(pn_(390),ans:contrib_ode(eqn:y=x*'diff(y,x)+cos('diff(y,x)),y,x));
[y=cos(%c)+%c*x, [y-%t*x-cos(%t)=0,sin(%t)-x=0]];
first(solve(ans[2][2],%t));
%t=asin(x);
s:first(solve(ev(ans[2][1],%),y));
y=x*asin(x)+sqrt(1-x^2);
[method,ode_check(eqn,ans[1]),ode_check(eqn,s)];
[clairault,0,0];

/* 396  FIXME - check second solution */
(pn_(396),ans:contrib_ode(eqn:(1+'diff(y,x)^2)*sin(y-x*'diff(y,x))^2=1,y,x));
[y=%c*x+asin(1/sqrt(%c^2+1)),[(%t^2+1)*sin(y-%t*x)^2-1=0,2*%t*sin(y-%t*x)^2-(2*%t^2*x+2*x)*cos(y-%t*x)*sin(y-%t*x)=0]];
[method,ode_check(eqn,ans[1])];
[clairault,0];

/* 397 FIXME - check second solution */
(pn_(397),ans:contrib_ode(eqn:'diff(y,x)*(acos('diff(y,x))-x)+sqrt(1-'diff(y,x)^2)+y=0,y,x));
[y=%c*x-%c*acos(%c)-sqrt(1-%c^2),[y-%t*x+%t*acos(%t)+sqrt(1-%t^2)=0,(sqrt(1-%t^2)*(acos(%t)-x)-2*%t)/sqrt(1-%t^2)=0]];
[method,ode_check(eqn,ans[1])];
[clairault,0];

/* 402 */
(pn_(402),ans:contrib_ode(eqn:log('diff(y,x))+x*'diff(y,x)+a=y,y,x));
[y = %c*x+a+log(%c),[-y+%t*x+log(%t)+a=0,(%t*x+1)/%t=0]];
/* Eliminate parameter t from singular solution */
(s:first(solve((ans[2])[2],%t)),s:first(solve(ev(first(ans[2]),s),y)));
y = log(-1/x)+a-1;
[method,ode_check(eqn,ans[1]),ode_check(eqn,s)];
[clairault,0,0];

/* 405 */
(pn_(405),ans:contrib_ode(eqn:log('diff(y,x))+a*(x*'diff(y,x)-y)=0,y,x));
[y=(%c*a*x+log(%c))/a,[-a*y+a*%t*x+log(%t)=0,(a*%t*x+1)/%t=0]];
/* Eliminate parameter t from singular solution */
/* (s:first(solve((ans[2])[2],%t)),s:first(solve(ev(first(ans[2]),s),y))); */
s:elim_(ans[2],x,y,%t);
y=(log(-1/(a*x))-1)/a;
[method,ode_check(eqn,ans[1]),ode_check(eqn,s)];
[clairault,0,0];

/* 408 */
(pn_(408),ans:contrib_ode(eqn:'diff(y,x)*log('diff(y,x))-(1+x)*'diff(y,x)+y=0,y,x));
[y=%c*x-%c*log(%c)+%c,[y-%t*x+%t*log(%t)-%t=0,log(%t)-x=0]];
/* Eliminate parameter %t from singular solution */
(s:first(solve((ans[2])[2],%t)),s:first(solve(ev(first(ans[2]),s),y)));
y = %e^x;
[method,ode_check(eqn,ans[1]),ode_check(eqn,s)];
[clairault,0,0];

/* 409 */
(pn_(409),ans:contrib_ode(eqn:log('diff(y,x)*x-y)='diff(y,x),y,x));
[y=%c*x-%e^%c,[log(%t*x-y)-%t=0,-(-y+%t*x-x)/(%t*x-y)=0]];
/* eliminate parameter %t from singular solution */
(s:first(solve((ans[2])[2],%t)),s:first(solve(ev(first(ans[2]),s),y)));
y = x*log(x)-x;
[method,ode_check(eqn,ans[1]),ode_check(eqn,s)];
[clairault,0,0];

/* 410 */
(pn_(410),ans:contrib_ode(eqn:'diff(y,x)*log('diff(y,x)+sqrt(1+'diff(y,x)^2))-sqrt(1+'diff(y,x)^2)-x*'diff(y,x)+y=0,y,x));
[y=%c*x-%c*log(sqrt(%c^2+1)+%c)+sqrt(%c^2+1),[y-%t*x+%t*log(sqrt(%t^2+1)+%t)-sqrt(%t^2+1)=0,log(sqrt(%t^2+1)+%t)-x=0]];
ans[2]:radcan(ans[2]);
[y-%t*x+%t*log(sqrt(%t^2+1)+%t)-sqrt(%t^2+1)=0,log(sqrt(%t^2+1)+%t)-x=0];
ans[2]:ans[2],log(sqrt(%t^2+1)+%t)=asinh(%t);
[y-%t*x+%t*asinh(%t)-sqrt(%t^2+1) = 0,asinh(%t)-x = 0];
solve(ans[2][2],%t);
[%t = sinh(x)];
trigsimp(ev(ans[2][1],%[1]));
y-COSH(x)=0;
ans[2]:first(solve(%,y));
y=cosh(x);
[method,ode_check(eqn,ans[1]),radcan(exponentialize((ode_check(eqn,ans[2]))))];
[clairault,0,0];

/* 416 - requires pdiff package */
block([use_pdiff:true],pn_(416),contrib_ode(eqn:f(x*'diff(y,x)-y)=g('diff(y,x)),y,x));
[f(%c*x-y)=g(%c)];
method;
clairault;
