(load("contrib_ode"),0);
0$

/* Unit tests for odelin.  Inputs are from file de-tests.txt in odelin19.tar.gz */

(kill(all),load('odelin),done);
done;

odelin('diff(y,x,2)+y,y,x);
set (%e^-(%i*x),%e^(%i*x));

odelin('diff(y,x,2)+'diff(y,x,1),y,x);
set (1,%e^-x);

assume(a > b);
[a > b];
odelin(x^2*'diff(y,x,2)+(1-a-b)*x*'diff(y,x,1)+a*b*y,y,x);
set (x^a,x^b);
forget(a > b);
[a > b];

odelin(9*x^2*'diff(y,x,2)+9*x^2*'diff(y,x,1)+2*y,y,x);
set (bessel_j(1/6,-(%i*x/2))*sqrt(-x)*%e^-(x/2),
       bessel_y(1/6,-(%i*x/2))*sqrt(-x)*%e^-(x/2));

odelin(2*x*(x-1)*'diff(y,x,2)+3*(x-1)*'diff(y,x,1)-y,y,x);
set ((x-1)/sqrt(x),
     (log(sqrt(x)+1)*x-log(sqrt(x)-1)*x-2*sqrt(x)-log(sqrt(x)+1)
     +log(sqrt(x)-1))/sqrt(x));

odelin(x^2*'diff(y,x,2)+x*'diff(y,x,1)+x^2*y,y,x);
set (bessel_j(0,-x),bessel_y(0,-x));

odelin(x*'diff(y,x,2)+'diff(y,x,1)+(-4)*y,y,x);
set (bessel_j(0,4*sqrt(-x)),bessel_y(0,4*sqrt(-x)));

odelin(x^2*'diff(y,x,2)+(x^2+x)*'diff(y,x,1)-y,y,x);
set ( (x-1)/x, %e^-x/x );

odelin(3*x*'diff(y,x,2)+(2-x)*'diff(y,x,1)-y,y,x);
set (x^(1/3)*%e^(x/3), gamma_incomplete(-1/3,x/3)*x^(1/3)*%e^(x/3) );

odelin(4*x^2*'diff(y,x,2)+2*x^2*'diff(y,x,1)+(-(x+3))*y,y,x);
set ( (x-2)/sqrt(x), %e^-(x/2)/sqrt(x) );

odelin(x^2*'diff(y,x,2)+(x^2-x)*'diff(y,x,1)+y,y,x);
set (x*%e^-x,gamma_incomplete(0,-x)*x*%e^-x);

odelin(x*'diff(y,x,2)-'diff(y,x,1)+(-x)*y,y,x);
set (bessel_j(1,-%i*x)*x,bessel_y(1,-%i*x)*x);

odelin(3*x^2*'diff(y,x,2)+8*x*'diff(y,x,1)+(x-2)*y,y,x);
set (bessel_j(-(7/3),2*sqrt(x)/sqrt(3))/x^(5/6),
	bessel_y(-(7/3),2*sqrt(x)/sqrt(3))/x^(5/6));

odelin(x*'diff(y,x,2)+(x-1)*'diff(y,x,1)+(-2)*y,y,x);
set (x^2, gamma_incomplete(-2,x)*x^2 );

odelin(x*(x+1)*'diff(y,x,2)+(x+5)*'diff(y,x,1)+(-4)*y,y,x);
set (gauss_a(-6,-2,-3,-x)/x^4,gauss_b(-6,-2,-3,-x)/x^4);

odelin(x*'diff(y,x,2)+(1-x)*'diff(y,x,1)-y,y,x);
set (%e^x,gamma_incomplete(0,x)*%e^x);

odelin(x^2*'diff(y,x,2)-x*(1+x)*'diff(y,x,1)+y,y,x);
set (x*%e^x,gamma_incomplete(0,x)*x*%e^x);

odelin(3*x*'diff(y,x,2)+2*(1-x)*'diff(y,x,1)+(-4)*y,y,x);
set (kummer_m(-1,4/3,-2*x/3)*x^(1/3)*%e^(2*x/3),
	kummer_u(-1,4/3,-2*x/3)*x^(1/3)*%e^(2*x/3));

odelin(x*'diff(y,x,2)+(x+2)*'diff(y,x,1)-y,y,x);
set (kummer_m(-2,0,-x)/x,kummer_u(-2,0,-x)/x);

odelin(x*(1-x)*'diff(y,x,2)+(1/2-4*x)*'diff(y,x,1)+(-2)*y,y,x);
set (sqrt(x)/(x-1)^(5/2),
    (2*sqrt(x-1)*x-3*log(sqrt(x)+sqrt(x-1))*sqrt(x)
     +3*log(sqrt(x-1)-sqrt(x))*sqrt(x)+4*sqrt(x-1)) /(x-1)^(5/2) );

odelin(3*x*(1-x)*'diff(y,x,2)+(1-27*x)*'diff(y,x,1)+(-45)*y,y,x);
set (gauss_a(-4,-2,5/3,x)*x^(2/3)/(x-1)^(23/3),
	gauss_b(-4,-2,5/3,x)*x^(2/3)/(x-1)^(23/3));

odelin(2*x*(1-x)*'diff(y,x,2)+(1-6*x)*'diff(y,x,1)+(-2)*y,y,x);
set ( (log(sqrt(x)+sqrt(x-1))*sqrt(x)-log(sqrt(x-1)-sqrt(x))*sqrt(x)
          -2*sqrt(x-1)) / (x-1)^(3/2),
      sqrt(x)/(x-1)^(3/2) );

odelin(2*x*(1-x)*'diff(y,x,2)+(3-10*x)*'diff(y,x,1)+(-6)*y,y,x);
set ( 1/((x-1)^(5/2)*sqrt(x)), 
     (4*sqrt(x-1)*x^(3/2)-10*sqrt(x-1)*sqrt(x)+3*log(sqrt(x)+sqrt(x-1))
      -3*log(sqrt(x-1)-sqrt(x)))/((x-1)^(5/2)*sqrt(x)) );

odelin(x*(1-x)*'diff(y,x,2)+(1-3*x)*'diff(y,x,1)-y,y,x);
set (1/(x-1),log(x)/(x-1));

odelin(x*(1-x)*'diff(y,x,2)+(2-2*x)*'diff(y,x,1)+(-y)/4,y,x);
set (gauss_a(-1/2,-1/2,0,x)/x,gauss_b(-1/2,-1/2,0,x)/x);

odelin(4*x^2*'diff(y,x,2)+4*x*'diff(y,x,1)+(4*x^2-1)*y,y,x);
set (%e^-(%i*x)/sqrt(x),%e^(%i*x)/sqrt(x));

odelin(9*x^2*'diff(y,x,2)+9*x*'diff(y,x,1)+(9*x^2-16)*y,y,x);
set (bessel_j(-(4/3),-x),bessel_y(-(4/3),-x));

odelin(x^2*'diff(y,x,2)+x*'diff(y,x,1)+(x^2-1)*y,y,x);
set (bessel_j(1,-x),bessel_y(1,-x));

odelin(x^2*'diff(y,x,2)+x*'diff(y,x,1)+x^2*y,y,x);
set (bessel_j(0,-x),bessel_y(0,-x));

odelin(9*x^2*'diff(y,x,2)+9*x*'diff(y,x,1)+(9*x^2-4)*y,y,x);
set (bessel_j(-(2/3),-x),bessel_y(-(2/3),-x));

odelin(x^2*'diff(y,x,2)+x*'diff(y,x,1)+(x^2-16)*y,y,x);
set (bessel_j(4,-x),bessel_y(4,-x));

odelin(x^2*'diff(y,x,2)+x*'diff(y,x,1)+(x^2-1)*y,y,x);
set (bessel_j(1,-x),bessel_y(1,-x));

odelin(x^2*'diff(y,x,2)+x*'diff(y,x,1)+(x^2-4)*y,y,x);
set (bessel_j(2,-x),bessel_y(2,-x));

odelin('diff(y,x,2)+5*'diff(y,x,1)+6*y,y,x);
set (%e^-(3*x),%e^-(2*x));

odelin('diff(y,x,2)+8*'diff(y,x,1)+16*y,y,x);
set (%e^-(4*x),x*%e^-(4*x));

odelin('diff(y,x,2)+'diff(y,x,1)-y,y,x);
set ( %e^(-sqrt(5)*x/2-x/2), %e^(sqrt(5)*x/2-x/2) );

odelin(2*'diff(y,x,2)+7*'diff(y,x,1)+(-4)*y,y,x);
set (%e^-(4*x),%e^(x/2));

odelin('diff(y,x,2)-'diff(y,x,1)+(-11)*y,y,x);
set ( %e^(x/2-3*sqrt(5)*x/2), %e^(3*sqrt(5)*x/2+x/2) );

odelin(4*'diff(y,x,2)+20*'diff(y,x,1)+25*y,y,x);
set (%e^-(5*x/2),x*%e^-(5*x/2));

odelin('diff(y,x,2)-8*'diff(y,x,1)+7*y,y,x);
set (%e^x,%e^(7*x));

odelin('diff(y,x,2)+4*'diff(y,x,1)+8*y,y,x);
set ( %e^(-2*%i*x-2*x), %e^(2*%i*x-2*x) );

odelin('diff(y,x,2)+10*'diff(y,x,1)+25*y,y,x);
set (%e^-(5*x),x*%e^-(5*x));

odelin('diff(y,x,2)+7*y,y,x);
set ( %e^-(sqrt(7)*%i*x), %e^(sqrt(7)*%i*x) );

odelin('diff(y,x,2)+2*'diff(y,x,1)+5*y,y,x);
set ( %e^(-2*%i*x-x), %e^(2*%i*x-x) );

odelin('diff(y,x,2)-2*'diff(y,x,1)+26*y,y,x);
set ( %e^(x-5*%i*x), %e^(5*%i*x+x) );

odelin(x^2*'diff(y,x,2)+6*x*'diff(y,x,1)+6*y,y,x);
set (1/x^3,1/x^2);

odelin(2*x^2*'diff(y,x,2)+13*x*'diff(y,x,1)+15*y,y,x);
set (1/x^3,1/x^(5/2));

assume(x > 0);
[x > 0];
odelin(x^2*'diff(y,x,2)-x*'diff(y,x,1)+17*y,y,x);
set (x^(1-4*%i),x^(4*%i+1));
forget(x > 0);
[x > 0];

odelin(x^2*'diff(y,x,2)+2*'diff(y,x,1)+(-3)*y,y,x);
set (
 kummer_m((sqrt(13)+3)/2,sqrt(13)+1,-(2/x))
   *(x)^(-(sqrt(13)/2)-(1/2))*abs(x)*%e^(2/x),
 kummer_u((sqrt(13)+3)/2,sqrt(13)+1,-(2/x))
   *(x)^(-(sqrt(13)/2)-(1/2))*abs(x)*%e^(2/x)
);

odelin(4*x^2*'diff(y,x,2)+2*x^2*'diff(y,x,1)+(-(x+3))*y,y,x);
set ( (x-2)/sqrt(x), %e^-(x/2)/sqrt(x) );

odelin(x^2*'diff(y,x,2)+(x^2-x)*'diff(y,x,1)+y,y,x);
set (x*%e^-x,gamma_incomplete(0,-x)*x*%e^-x);

odelin(x*'diff(y,x,2)-'diff(y,x,1)+(-x)*y,y,x);
set (bessel_j(1,-%i*x)*x,bessel_y(1,-%i*x)*x);

odelin(3*x^2*'diff(y,x,2)+8*x*'diff(y,x,1)+(x-2)*y,y,x);
set (bessel_j(-(7/3),2*sqrt(x)/sqrt(3))/x^(5/6),
	bessel_y(-(7/3),2*sqrt(x)/sqrt(3))/x^(5/6));

odelin(x*'diff(y,x,2)+(x-1)*'diff(y,x,1)+(-2)*y,y,x);
set (x^2,gamma_incomplete(-2,x)*x^2);

odelin(x*(x+1)*'diff(y,x,2)+(x+5)*'diff(y,x,1)+(-4)*y,y,x);
set (gauss_a(-6,-2,-3,-x)/x^4,gauss_b(-6,-2,-3,-x)/x^4);

odelin(x*'diff(y,x,2)+(1-x)*'diff(y,x,1)-y,y,x);
set (%e^x,gamma_incomplete(0,x)*%e^x);

odelin(x^2*'diff(y,x,2)-x*(1+x)*'diff(y,x,1)+y,y,x);
set (x*%e^x,gamma_incomplete(0,x)*x*%e^x);

odelin(3*x*'diff(y,x,2)+2*(1-x)*'diff(y,x,1)-y,y,x);
set (kummer_m(1/2,4/3,-2*x/3)*x^(1/3)*%e^(2*x/3),
	kummer_u(1/2,4/3,-2*x/3)*x^(1/3)*%e^(2*x/3));

assume(sqrt(2*n-b)*sqrt(2*n+b)>0);
[sqrt(2*n-b)*sqrt(2*n+b)>0];
odelin('diff(y,x,2)+(b^2-(4*n^2-1))/(4*x^2)*y,y,x);
set ( x^(1/2-(sqrt(2*n-b)*sqrt(2*n+b))/2),
     x^((sqrt(2*n-b)*sqrt(2*n+b))/2+1/2) );
forget(sqrt(2*n-b)*sqrt(2*n+b)>0);
[sqrt(2*n-b)*sqrt(2*n+b)>0];

odelin('diff(y,x,2)+(1-2*a)*'diff(y,x,1)/x+(b^2+(a^2-n^2)/x^2)*y,y,x);
set (bessel_j(n,-b*x)*x^a,bessel_y(n,-b*x)*x^a);

odelin('diff(y,x,2)+b^2*x^3*y,y,x);
set (bessel_j(-(1/5),2*abs(b)*x^(5/2)/5)*sqrt(x),
     bessel_y(-(1/5),2*abs(b)*x^(5/2)/5)*sqrt(x));

odelin('diff(y,x,2)+b^2*x^2*y,y,x);
set (bessel_j(-(1/4),-(b*x^2/2))*abs(x)/sqrt(-x),
     bessel_y(-(1/4),-(b*x^2/2))*abs(x)/sqrt(-x));

odelin('diff(y,x,2)+'diff(y,x,1)/x+4*(x^2-n^2/x^2)*y,y,x);
set (bessel_j(n,x^2)*abs(x)/x, bessel_y(n,x^2)*abs(x)/x);

odelin('diff(y,x,2)+'diff(y,x,1)/x+(1-n^2/x)*y/(4*x),y,x);
set (bessel_j(n,sqrt(x)),bessel_y(n,sqrt(x)) );

odelin('diff(y,x,2)+(1-n)*'diff(y,x,1)/x+y/(4*x),y,x);
set (bessel_j(n,sqrt(x))*x^(n/2),bessel_y(n,sqrt(x))*x^(n/2));

odelin('diff(y,x,1) = (-((x^9+4*x^7+6*x^5+4*x^3+x)*'diff(y,x,2)+((-100)*x^7-200*x^5+(-96)*x^3)*y))/(x^8+2*x^6+(-2)*x^2-1),y,x);
set (-bessel_j(5,-(1/(x^2+1))),-bessel_y(5,-(1/(x^2+1))));

odelin('diff(y,x,2) = (-((x^10+x^8+(-10)*x^6+14*x^4+(-7)*x^2+1)*'diff(y,x,1)+(x^7+3*x^5+3*x^3+x)*y))/(x^11-3*x^9+2*x^7+2*x^5+(-3)*x^3+x),y,x);
set (bessel_j(0,-(x/(x^2-1))),bessel_y(0,-(x/(x^2-1))));

odelin('diff(y,x,2) = (-((x^10+3*x^9+2*x^8+(-7)*x^7+(-25)*x^6+(-40)*x^5+(-43)*x^4+(-31)*x^3+(-16)*x^2+(-5)*x-1)*'diff(y,x,1)+(x^7-3*x^5+3*x^3-x)*y))/(x^11+4*x^10+9*x^9+12*x^8+9*x^7+(-9)*x^5+(-12)*x^4+(-9)*x^3+(-4)*x^2-x),y,x);
set (bessel_j(0,-(x/(x^2+x+1))),bessel_y(0,-(x/(x^2+x+1))));

odelin('diff(y,x,2) = (2*x*'diff(y,x,1)-2*y)/x^2,y,x);
set (x,x^2);

odelin('diff(y,x,2) = (-((x^3-5*x^2+4*x)*'diff(y,x,1)+(-x^2+5*x-4)*y))/(x^3-2*x^2),y,x);
set ( x, (x-1)*x*%e^-x );

odelin('diff(y,x,2) = ((x^5-4*x^4+8*x^3+(-4)*x^2-x)*'diff(y,x,1)+(-x^4+4*x^3+(-8)*x^2+4*x+1)*y)/(x^5-3*x^4+2*x^3+(-4)*x^2+x-1),y,x);
set ( x, %e^x/(x^2+1) );

odelin('diff(y,x,2) = ((4*x^5-8*x^4+(15-4*b)*x^3+(4*b-15)*x^2+(4-b)*x)*'diff(y,x,1)+((8*a-8)*x^4+(16-12*a)*x^3+(8*b+6*a-26)*x^2+((-8)*b-a+24)*x+2*b-6)*y)/(2*x^4-3*x^3+x^2),y,x);
set ( kummer_m(a,b,(x-1)*x)*x^2, kummer_u(a,b,(x-1)*x)*x^2 );

odelin('diff(y,x,2) = ((4*a*x^4-8*a*x^3+(7*a-4)*x^2+(4-3*a)*x-1)*'diff(y,x,1)+(8*a^2*x^3-12*a^2*x^2+6*a^2*x-a^2)*y)/(2*a*x^3-3*a*x^2+a*x),y,x);
set ( kummer_m(a,1/a,(x-1)*x), kummer_u(a,1/a,(x-1)*x) );

odelin('diff(y,x,2) = (((8*a-6)*x^6+(24*a-18)*x^5+(42*a-34)*x^4+(44*a-38)*x^3+(30*a-27)*x^2+(12*a-11)*x+2*a-1)*'diff(y,x,1)+(8*a*x^3+12*a*x^2+6*a*x+a)*y)/(2*x^7+7*x^6+15*x^5+20*x^4+19*x^3+12*x^2+5*x+1),y,x);
set (
bessel_y(-((2*a-1)/2),-(%i/(2*(x^2+x+1))))
         *(x^2+x+1)^(a-1/2)*%e^(1/(2*x^2+2*x+2)),
((-1)^((2*a-1)/2)*bessel_i(-((2*a-1)/2),-(1/(2*(x^2+x+1))))
         *(x^2+x+1)^((-((2*a-1)/2))+a-1/2)*%e^(1/(2*x^2+2*x+2)))
    /(-(%i/(x^2+x+1)))^((2*a-1)/2)
);

odelin('diff(y,x,2) = (-(((u+n+1)*x-k)*'diff(y,x,1)+n*u*y))/(x^2-x),y,x);
set (gauss_a(n,u,k,x),gauss_b(n,u,k,x));

odelin('diff(y,x,2) = (-(((u+n+1)*x-15*u+(-15)*n+3*k-15)*'diff(y,x,1)+n*u*y))/(x^2-27*x+180),y,x);
set ( gauss_a(n,u,u+n-k+1,(x-12)/3), gauss_b(n,u,u+n-k+1,(x-12)/3) );

odelin('diff(y,x,2) = (-((2*x^3-k*x^2+(u+n-1)*x)*'diff(y,x,1)+(x^3+(1-k)*x^2+(u+n-1)*x+(-n)*u)*y))/(x^3-x^2),y,x);
set (gauss_a(n-k+1,n,-u+n+1,x)*x^n*%e^-x,
	gauss_b(n-k+1,n,-u+n+1,x)*x^n*%e^-x);

odelin('diff(y,x,2) = (-((18*x^3-69*x^2+96*x)*'diff(y,x,1)+(9*x^3-60*x^2+115*x-304)*y))/(9*x^3-9*x^2),y,x);
set (
  x^(19/3)*%e^-x,
  (x^(16/3)*%e^-x
     *(60*x^5*log(x)-240*x^4*log(x)+360*x^3*log(x)-240*x^2*log(x)
       +60*x*log(x)-60*log(x-1)*x^5+240*log(x-1)*x^4
       -60*x^4-360*log(x-1)*x^3+210*x^3
       +240*log(x-1)*x^2-260*x^2-60*log(x-1)*x+125*x
       -12))
    /(x-1)^4
);

odelin('diff(y,x,2) = (-((46*x^4-92*x^3+32*x^2+14*x-7)*'diff(y,x,1)+(240*x^3-360*x^2+180*x-30)*y))/(2*x^5-5*x^4+2*x^3+2*x^2-x),y,x);
set (
  1/((x-1)^6*x^6),
  (60*x^8*log(x^2-x-1)-240*x^7*log(x^2-x-1)+120*x^6*log(x^2-x-1)
                      +480*x^5*log(x^2-x-1)-300*x^4*log(x^2-x-1)
                      -480*x^3*log(x^2-x-1)+120*x^2*log(x^2-x-1)
                      +240*x*log(x^2-x-1)+60*log(x^2-x-1)+12*x^10-60*x^9
                      +72*x^8+72*x^7-276*x^6+324*x^5+60*x^4-456*x^3
                      +4*x^2+248*x+77)
    / ((x-1)^6*x^6*(x^2-x-1)^4)
);

odelin('diff(y,x,2) = ((5*x^2-20*x+15)*'diff(y,x,1)+30*y)/(x^3-4*x^2+5*x-2),y,x);
set (
(x-1)^6,
((x-1)^5*(60*log(x-1)*x^5-60*log(x-2)*x^5-540*log(x-1)*x^4
   +540*log(x-2)*x^4-60*x^4+1920*log(x-1)*x^3
   -1920*log(x-2)*x^3+450*x^3-3360*log(x-1)*x^2
   +3360*log(x-2)*x^2-1250*x^2+2880*log(x-1)*x
   -2880*log(x-2)*x+1515*x-960*log(x-1)
   +960*log(x-2)-667))
  / (x-2)^4
);

odelin('diff(y,x,2) = (-(((b+2*a+1)*x-b+(-2)*a-8)*'diff(y,x,1)+(a*b+a^2)*y))/(x^2-3*x+2),y,x);
set (gauss_a(a,b+a,7,x-1),gauss_b(a,b+a,7,x-1));

odelin('diff(y,x,2) = (-(((8*a+2)*x^4+(16*a+4)*x^3+(14*a+5)*x^2+(6*a+3)*x+a+1)*'diff(y,x,1)+(8*a^2*x^3+12*a^2*x^2+6*a^2*x+a^2)*y))/(2*x^5+5*x^4+6*x^3+4*x^2+x),y,x);
set ( 1/(x^a*(x+1)^a),
      ('integrate((x^(a-1)*(x+1)^(a-1)*(2*x+1))/(x^2+x+1)^a,x))/(x^a*(x+1)^a)
);

odelin('diff(y,x,2) = (-(8*x*'diff(y,x,1)+(2*x^2-1)*y))/(2*x^2-2),y,x);
set (spherodialwave_a(1,1/2,1/4,-x),spherodialwave_b(1,1/2,1/4,-x));

odelin('diff(y,x,2) = (-((2*x^5+6*x^3)*'diff(y,x,1)+(6*x^2-28)*y))/(x^6-x^4),y,x);
set (
  spherodialwave_a(-3,12,7,-(1/x))*x^5*abs(x)/((x-1)^3*(x+1)^3),
  spherodialwave_b(-3,12,7,-(1/x))*x^5*abs(x)/((x-1)^3*(x+1)^3)
);

odelin('diff(y,x,2) = (-((2*x^5-10*x^4+26*x^3+(-38)*x^2+28*x-8)*'diff(y,x,1)+(6*x^2-12*x-22)*y))/(x^6-6*x^5+14*x^4+(-16)*x^3+9*x^2+(-2)*x),y,x);
set (
  spherodialwave_a(-3,12,7,-(1/(x-1)))*(x-1)^6/((x-2)^3*x^3),
  spherodialwave_b(-3,12,7,-(1/(x-1)))*(x-1)^6/((x-2)^3*x^3)
);

odelin('diff(y,x,2) = (-((8*x^4-16*x^3+12*x^2+(-4)*x)*'diff(y,x,1)+(8*x^5-20*x^4+(-6254)*x^3+9401*x^2+(-4703)*x+784)*y))/(8*x^5-20*x^4+16*x^3+(-4)*x^2),y,x);
set ( bessel_j(28,sqrt(x-1)*sqrt(x)),bessel_y(28,sqrt(x-1)*sqrt(x)));

odelin('diff(y,x,2) = ((-x^2)*'diff(y,x,1)-(2-933156*x)*y)/x^3,y,x);
set ( (bessel_j(1932,2^(3/2)/sqrt(x))*abs(x))/x,
      (bessel_y(1932,2^(3/2)/sqrt(x))*abs(x))/x);

odelin('diff(y,x,2) = (x^6-x^5+x^4+(-4)*x^3-x^2+x-1)*'diff(y,x,1)/(x^6-x^2),y,x);
set ( 1, 'integrate(((x^2+1)*%e^(x-1/x))/(x*(x^2-1)),x) );

odelin('diff(y,x,2) = ((x^7-2*x^6+x^5+(-6)*x^4-x^3-x)*'diff(y,x,1)+(x^6+3*x^4+3*x^2+1)*y)/(x^7-x^3),y,x);
set ( x/((x-1)*(x+1)), (x*%e^(x-(1/x)))/((x-1)*(x+1)) );

odelin('diff(y,x,2) = ((2*x^7-x^6+2*x^5+(-6)*x^4+(-2)*x^3+3*x^2+(-2)*x)*'diff(y,x,1)+(2*x^6+6*x^4+6*x^2+2)*y)/(2*x^7-2*x^3),y,x);
set (
  (sqrt(x-1)*sqrt(x+1)*%e^(x-(1/x)))/sqrt(x),
  (sqrt(x-1)*sqrt(x+1)*%e^(x-(1/x))
    *'integrate(((x^2+1)*%e^(1/x-x))/(sqrt(x-1)*sqrt(x)*sqrt(x+1)*(x^2-1)),x))
   /sqrt(x)
);

odelin('diff(y,x,2) = (-(4*x^4*'diff(y,x,1)-8*a*x^3*'diff(y,x,1)+4*a^2*x^2*'diff(y,x,1)+a^2*'diff(y,x,1)+(-4)*x^3*y+6*a*x^2*y+(-2)*a^2*x*y+a^2*y))/(2*x*(x-a)*(2*x^2-2*a*x+2*x-a)),y,x);
set (
 %e^-x,
 %e^-x*'integrate(((2*x^2+(2-2*a)*x-a)*%e^x)/(sqrt(x)*sqrt(x-a)),x)
);

odelin('diff(y,x,2) = (((2*a+1)*x^3-4*a*x^2+(2*a-1)*x)*'diff(y,x,1)+(((-a-1)*a-a-1)*x^2+(a*(2*a+1)+a-1)*x-a^2)*y)/(x^4-2*x^3+x^2),y,x);
set ( (x-1)*x^a, (x-1)*x^a*log(x) );

odelin(4*x^2*'diff(y,x,2)+4*x*'diff(y,x,1)-y,y,x);
set (1/sqrt(x),sqrt(x));

odelin('diff(y,x,2)+2*'diff(y,x,1)+(-15)*y,y,x);
set (%e^-(5*x),%e^(3*x));

odelin(x*'diff(y,x,2)-(x+1)*'diff(y,x,1)+y,y,x);
set (x+1,%e^x);

odelin(x*'diff(y,x,2)+(1-2*x)*'diff(y,x,1)+(x-1)*y,y,x);
set (%e^x,%e^x*log(x));

odelin('diff(y,x,2)-2*x*'diff(y,x,1)+n*y,y,x);
set ( (kummer_m((n+2)/4,1/2,-x^2)*%e^x^2*sqrt(abs(x)))/sqrt(-x),
      (kummer_u((n+2)/4,1/2,-x^2)*%e^x^2*sqrt(abs(x)))/sqrt(-x) );

odelin((1-x^2)*'diff(y,x,2)-2*x*'diff(y,x,1)+n*(n+1)*y,y,x);
set ( gauss_a(-n,n+1,1,-((x-1)/2)), gauss_b(-n,n+1,1,-((x-1)/2)) );

odelin(x*'diff(y,x,2)+(1-x)*'diff(y,x,1)+n*y,y,x);
set (kummer_m(n+1,1,-x)*%e^x,kummer_u(n+1,1,-x)*%e^x);


