#!/bin/sh

log_file="$1"
known_bugs="`dirname $1`/known-bugs"
echo
echo "*** Summary results for tests recorded in"
echo "*** log file ${log_file}:"
grep "No Errors Found" $log_file
grep "Error summary:" $log_file
grep "Error(s) found in.*:" $log_file
no_err_count=`grep -c "No Errors Found" $log_file`
err_count=`grep -c "Error summary:" $log_file`
if [ "$no_err_count" = "0" ] && [ "$err_count" = "0" ]; then
  echo "Unknown error in log file"
fi
echo
if [ -f "$known_bugs" ]; then
  echo "Expected failures (known bugs in this version of Maxima):"
  cat "$known_bugs"
  echo 
fi
echo "Timing:"
grep time $log_file
echo "*** end of summary for $log_file"
echo
