(in-package :maxima)
;; Cheaper Maxima variable binding. MBIND-DOIT calls $LISTOFVARS on
;; every variable only to check it is a symbol, and MUNBIND-MAKUNBOUND uses
;; generic DELETE with keywords on $VALUES.
(defun mbind-doit (lamvars fnargs fnname)
  (declare (special bindlist))
  (do ((vars lamvars (cdr vars))
       (args fnargs (cdr args)))
      ((cond ((and vars args) nil)
	     ((and (null vars) (null args)))
	     (t (assert fnname (fnname)
			"Expected a maxima function designator but got NIL.")
		(merror (intl:gettext "~A arguments supplied to ~M; found: ~M")
			(if vars (intl:gettext "Too few") (intl:gettext "Too many"))
			(if (and (consp fnname)
				 (consp (car fnname))
				 (eq (caar fnname) 'lambda))
			    fnname
			    (cons (ncons fnname) lamvars))
			(cons '(mlist) fnargs)))))
    (let ((var (car vars)))
      (unless (or (and (symbolp var) var (not (eq var t)))
                  (every 'symbolp (cdr ($listofvars var))))
	  (merror (intl:gettext "Only symbols can be bound; found: ~M") var))
      (let ((value (symbol-values-in var)))
	(let ((mbindp t))
	  (mset var (car args)))
	(psetq bindlist (cons var bindlist)
	       mspeclist (cons value mspeclist))))))
(defun munbind-makunbound (var)
  (makunbound var)
  ;; Remove the first occurrence of VAR from $VALUES, destructively.
  (do ((prev $values tail)
       (tail (cdr $values) (cdr tail)))
      ((atom tail))
    (when (eq (car tail) var)
      (rplacd prev (cdr tail))
      (return))))
