(in-package :maxima)
;; SIMPLIFYA looks up DISTRIBUTE_OVER, OPERS and OPERATORS with three
;; separate GETs. For an operator lacking them each GET walks the whole
;; plist. Prototype: one pass collecting all three.
(defun simplifya (x y)
 (let (op)
  (cond ((or (atom x) (not $simp)) x)
	((atom (car x))
	 (cond ((and (cdr x) (atom (cdr x)))
		(merror (intl:gettext "simplifya: malformed expression (atomic cdr).")))
	       ((get (car x) 'lisp-no-simp)
		x)
	       (t (cons (car x)
			(mapcar #'(lambda (x) (simplifya x y)) (cdr x))))))
	((eq (setq op (caar x)) 'rat) (*red1 x))
	(dosimp (let ((dosimp nil)) (simplifya (unsimplify x) nil)))
	((member-eq 'simp (cdar x)) x)
	((eq op 'mrat) x)
	((stringp op)
	 (simplifya (cons (cons ($verbify op) (rest (car x))) (rest x)) y))
	((not (atom op))
	 (cond ((or (eq (caaar x) 'lambda)
		    (and (not (atom (caaar x))) (eq (caaaar x) 'lambda)))
		(mapply1 op (cdr x) op x))
	       (t (merror (intl:gettext "simplifya: operator is neither an atom nor a lambda expression: ~S") x))))
	(t
	 (let (sa-dist sa-opers sa-w (seen 0))
	   (declare (fixnum seen))
	   (do ((pl (symbol-plist op) (cddr pl)))
	       ((or (atom pl) (= seen 7)))
	     (case (car pl)
	       (distribute_over (unless (logtest seen 1) (setq sa-dist (cadr pl) seen (logior seen 1))))
	       (opers (unless (logtest seen 2) (setq sa-opers (cadr pl) seen (logior seen 2))))
	       (operators (unless (logtest seen 4) (setq sa-w (cadr pl) seen (logior seen 4))))))
	   (cond ((and $distribute_over sa-dist (distribute-over x y)))
		 (sa-opers
		  (let ((opers-list *opers-list)) (oper-apply x y)))
		 ((and (eq op 'mqapply)
		       (or (atom (cadr x))
			   (and (eq substp 'mqapply)
				(or (eq (car (cadr x)) 'lambda)
				    (eq (caar (cadr x)) 'lambda)))))
		  (cond ((or (symbolp (cadr x)) (not (atom (cadr x))))
			 (simplifya (cons (cons (cadr x) (cdar x)) (cddr x)) y))
			((or (not (member-eq 'array (cdar x))) (not $subnumsimp))
			 (merror (intl:gettext "simplifya: I don't know how to simplify this operator: ~M") x))
			(t (cadr x))))
		 ((and sa-w
		       (or (not (member-eq 'array (cdar x)))
			   (rulechk op)))
		  (funcall sa-w x 1 y))
		 (t (simpargs x y))))))))
